### ISSUE TITLE
Change arguments log level from INFO to DEBUG

### ISSUE THREAD

**Issue by varuntestaz** [OpenLineage/OpenLineage#1011]
https://github.com/OpenLineage/OpenLineage/blob/46efab1e7c2a0aa5ebe8d11185fe8d5225c0f78b/integration/spark/app/src/main/java/io/openlineage/spark/agent/EventEmitter.java#L64-L66 sends the Api key and other potentially sensitive URL parameters to the logs. We should change it to use `log.debug`.

**Comment by varuntestaz** [comment]
@howardyoo Are you still working on this? If not, I can create a PR since it's only a one line change.

**Comment by howardyoo** [comment]
No I am not - please go ahead and create a PR for it.

Thanks,
Howard
