### ISSUE TITLE
Frequent timeout while using latest version of 0.12.0 jar in spark lineage

### ISSUE THREAD

**Issue by kumar-gaurav** [OpenLineage/OpenLineage#1012]
The default value of transport in HTTPConfig is set as 5 sec, causing frequent timeout while sending lineage info from spark pipeline.

please increase default value to 60 sec.also, how to set this timeout from configuration?

**Comment by merobi-hub** [comment]
Hello, thanks for opening an issue and welcome to the community! We'll respond as soon as possible. In the meantime, we hope you'll join us on Slack: http://bit.ly/OpenLineageSlack.

**Comment by howardyoo** [comment]
Hi, could you be more specific on the case of how this timeout is occurring?
Perhaps, something that can be scripted to reproduce this issue would be helpful. Thanks!

**Comment by pawel-big-lebowski** [comment]
Hi @kumar-gaurav, I think 5 secs may be good enough as default, but we do miss the ability to provide custom configuration. It is available in `openlineage-java` library but unfortunately spark integration library does not allow this. 

The solution to this would be: 
 * include `timeout` in ArgumentParser -> https://github.com/OpenLineage/OpenLineage/blob/0.12.0/integration/spark/app/src/main/java/io/openlineage/spark/agent/ArgumentParser.java
 * Make use of the parameter when building http transport -> https://github.com/OpenLineage/OpenLineage/blob/0.12.0/integration/spark/app/src/main/java/io/openlineage/spark/agent/EventEmitter.java#L60
 * Describe parameter in readme: https://github.com/OpenLineage/OpenLineage/blob/0.12.0/integration/spark/README.md
* and describe it in docs: https://github.com/OpenLineage/docs/blob/main/docs/integrations/spark/spark.md
