### ISSUE TITLE
SQL Parser Does Not Understand Snowflake Stages

### ISSUE THREAD

**Issue by astronaut-chris** [OpenLineage/OpenLineage#1013]
Receiving the following error in Airflow when trying to [create a Snowflake stage](https://docs.snowflake.com/en/sql-reference/sql/create-stage.html):

```
[2022-08-12, 04:33:44 UTC] {__init__.py:27} ERROR - SQL parser failed: sql parser error: Expected an object type after CREATE, found: STAGE
```

**Comment by merobi-hub** [comment]
Hello, thanks for opening an issue and welcome to the community! We'll respond as soon as possible. In the meantime, we hope you'll join us on Slack if you haven't already: http://bit.ly/OpenLineageSlack.

**Comment by astronaut-chris** [comment]
An example of failing SQL:

```sql
CREATE STAGE IF NOT EXISTS MY_SCHEMA.MY_STAGE
      URL='gcs://my-bucket/my-parquet files'
      FILE_FORMAT=(TYPE=PARQUET, TRIM_SPACE=TRUE)
      COPY_OPTIONS=(MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE)
      storage_integration = MY_GCS_INTEGRATION
```

**Comment by pawel-big-lebowski** [comment]
Related PR in sqlparser-rs https://github.com/sqlparser-rs/sqlparser-rs/pull/833
