### ISSUE TITLE
New Feature: OPENLINEAGE_LOGLEVEL to override default log level of Openlineage via env. variable / config

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1016]
Currently, there is no `global setting` to adjust log levels of OpenLineage in the scope of its package, and because of that, debugging openlineage can be a bit annoying. For example, if we are to log debug messages in OpenLineage, which may be running as part of Apache Airflow, it would generate all the debug messages in Airflow as well, and thus make the troubleshooting part having many unnecessary log messages.

Therefore, I'd like to propose a simple feature for OpenLineage, that it will accept log level coming from the environment variable `OPENLINEAGE_LOGLEVEL` and set the logger's default log level accordingly. For example, having env. variable `OPENLINEAGE_LOGLEVEL=debug` will switch the default logging of all OpenLineage's loggers with debug level.

This configuration could also be inside openlineage.yaml configuration file, so that levels can be adjusted through it.

**Comment by mobuchowski** [comment]
@howardyoo at least for Airflow, this could be configured by your `log_config.py` file like in the tests - https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/tests/integration/tests/airflow/config/log_config.py#L93

**Comment by mobuchowski** [comment]
My idea is that we should have logger configuration infrastructure in `openlineage-python` - with overrides if processing engine sets this themselves like Airflow - and integrations should get local loggers using that infra.

Not yet sure how that would look in Java, since it's logging APIs are more diverse.

**Comment by howardyoo** [comment]
> My idea is that we should have logger configuration infrastructure in `openlineage-python` - with overrides if processing engine sets this themselves like Airflow - and integrations should get local loggers using that infra.
> 
> Not yet sure how that would look in Java, since it's logging APIs are more diverse.

Yes! that approach would work. Yeah. I am also not completely sure about java side, but perhaps we could introduce an abstract logging layer that could hide the end logger implementation - and make it pluggable for users to use slf4j, log4j, etc... 

The things for this logger configuration infrastructure that would be great to have is..:
1. configuration can be made via env. variables - I believe this is important, esp. nowdays, where many applications are containerized and provides env. variable based configs.
2. Have adequate amount of documentation, if the process is not straightforward or easily understood by not so technical developers - so that they could learn how to use it

**Comment by mobuchowski** [comment]
The problem with 1) is that we have different loglevel for different messages - if we don't have control over general log level, the only thing we can do is "flatten" the log level to the one that passes... and that would be extremely confusing.

**Comment by howardyoo** [comment]
> 

I don't understand why would that be a problem. If you look at the code https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/tests/integration/tests/airflow/config/log_config.py#L93 that you mentioned, the airflow configuration does control - what level of log message the openlineage related logs should contain. so, if `OPENLINEAGE_LOGLEVEL=debug`, that would simply mean (in the example for airflow mentioned):
```
    'loggers': {
        'openlineage': {
            'handler': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
```
And when set as such, any log messages having DEBUG and lower would be emitted. Not sure why you think this would be a difficult problem to do. or be extremely confusing. Maybe we can discuss this offline.

**Comment by mobuchowski** [comment]
We don't control that file :)

I mean, in tests we do, but we don't in general case.

**Comment by howardyoo** [comment]
Implementing this specific control may not be feasible - so blocking this for a while.

**Comment by howardyoo** [comment]
Closing this issue, as there is no traction to it.
