### ISSUE TITLE
sql: parser doesn't support CREATE TABLE ... CLONE ...

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#1021]
```
CREATE OR REPLACE TABLE MY_SCHEMA.MY_TABLE_NAME  CLONE MY_SCHEMA.MY_OTHER_TABLE
```
this should produce:
 input : MY_SCHEMA.MY_OTHER_TABLE
 output : MY_SCHEMA.MY_TABLE_NAME

**Comment by mobuchowski** [comment]
Hey @julienledem - this should already work for few releases, we even have test for that - https://github.com/OpenLineage/OpenLineage/blob/a3f281e6d7ac5ac861de4afe22053aee8cc0ab9f/integration/sql/tests/tests_create.rs#L40

Do you have context in which this did not work?

**Comment by mobuchowski** [comment]
Already fixed.
