### ISSUE TITLE
[SQL] SQL parser error on treatment of LOCATION '..'

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1024]
# Problem:
The following SQL statement - when ran against our sql parser, had failed:
```
CREATE EXTERNAL TABLE IF NOT EXISTS  Testing_Versions_latest (
                `ID` INT,
                `ExperimentID` INT,
                `Version` SMALLINT,
                `EnrollmentPeriodInHours` INT,
                `Started` TIMESTAMP,
                `EndDate` TIMESTAMP,
                `IsActive` BOOLEAN,
                `PercentOfSubjectsToEnroll` SMALLINT,
                `Created` TIMESTAMP,
                `Updated` TIMESTAMP,
                        ds STRING
                    )
                    STORED AS PARQUET
                    LOCATION 's3://abc.ingest/sqlserver/Testing/Versions/ds=2022-08-10'
                    TBLPROPERTIES ('parquet.compression'='SNAPPY');
```
The parsing error:
```
- SQL parser failed: sql parser error: Expected column name or constraint definition, found: `
```
Suggests the string `s3://abc.ingest/sqlserver/Testing/Versions/ds=2022-08-10` is not being properly skipped or recognized by the parser in treating `LOCATION`

**Comment by howardyoo** [comment]
> @howardyoo it would help us greatly if you could specify database system on which this does not work - and possibly how you execute that statement.

Hi, @mobuchowski  - Yes, the syntax is of apache 'Hive' query.

**Comment by mobuchowski** [comment]
@howardyoo the query actually parses correctly, if you set proper `Hive` dialect on SQL parser. 

https://github.com/OpenLineage/OpenLineage/compare/sql/add-hive-backtick-test?expand=1

With that, I believe that problem is with usage. If it's Hive using SQL parser, I believe that you're using custom Hive Extractor. It should set `hive` dialect in parser like here: https://github.com/OpenLineage/OpenLineage/compare/sql/add-hive-backtick-test?expand=1#diff-326930b2a9738a16438099ac129639eb681afb692ebd6fefac58b840a31a95e9R31

**Comment by howardyoo** [comment]
> @howardyoo the query actually parses correctly, if you set proper `Hive` dialect on SQL parser.
> 
> https://github.com/OpenLineage/OpenLineage/compare/sql/add-hive-backtick-test?expand=1
> 
> With that, I believe that problem is with usage. If it's Hive using SQL parser, I believe that you're using custom Hive Extractor. It should set `hive` dialect in parser like here: https://github.com/OpenLineage/OpenLineage/compare/sql/add-hive-backtick-test?expand=1#diff-326930b2a9738a16438099ac129639eb681afb692ebd6fefac58b840a31a95e9R31

That is great! Thank you for the info, and also the test case.
