### ISSUE TITLE
[PROPOSAL] Add boring-cyborg Github app

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/OpenLineage#1026]
[Boring Cyborg](https://github.com/kaxil/boring-cyborg) by [@kaxil](https://github.com/kaxil) is a Github app that automates "boring" Github tasks such as PR labeling and new contributor greeting. It also, naturally, makes such actions more consistent and reliable across a project. [Airflow](https://github.com/apache/airflow/blob/main/.github/boring-cyborg.yml) uses the app to label PRs, greet new contributors upon first PRs and issues, congratulate users on merged PRs, and check if branches are up to date prior to merging. 

To add it to the project, we would need to [install the Github app](https://github.com/apps/boring-cyborg), assign it to the repository, and add a `boring-cyborg.yml` file to the `.github` directory.

You can see a configuration file for OpenLineage in my fork here: https://github.com/merobi-hub/OpenLineage/blob/main/.github/boring-cyborg.yml

Airflow's `boring-cyborg.yml`: https://github.com/apache/airflow/blob/main/.github/boring-cyborg.yml

![Screen Shot 2022-08-22 at 11 08 13](https://user-images.githubusercontent.com/68482867/185957617-214cdbfa-979b-4439-a6e0-31dab27eaeac.png)

**Comment by julienledem** [comment]
This sounds good to me. Thanks for proposing!
Other opinions?

**Comment by pawel-big-lebowski** [comment]
Modified path based labelling sounds great.
