### ISSUE TITLE
Multiple start and complete events are emitting 

### ISSUE THREAD

**Issue by MayurMundekar** [OpenLineage/OpenLineage#1041]
Hi Team,

I have integrated OpenLineage in databricks cluster with following configuration.
spark.openlineage.host XXX
spark.openlineage.namespace XXX
spark.openlineage.version XX.

by attaching the cluster to particular notebook and running that notebook lineage data is generating with start and complete event. But those events are generating multiple times for same job of notebook which kind of redundant and data is same both those events.

Do we have option to get only one start and complete event of one job running in notebook ?

**Comment by pawel-big-lebowski** [comment]
Hi @MayurMundekar, could you please provide more details like the code snippet that generates multiple events on Databricks? Single Spark notebook can run several Spark actions or execute several SQLs and for each action/SQL being run .

**Comment by MayurMundekar** [comment]
sure @pawel-big-lebowski  I will share the snippet shortly.

**Comment by MayurMundekar** [comment]
Hi @pawel-big-lebowski , Please find the attachment of code snippet. 
I have create sql file in notebook with two commands drop and create.
After running the notebook open lineage generate 2 files for START and 2 files for COMPLETE event for **"databricks_shell.atomic_create_table_as_select"** JOB. 

**Attachment:-**
[Test.zip](https://github.com/OpenLineage/OpenLineage/files/9423120/Test.zip)

**Other Information**


I have created one api project which have endpoint like http://XXX.net/api/v1/lineage. and this URL i pointed as value of **spark.openlineage.host** in spark config. and using this endpoint i am collecting the lineage data and saving  in json format.

let me know if any other information is required.

Thanks
Mayur

**Comment by wjohnson** [comment]
@MayurMundekar - Just to be sure, your code snippet was just the following:

```sql
-- Databricks notebook source
drop table testtable;
Create table testtable select 'test' as name
```

OpenLineage emits once for every SQL ExecutionStart, Job Start, Job End, and SQL ExecutionEnd.  You should expect to collect all the emit events produced by OpenLineage with the same run id and job name + namespace and combine them to get a complete picture of the events happening on your Spark cluster.

**Comment by MayurMundekar** [comment]
Hi @wjohnson , ok I get it . Now just wanted to be sure for the code snippet which I shared earlier for that the files which are generated I am sharing here can you please just check because the data for run-id is almost same 7611e8b6-c442-4aa2-b3b6-a40432b442ef. can you please take look at that. As I am not seeing much difference I think if take the file based on latest time for this run-id . I will get all data.

**Attachment:**
[DataGeneratedByEvents.zip](https://github.com/OpenLineage/OpenLineage/files/9451948/DataGeneratedByEvents.zip)
