### ISSUE TITLE
Upgrade DB failing in Airflow 2.3.x

### ISSUE THREAD

**Issue by sinjup** [OpenLineage/OpenLineage#1042]
Currently I am running Airflow 2.2.5 with python 3.8 on docker. When trying to upgrade to 2.3.x, db upgrade command is not working properly.
How can I fix the issue?

**Comment by collado-mike** [comment]
Hi! Sorry, but is the issue with your Airflow upgrade OpenLineage related somehow? Or did you mean to open this in the Airflow repo?

**Comment by kacpermuda** [comment]
Closing this as no further information has been provided.
