### ISSUE TITLE
Column Lineage Should Support JDBC Relations

### ISSUE THREAD

**Issue by wjohnson** [OpenLineage/OpenLineage#1048]
Currently, the Column Lineage Input Field Collectors work mainly for Spark SQL operations and Data Source V2.

This leaves out JDBC operations like inserting into a SQL Server or MySQL table.

Column Lineage should support this scenario as many users will want to see column lineage when they interact with JDBC data sources.

**Comment by pawel-big-lebowski** [comment]
This should cover extracting column level lineage from SQL in general and could be a part of our SQL Parser used by both Airflow and Spark integration.

**Comment by mobuchowski** [comment]
@wjohnson I think the way to do this is generate JNI bindings to the SQL parser, like in this blog post: https://blog.frankel.ch/start-rust/7/

I wanted to try this for quite a bit of time, but did not find time yet.

**Comment by mobuchowski** [comment]
Oh, and of course, SQL parser needs to support column-level lineage first 😉

**Comment by wjohnson** [comment]
@hmoazam and I talked about this today and this is a lot bigger than I thought.  Allow me to be the lazy person in the room. Couldn't we implement column lineage for the one table scenario?  We already return "COMPLEX" in certain scenarios due to our SQL Parser limitations in the spark integration.

* [Logical Relation (handleJDBCRelation)](https://github.com/OpenLineage/OpenLineage/blob/b1f8ef2865c74f3cf7af0866bc2c0d72d8cb10f3/integration/spark/shared/src/main/java/io/openlineage/spark/agent/lifecycle/plan/LogicalRelationDatasetBuilder.java#L189)
* [Sql Dw Databricks](https://github.com/OpenLineage/OpenLineage/blob/65a5f021a1ba3035d5198e759587737a05b242e1/integration/spark/shared/src/main/java/io/openlineage/spark/agent/lifecycle/plan/SqlDWDatabricksVisitor.java#L104)
* [Kusto](https://github.com/OpenLineage/OpenLineage/blob/a96ecdabe66567151e7739e25cd9dd03d67e03e8/integration/spark/shared/src/main/java/io/openlineage/spark/agent/lifecycle/plan/KustoRelationVisitor.java#L116)

Granted 2 / 3 are Hanna's and my contributions but we borrowed from the JDBC Relation Handler 😜

If we implemented column lineage with the existing handleJdbcRelation method, we could still get column lineage for JDBC commands that reference a single table.

Is that not a good enough start?

**Comment by mobuchowski** [comment]
Do I understand correctly that you want to add some "workaround" for single table directly in Spark integration; like searching query string for `FROM` and assuming that table name is after that token? 

Might be doable if you want to keep it very simple - this is basically what old SQL parser did, although without column-level lineage. 

On the other hand, if you want to make something more complex, utilizing SQL parser probably would be better. I assume that adding column-level lineage for someone knowing Rust might take 2-3 weeks.

**Comment by wjohnson** [comment]
> @wjohnson Do I understand correctly that you want to add some "workaround" for single table directly in Spark integration; like searching query string for `FROM` and assuming that table name is after that token?

That's right, I want to offer limited support in this case. I haven't dug into it yet but there's also a table property on the JDBCRelation ([Old Spark javadoc](https://spark.apache.org/docs/1.3.0/api/java/org/apache/spark/sql/jdbc/JDBCRelation.html#table())) that might just contain the table name?

> On the other hand, if you want to make something more complex, utilizing SQL parser probably would be better. I assume that adding column-level lineage for someone knowing Rust might take 2-3 weeks.

So... do you happen to know anyone who is a good Rust developer 😅?
