### ISSUE TITLE
[PROPOSAL] package level job metadata

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#105]
# Purpose
To expose information like the version of the job and its source repository, we need a mechanism to provide metadata in the job package when deploying to a scheduler. 
An example of this is deploying DAGs to an Airflow instance, but this is applicable to all package deployments in general. 
In some instances workflows/jobs are directly pulled from a source control system from the scheduler allowing some metadata to be inferred from the environment. In other instances, the jobs are packaged and deployed to a scheduler (example: google cloud composer or astronomer). This doc concerns the later case of providing metadata related to the source code of the job at build time.

(This is based on a Marquez proposal: https://github.com/MarquezProject/marquez/issues/825)

# Proposal
We define a metadata file to be added at the root of the package/deployment location. This file is named **.OpenLineage.job.facets.json** and is a json file with the following initial properties (that can be expanded later).

This also adds "repoUrl", "path", "version", "branch" to the existing SourceCodeLocation facet.

https://github.com/OpenLineage/OpenLineage/blob/6909a3da92ec69e464a90982f6b2c3727353955e/spec/OpenLineage.json#L339-L362

## Properties:
* **sourceCodeLocation.type**: the source control system
Examples: GIT, SVN, ...
* **sourceCodeLocation.url**: the full http URL to locate the file
Example: https://github.com/MarquezProject/marquez-airflow-quickstart/blob/693e35482bc2e526ced2b5f9f76ef83dec6ec691/dags/dummy_example.py
* **sourceCodeLocation.repoUrl**: the URL to the repository
Examples:
   * GIT: git@github.com:{org}/{repo}.git or https://github.com/{org}/{repo}.git
   * SVN: svn://<your_ip>/<repository_name>
* **sourceCodeLocation.path**: the path in the repo containing the source files
Example: path/to/my/dags
It is intended that we can reconstruct a URL from that path pointing to the file defining a job. https://github.com/{org}/{repo}/tree/{version}/{path}/{file path in the package}
* **sourceCodeLocation.version**: the current version deployed (not a branch name, the actual unique version)
Examples:
  * Git: the git sha
  * Svn: the revision number
* **sourceCodeLocation.tag**: optional tag name
Examples: {tag name} 
* **sourceCodeLocation.branch**:optional branch name
## JSON Schema
```
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "sourceCodeLocation": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "repoUrl": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "url"
      ]
    }
  }
}
```
## Example:
For the DAG defined at: https://github.com/MarquezProject/marquez-airflow-quickstart/blob/693e35482bc2e526ced2b5f9f76ef83dec6ec691/dags/dummy_example.py
```
{ 
  "sourceCodeLocation": {
    "type": "GIT",
    "url": "https://github.com/MarquezProject/marquez-airflow-quickstart/blob/693e35482bc2e526ced2b5f9f76ef83dec6ec691/dags/dummy_example.py",
    "repoUrl": "https://github.com/MarquezProject/marquez-airflow-quickstart.git",
    "path": "dags",
    "version": "693e35482bc2e526ced2b5f9f76ef83dec6ec691",
    "branch": "master"
  }
}
```

**Comment by julienledem** [comment]
Here is a PR for adding it to the spec: https://github.com/OpenLineage/OpenLineage/pull/107

**Comment by wslulciuc** [comment]
The new fields for the `sourceCodeLocation` facet look great! I was wondering, can we use a YAML file named `.openlineage.yml` to have the user provided the code metadata and any future metadata for OpenLineage? A YAML file is less verbose for the user to write (no curly braces, quotes, etc) and has the advantage of supporting comments. Also, JSON wasn't designed for configuration files, so I prefer users edit a YAML config file that, for the most part, will contain minimal configuration.

**Comment by wslulciuc** [comment]
Alternatively, we may want to support both file types: `openlineage.yml`, `openlineage.json`

**Comment by mobuchowski** [comment]
I don't think it fits within `sourceCodeLocation`, but having metadata about deployable artifact, like jar MD5, docker image hash would be useful too.
