### ISSUE TITLE
Strange inconsistent output lineage Databricks

### ISSUE THREAD

**Issue by lazowmich** [OpenLineage/OpenLineage#1059]
I'm using version 0.13.0 in Databricks runtime 9.1 and running into a strange ADLS delta table issue in my prod environment I'm unable to really reproduce in any other environment. 

I'm running a sort of orchestration notebook that then starts multiple child notebooks via job rest api on the same cluster with OpenLineage enabled. For most Databricks workspaces this works fine but for one I'm seeing inconsistent and mostly missing output lineage.

I created a simple test orchestration notebook that only starts one child in the prod workspace and another in a test workspace. Both 0.13.0 OpenLineage and 9.1 Databricks. In test I always get correct output lineage and in prod it's very inconsistent. In both, inputs look fine. The notebook should have output lineage for 2 delta tables.

I added multiple log points into the OpenLineage spark library and here is what I noticed:

- In the test workspace the both delta tables output lineage plan is `ReplaceTableAsSelect`
- In prod I either get zero output lineage and `AbstractDatabricksHandler` is never called (I added additional logs to `hasClasses` and `isClass`) or I only get output lineage for one delta table as `ReplaceTableAsSelect` but never both
- I added multiple logs to `sparkSQLExecStart` and `sparkSQLExecEnd` in `OpenLineageSparkListener` and it looks like many `SparkListenerSQLExecutionStart` events are not adding a context to `sparkSqlExecutionRegistry` because in `ContextFactory.createSparkSQLExecutionContext` the method `SQLExecution.getQueryExecution(executionId)` does not find anything. I see many `SparkListenerSQLExecutionEnd` events that cannot find a start context in `sparkSqlExecutionRegistry` and many of them have a `LogicalPlan` of type `ReplaceTableAsSelect` which I'm assuming I want to capture for the expected lineage
- In prod, most of the time when we do get output lineage the Databricks `EnvironmentFacet` does not contain ` spark.databricks.job.runId` or `spark.databricks.job.id` with the values corresponding to the child notebook run like in the test workspace. Instead it contains `spark.databricks.clusterUsageTags.clusterName` which has the run and job id of the parent notebook

The notebooks are in python and the command to write to the delta table is:
```
spark_dataframe
   .write
   .format('delta')
   .mode("Overwrite")
   .saveAsTable(write_location)
```

Could use some guidance on this.

**Comment by pawel-big-lebowski** [comment]
@wjohnson Is it possible for `ADLS delta table` to experience different behavior on different environments?

**Comment by wjohnson** [comment]
@lazowmich - Can you share how your default database is defined in the test and prod environments?

If in the TEST environment, you're using the Databricks provided metastore it will be one code path (not sure which).

If in the PROD environment, you've changed the default database's metastore location to and ADLS G2 path, you would execute a different code path.

With respect to the properties in the Environment Facet, it is only returned on JobStart where the properties are provided. Depending on how Databricks builds the job, they may or may not have all the properties in the job.

**Comment by lazowmich** [comment]
@wjohnson, thanks for responding. If I understand the question correctly, then for both environments we are using the same external hive metastore. 

Even if they were different, shouldn't I still get output lineage just with different paths? I'm always missing output lineage in PROD that I get in TEST. 

For the Environment Facet, since the missing props issue only happens when I get partial output lineage in PROD, I was wondering if it could be related to the missing lineage issue as I've never seen this happen in the other PROD environment I'm running OpenLineage on.

**Comment by lazowmich** [comment]
Looking into it more I think the issue is when Spark triggers start and end events. 

From the logs I added, OpenLineage is getting the start and end events almost at the exact same time. Additionally, the changes to delta tables from my test notebook are very tiny. I’m seeing new parquet files in the kilobytes. Also looking at Spark code [here ](https://github.com/apache/spark/blob/4274fb8806c25519cac829d00b01132fe08c0cac/sql/core/src/main/scala/org/apache/spark/sql/execution/SQLExecution.scala#L131), it looks like once an end event is sent, the `executionId` is removed from the `executionIdToQueryExecution` `ConcurrentHashMap` which is what the `SQLExecution.getQueryExecution` method uses.

My assumption is that for certain notebook runs, Spark processes start and end events so close together that by the time OpenLineage gets the start event and calls [`SQLExecution.getQueryExecution`](https://github.com/OpenLineage/OpenLineage/blob/1d9611110ed1aec3a793664fe0479f388a2ffa01/integration/spark/app/src/main/java/io/openlineage/spark/agent/lifecycle/ContextFactory.java#L32), Spark has already sent the end event and cleared the `SQLExecution` of that execution id and I receive null back.

**Comment by mobuchowski** [comment]
@lazowmich that might very much be the case, and the reason why we're getting flaky tests on Spark relatively often.

**Comment by pawel-big-lebowski** [comment]
@lazowmich @mobuchowski Great investigation! I think I had some similar findings written here: 
https://github.com/OpenLineage/OpenLineage/issues/999#issuecomment-1209048556

The good thing is that Spark's `master` branch already contains a fix for that and `SparkListenerSQLExecutionStart` will contain `QueryExecution`. The bad thing is that, the change is not present in Spark `3.3.1-rc1` branch.

**Comment by lazowmich** [comment]
@pawel-big-lebowski Awesome, glad there is an eventual fix for this from Spark. Just wish I had seen your comment before I spent all this time looking for my issue haha.

Thanks for the help! I'll close this issue since the problem and fix are already known.
