### ISSUE TITLE
sql: support Snowflake's ALTER TABLE SWAP WITH operation

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#1070]
https://docs.snowflake.com/en/sql-reference/sql/alter-table.html

**Comment by denimalpaca** [comment]
@pawel-big-lebowski here are some examples:

`ALTER TABLE coda_dimensional.d_company SWAP WITH coda_dimensional.d_company__copy`

`ALTER TABLE dimensional.d_operating_system SWAP WITH dimensional.d_operating_system__copy`

There are some other `ALTER` commands that don't work, either, but I don't think we actually need lineage data from them. Stuff like:
`ALTER SESSION SET TIMEZONE = 'America/Bogota';`
which I don't know how we'd represent anyway. Also any `ALTER STAGE`, `ALTER WAREHOUSE`, etc.. I think are out of scope for this issue anyway.
