### ISSUE TITLE
Create Docker Hub account

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#1080]
To upload images for our [`proxy`](https://github.com/OpenLineage/OpenLineage/tree/main/proxy) backend, we need to create a [Docker Hub](https://hub.docker.com) account. I suggest we name the account `openlineage`.

Then, we can push images for the proxy backend to the `proxy` repository: 

```
$ docker push openlineage/proxy:[TAG]
```

**Note:** The image will be used by the [Helm Chart](https://github.com/OpenLineage/OpenLineage/pull/1068) for the proxy backend.

**Comment by julienledem** [comment]
Done!
