### ISSUE TITLE
[SQL] Unable to parse INSERT INTO (SELECT...)

### ISSUE THREAD

**Issue by mlecuyer-dna** [OpenLineage/OpenLineage#1082]
## Background
Trying to capture data from an `INSERT INTO (select ...)` query fails at a syntax error in the RUST parser, and returns incorrect/empty results from the python parser.

## Expected Behavior
All input and output tables should be properly parsed and surfaced by the metadata generator. 

## Observed Behavior:
* SQL parser fails with the parentheses if the format is `INSERT INTO schema.table (SELECT...)`

### Rust
```

#[test]
fn test_query() {
    assert_eq!(
        test_sql(
            "
INSERT INTO s.table_a (
    SELECT
        col1,
        col2,
    from s_two.table_x
    WHERE
        condition IS true AND
        condition_2 is false
    GROUP BY 1,2

 --  adding a comment here
    UNION

    SELECT
        col1, col2,
    FROM s_two.table_y
        WHERE
            condition_3 >=  1 AND
            condition_4 < 10
    );
    "
                 ,
        ),
        SqlMeta {
            in_tables: tables(vec!["s_two.table_x", "s_two.table_y"]),
            out_tables: tables(vec!["s.table_a"])
        }
    )
}
```

**Comment by mobuchowski** [comment]
Thanks for the issue and test. The underlying cause is that library we're using to generate SQL's AST - sqlparser-rs - does always interpret left paren `(` after table name in `INSERT INTO` statement as projection. Will try to fix this in the upstream library.

**Comment by mobuchowski** [comment]
Got PR here: https://github.com/sqlparser-rs/sqlparser-rs/pull/667
