### ISSUE TITLE
[SQL][Postgres][Airflow] Datasets for PostgresOperator Aren't Created due to Case Sensitivity

### ISSUE THREAD

**Issue by mlecuyer-dna** [OpenLineage/OpenLineage#1084]
## Background
The PostgresExtractor and all child classes have `_is_case_sensitive`  set to the default of False. Postgres tables and schemas ARE case sensitive, and so this causes the information schema query to return incorrect results (or often times just no results at all) which means that the datasets that a query touches aren't actually created by the downstream processes.

## Possible Fixes
I don't quite know for sure if this is the only issue, but I believe setting `_is_case_sensitive` to `True` for `PostgresExtractor` would solve this issue, and allow the information schema to return proper results.

**Comment by mobuchowski** [comment]
The problem here is that it's case sensitive only if you use double quotes.

```
create table public.TBL (id int primary key );

select *  from public.TbL;
```

and in information schema it is `tbl`.

**Comment by mlecuyer-dna** [comment]
Hmmm... is there a way we can force it to use all lowercase only for the information schema query?

**Comment by mobuchowski** [comment]
@mlecuyer-dna but then you can do 

```
create table public."Tbl" (id int primary key );
```

and it can't be recognized as lowercase then. Maybe there is solution, but would require reorganizing our SQL parser to pass quote information to the part which decides how to create query to information schema.

**Comment by mlecuyer-dna** [comment]
Oh wow, I'm sorry I completely misremembered what I meant to include in this ticket lol. I typed table, but what I meant was schema.

I meant to point to this line: 

https://github.com/OpenLineage/OpenLineage/blob/83a12e1790d470ae6e4d481681f8560d1b6d38c5/integration/airflow/openlineage/airflow/extractors/dbapi_utils.py#L143

but it looks like it's fixed in master already? Or at least there's a flag for it?

**Comment by mlecuyer-dna** [comment]
I'm going to close this, as 
1.) I did an oops and botched the summary by writing table and not schema
2.) Looks like it was already fixed.
