### ISSUE TITLE
DOCS: please add documentation on what facets are 

### ISSUE THREAD

**Issue by leeyspaul** [OpenLineage/OpenLineage#1085]
Missing documentation here: http://openlineage.io/docs/spec/facets/

It would be useful to have these docs available to the public to better understand the components of OpenLineage.

**Comment by howardyoo** [comment]
Yes, it's worthwhile to explain more details about facets.

**Comment by harels** [comment]
closing this, as we have some more docs on the website now. please feel free to reopen if you think differently
