### ISSUE TITLE
spark: fix flaky tests

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#1096]
Here fails `io.openlineage.spark.agent.SparkContainerIntegrationTest [10] spark_v2_drop.py, pysparkV2DropTableStartEvent.json, pysparkV2DropTableCompleteEvent.json, true`

https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/4630/workflows/8fe28cb2-7737-4924-bda5-91d7c7471a47/jobs/56363

and here `testFilteringDeltaEvents`
https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/4634/workflows/3acb2e0a-ee15-45b2-9d5e-b38c00228d6c/jobs/56458

**Comment by tnazarew** [comment]
tests no longer seem to fail, maybe we can close it @mobuchowski

**Comment by pawel-big-lebowski** [comment]
Please be aware of this https://github.com/OpenLineage/OpenLineage/issues/999#issuecomment-1209048556
as this can be a cause of flaky tests (so far unsolvable)

**Comment by mobuchowski** [comment]
It still is a very bad experience. We should strive to remove this problem, maybe by rewriting tests or making them work with larger datasets if that's what will allow us to emit events in time. 

https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/4816/workflows/962d0d0f-e8ce-4aba-947e-e46dc9db59e3/jobs/60092

**Comment by pawel-big-lebowski** [comment]
@mobuchowski indeed Maciej, they didn't it for Spark 3.3.1.To rephrase the problem:
Before we are able to process `SparkListenerSQLExecutionStart`, the `SparkListenerSQLExecutionEnd` is published and query execution is removed from `executionIdToQueryExecution` which we do require for processing start event. 

Are somehow able to check within processing `start` event if there is already an `end` event and get queryExecution from it?
