### ISSUE TITLE
Open lineage spark Listener Not capturing SQL query

### ISSUE THREAD

**Issue by Bishnup1995** [OpenLineage/OpenLineage#1097]
Hi all,
I am using open lineage version 1.14.0 with spark version 3.0. I observed that the spark listener is not capturing the database query. I am running a simple spark job that reads data from Postgres and writes it to hdfs. I am running the spark job from spark-shell. Below is the run command:
`spark-shell --jars openlineage-spark-0.14.0.jar --jars postgresql-42.2.6.jar --conf "spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener" --conf "spark.openlineage.host=http://test01:8085" -- conf "spark.openlineage.parentJobName=spark-job" --conf "spark.openlineage.namespace=my_job_namespace"  --conf "spark.driver.extraClassPath=/DataDrive/sourceCodes/lineage/openlineage-spark-0.14.0.jar"  --master spark://spark01:7077 --driver-memory 5g --conf spark.cores.max=2 --conf spark.executor.instances=2 --conf spark.executor.cores=1`

Below is my sample code:

```
   val jdbcDF = spark.read
    .format("jdbc")
    .option("url", "jdbc:postgresql://dbserver:5432/test")
    .option("user", "postgres")
    .option("password", "password")
    .option("query", "select * from testtable")
    .load()
  val newDf = jdbcDF.withColumn("testColumn_new", jdbcDF.col("testColumn") + 60)
  newDf.write.csv("hdfs://hadoop01:8020/test")
```

Is there anything that I am missing?

**Comment by mobuchowski** [comment]
We have not yet integrated SQL parser with Spark integration, and this depends on this work.

It's on our radar though!

**Comment by pawel-big-lebowski** [comment]
@tnazarew  Didn't we solve it in recent weeks?

**Comment by tnazarew** [comment]
yeah we did, since version 0.21.0
