### ISSUE TITLE
DISCUSSION: Openlineage's behavior when OPNENLINEAGE_URL is not provided.

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1106]
# Overview of the topic
When using OpenLineage, we do see this message in our log:
```
[2022-09-21, 17:12:03 UTC] {factory.py:122} ERROR - Did not find openlineage.yml and OPENLINEAGE_URL is not set
[2022-09-21, 17:12:03 UTC] {factory.py:43} WARNING - Couldn't initialize transport; will print events to console.
```
And it seems like since OPENLINEAGE_URL nor openlineage.yaml is not found, the OpenLineage library would start printing many information into the standard output. But because of this, even though there is no openlineage event actually being emitted to the backend, we do see a lot of messages printed out into the console instead, and that sometimes is annoying - and sometimes fills up the file system with unintended messages.

So, the discussion that I want to start is whether this is a good and expected behavior. By default, the `OPENLINEAGE_DISABLED` is set to `False`, so OpenLineage will continue to run and extract lineage information - into output console. Users may not know about it until they check the logs. Currently the only way to stop the events from printing to the console is to explicitly set `OPENLINEAGE_DISABLED=True.`

# some of my opinions
1. If we couldnt' initialize the transport - why are we printing events to console? Shouldn't we just not do anything?
2. If user wants to see the events being generated into the console, shouldn't there be a more precise way of setting that up, and not do it when there is no URL present?
3. This sort of behavior, may need to be better documented.
4. Also, there is a way to setup openlineage client without using openlineage.yml and setting OPENLINEAGE_URL. I'm not sure doing that will cause error.

# other opinions?
So what do you think? I thought this would be a good topic to have a discussion in the community, to see if this can be improved.

**Comment by mobuchowski** [comment]
Hey @howardyoo. One thing I don't understand is what is your use case? Why would you install a library and not configure it? 

>If we couldnt' initialize the transport - why are we printing events to console? Shouldn't we just not do anything?

I would generally assume that if the integration is installed, it's ment to be used. It's not a behavior of client - something is trying to initialize it. I would assume doing nothing gives false sense of the fact that everything works okay.

>Currently the only way to stop the events from printing to the console is to explicitly set OPENLINEAGE_DISABLED=True.

You can also uninstall the integration.

>Also, there is a way to setup openlineage client without using openlineage.yml and setting OPENLINEAGE_URL. I'm not sure doing that will cause error.

Yes, by using client directly, and passing desired transport. The .yml config method and `OPENLINEAGE_URL` are meant for integrations where end user does not directly control the OL code initialization.

**Comment by howardyoo** [comment]
> Hey @howardyoo. One thing I don't understand is what is your use case? Why would you install a library and not configure it?
> 
> > If we couldnt' initialize the transport - why are we printing events to console? Shouldn't we just not do anything?
> 
> I would generally assume that if the integration is installed, it's ment to be used. It's not a behavior of client - something is trying to initialize it. I would assume doing nothing gives false sense of the fact that everything works okay.
> 
> > Currently the only way to stop the events from printing to the console is to explicitly set OPENLINEAGE_DISABLED=True.
> 
> You can also uninstall the integration.
> 
> > Also, there is a way to setup openlineage client without using openlineage.yml and setting OPENLINEAGE_URL. I'm not sure doing that will cause error.
> 
> Yes, by using client directly, and passing desired transport. The .yml config method and `OPENLINEAGE_URL` are meant for integrations where end user does not directly control the OL code initialization.

We can discuss this in detail off-line.

**Comment by howardyoo** [comment]
I'm moving this to Discussions page, since this is not actually an issue: https://github.com/OpenLineage/OpenLineage/discussions/1118
