### ISSUE TITLE
[SQL] SQL parsing failing with parenthesis around sub-query

### ISSUE THREAD

**Issue by meher404** [OpenLineage/OpenLineage#1113]
Hello! 

Here is a code snippet i am trying to run; and the first query works well, but the second query fails. The only difference being parenthesis around the sub-query. 

Background Context: 
We have a lot of trino queries (000s) that we trigger via Airflow. The idea was to export the meta data specifically the input and output data sources to marquez; so as to get an understanding of most important tables etc. 

```python
from openlineage_sql import parse

sql_simple = """
insert into a.dst_tn  select
  a_1,
  a_2,
  a_3,
  a_4,
  a_5,
  a_6
  from b.src_tn
  where process_date=date('2022-09-23') and hour=5 ;
"""
print(parse([sql_simple], dialect="hive"))

# outputs: {"in_tables": [DbTableMeta { database: None, schema: Some("b"), name: "src_tn" }], "out_tables": [DbTableMeta { database: None, schema: Some("a"), name: "dst_tn" }] }
```
This works as expected! 

The following breaks:
```python

sql_simple = """
insert into a.dst_tn ( select
  a_1,
  a_2,
  a_3,
  a_4,
  a_5,
  a_6
  from b.src_tn
  where process_date=date('2022-09-23') and hour=5 );
"""

print(parse([sql_simple], dialect="hive"))

# outputs: SQL parser failed: sql parser error: Expected ), found: a_1

```

Throws an error!

Can someone help me if this is a bug or feature? 
Is there a way to get the sql parser to work with second type of query? or We will have to update the Queries manually.

**Comment by howardyoo** [comment]
The syntax of having `(` and `)` between the subquery (select statement) is a valid SQL syntax, and therefore should not result in parsing error, so potentially something that we may need to fix.

**Comment by mobuchowski** [comment]
I think this is the same issue as https://github.com/OpenLineage/OpenLineage/issues/1082

**Comment by howardyoo** [comment]
Closing this issue as duplicate.
