### ISSUE TITLE
dbt: postgreSQL database support [INTEGRATION]

### ISSUE THREAD

**Issue by mikekenneth** [OpenLineage/OpenLineage#1120]
### What is the target system?

dbt: adding postgreSQL  database support

### What kind of integration is this?

- [X] Produces OpenLineage metadata
- [ ] Consumes OpenLineage metadata
- [ ] Something else

### How should this integration be implemented?

PostgreSQL being very popular, I suggest we add it in the list of supported Databases for dbt integration.

### Where should this integration be implemented?

- [ ] In the target system
- [X] In the OpenLineage repo
- [ ] Somewhere else

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work

**Comment by mobuchowski** [comment]
@mikekenneth feel free to reach out if you need any help!

**Comment by mikekenneth** [comment]
@mobuchowski, **How would you go about this??**
Based on my understanding, am thinking the way to add PostgreSQL support is as below:

**1- Adapters:** 
https://github.com/OpenLineage/OpenLineage/blob/c0c07f88ecfbe82009865bddacf04f1a989f740b/integration/common/openlineage/common/provider/dbt.py#L30-L35

**2- Namespace extraction** (add PostgreSQL extraction from the profile)
https://github.com/OpenLineage/OpenLineage/blob/c0c07f88ecfbe82009865bddacf04f1a989f740b/integration/common/openlineage/common/provider/dbt.py#L683-L691

**Do you think anything I missed?**

Thanks.
**PS**: This is my first code contribution :smile:

**Comment by mobuchowski** [comment]
@mikekenneth sorry, I haven't seen this comment until now 😞 

Yes, that's what I think needs to be done. There is one more thing: https://github.com/OpenLineage/OpenLineage/blob/c89bb4a86119012d6e079328daff7185259eb3f3/integration/common/openlineage/common/provider/dbt.py#L571

here we extract how many rows and bytes was processed by model execution. I'm not sure if Postgres adapter exposes this information, but if yes, then it would also need to be added.
