### ISSUE TITLE
airflow: support Airflow 2.4

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#1121]
During testing we've found that OpenLineage integration on new Airflow 2.4 is broken due to AIP-45 changes.

We've discussed the issue and unfortunately reverting this is not really possible, nor making non-breaking changes for Airflow that would return previous behavior. We plan to fix that by 2.5 release, tracked separetely from this.

For the 2.4 release we'll get around this problem by using Airflow's `task policy` settings.

**Comment by JDarDagran** [comment]
Closing - 2.4.2 will be supported back again.
