### ISSUE TITLE
[PROPOSAL DOCS] Please link the docs in homepage or somewhere more visible

### ISSUE THREAD

**Issue by leeyspaul** [OpenLineage/OpenLineage#1135]
**Purpose:**
This section gives the context of the proposal. It explains *why* this is needed.
Please describe the corresponding use cases.

The links on the homepage link to blog type references https://openlineage.io/. These docs seem to be much more useful for developers trying to get up and going.

https://openlineage.io/docs/

**Proposed implementation**
This section describes *how* you propose to model it. 
If you are you proposing a new facet, please mention its name and schema.

**Comment by howardyoo** [comment]
SGTM

**Comment by howardyoo** [comment]
This is closed - I'll close it! Thanks!
