### ISSUE TITLE
Secret values are not properly filtered out in RedshiftSQLOperator

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1141]
During the execution of extractor for RedshiftSQLOperator, in the URI for the datasource, attributes like `access_key_id` and `secret_access_key` have sensitive values exposed without getting obfuscated. These sensitive information should be shielded and not be visible when being emitted to OpenLineage.

**Comment by mobuchowski** [comment]
Maybe it's possible to just whitelist potential url query params that we want to pass?

**Comment by howardyoo** [comment]
> Maybe it's possible to just whitelist potential url query params that we want to pass?

that would work - but I do know we should come up with a general standard of how we would remove these sensitive information from the URL, whether we would deny-list sensitive ones, or let allowed ones pass.

**Comment by mobuchowski** [comment]
@howardyoo I was thinking about operator/extractor specific ones. Generally I think we know which ones are relevant for given operator, like host, project name. This might be more relevant for operators that are responsible for it's own lineage.

**Comment by JDarDagran** [comment]
Reopening to implement filtering per operator.
