### ISSUE TITLE
[PROPOSAL] Add a way to programatically register extractors

### ISSUE THREAD

**Issue by sunank200** [OpenLineage/OpenLineage#1154]
**Purpose:**
Currently, all the extractors need to be explicitly be added as `OPENLINEAGE_EXTRACTORS` in env but instead we should have a programatically register them to open lineage. Otherwise, every time we have extractor implemented, it has to be either added to open lineage integrations or one has to use env. 

**Proposed implementation**
Add a way to programatically register extractors.

**Comment by harels** [comment]
DefaultExtractor should cover this
