### ISSUE TITLE
[PROPOSAL] Airflow - Add option to configure openlineage-airflow plugin via Airflow's native configuration mechanism

### ISSUE THREAD

**Issue by saidst** [OpenLineage/OpenLineage#1170]
# Purpose
## Suggestion

Add the configuration via Airflow native’s config file (airflow.cfg) as an additional configuration option to the openlineage-airflow plugin.

## Motivation

Currently, the openlineage-airflow plugin is configured via environment variables or openlineage-specific config file.

For users, which used to configure Airflow via Airflow’s native config file only (airflow.cfg), this leads to a minor "stylistic flaw" as they are required to start with environment variables or work with a 2nd configuration file besides airflow.cfg. 

# Proposed implementation
## airflow.cfg

- Add (foresee) a parameter `openlineage_kwargs` in the lineage-section. 
    - Comparable, to Datahub or OpenMetadata airflow plugin.
- The parameter takes a map encoded as a json string. 
- Through the map, the configuration for the OpenLineageClient is defined. 
- The (possible) keys refer to the parameters the OpenLineageClient takes from user-defined configuration. E.g. url and apikey for HTTP-Transport.

Example
```
[lineage]
backend = openlineage.lineage_backend.OpenLineageBackend
openlineage_kwargs = {
   "url": "<url>",
   "api_key": "<api_key>",
   ...
}
```

## OpenLineageAdapter
- Enhance `get_or_create_openlineage_client()` method to additionally check for `openlineage_kwargs` config parameter.
- Give the configuration via `openlineage_kwargs` a higher precedence then the option via `OpenLineageClient.from_environment()`.

**Comment by mobuchowski** [comment]
Interesting idea. Sure, it could work. The scheme for this conf method should be the same as for `openlineage.yml` though.

**Comment by saidst** [comment]
With regard to sample snippet from `airflow.cfg` above, you mean to reflect t[his data structure](https://github.com/OpenLineage/OpenLineage/tree/main/client/python#config-file) in the `openlineage_kwargs ` attribute?

So something like this?

```
backend = openlineage.lineage_backend.OpenLineageBackend
openlineage_kwargs = {
   "transport": {
     "type": "http",
      "url": "https://backend:5000"
      ...
   }
}
```

**Comment by saidst** [comment]
@mobuchowski , what do you think on the above? thx :)

**Comment by mobuchowski** [comment]
@saidst yeah, that's what I think. We might add additional params, and I'm not looking forward to having different config structure in every integration.

**Comment by saidst** [comment]
Thx. Makes sense

**Comment by saidst** [comment]
Hey, while test-implementing the above, I came across the following questions. Looking for your guidance. Thx in advance.

1. Is an env-var-based configuration of the kafka-transport planned in the python-client (https://github.com/OpenLineage/OpenLineage/blob/main/client/python/openlineage/client/transport/factory.py#L117)

2.  How to fit `namespace` in the configuration data structure? Didn't find a reference to this in docs and code.
What about this?

```
namespace: "default"
transport:
  type: "http"
  url: "https://backend:5000"
  auth:
    type: "api_key"
    api_key: "f048521b-dfe8-47cd-9c65-0cb07d57591e"
 ```

**Comment by mobuchowski** [comment]
@saidst sorry for late reply.

1. I think we want to discourage too much env-var based config, like nested Kafka properties. This is why we introduced file-based configs.
2. probably should be done this way from the start 😉 I've written this some time ago and I don't really remember. Maybe something for Airflow 1?
3. Yes, but best to use keyword arguments. URL is there for historical reasons, before we added `Transport` concept.
4. I think this is a good idea!
5. I think maybe

```
airflow: 
  job_namespace: "default"
transport:
  type: "http"
  url: "https://backend:5000"
  auth:
    type: "api_key"
    api_key: "f048521b-dfe8-47cd-9c65-0cb07d57591e"
```

@JDarDagran any opinions?

**Comment by JDarDagran** [comment]
Hey guys,

sorry for late reply too. I agree with points 1-4. 

When it comes to 5. it's a more general comment:
I don't really like the way Datahub is configured through Airflow config file. 
I'd put the whole configuration under new section `[openlineage]` so it would look like:
```
[openlineage]
config = /path/to/config.yml
namespace = default
url = my_url
api_key = my_key
airflow_disable_source_code = False
extractors = full.path.to.ExtractorClass;full.path.to.AnotherExtractorClass
transport_kwargs = {
   here's what goes from yaml file located by OPENLIENAGE_CONFIG
}
```

This would reflect more what we have in `OPENLINEAGE_` env vars now and is easier to create and to document.

**Comment by mobuchowski** [comment]
>This would reflect more what we have in OPENLINEAGE_ env vars now and is easier to create and to document.

I would rather try to get out of that, and have proper namespaced config. For example, it would be unintuitive to express kafka properties in this way.

**Comment by saidst** [comment]
Had today (after quite a while) the chance to look into this topic.

I agree with @JDarDagran that reflecting all env vars into airflow.cfg, also the ones that are specific to the Airflow integration and do not exist for the python client (Extractors, Disable source code..),  would be useful.

However, it seems that `OPENLINEAGE_` - env vars are accessed in various places of the airflow the integration.
Ideally, from my perspective, we would introduce a central place for interacting with the environment and other ways of passing configuration (e.g. airflow.cfg). For instance, in the OpenLineageAdapter. This requires quite some effort and deliberate planning.
Otherwise, all places which interact with the environment would need to be augmented to also be able to work with airflow.cfg. And this is a bad idea from perspective as creates (further) unwanted coupling and reduces maintainability.

I can deliver a short-term implementation covering the variables currently dealt with in the OpenLineageAdapter (namespace, transport, url, api_key) and used to instantiate the OpenLineageClient. 

Let me know ....
- if this is sufficient for an incremental step and I shall proceed.
- which of the alternatives to follow: the one by @JDarDagran or @mobuchowski.

I don't have a final preference as both have (stylistic) downside from my perspective. I am inclined to @JDarDagran's idea as it is more in line with the env vars which are already out there.

**Comment by mobuchowski** [comment]
Hey @saidst - we're actually working on this with @JDarDagran as part of https://github.com/apache/airflow/issues/29670 - part of AIP-53 that recently was accepted/

>However, it seems that OPENLINEAGE_ - env vars are accessed in various places of the airflow the integration.
Ideally, from my perspective, we would introduce a central place for interacting with the environment and other ways of passing configuration (e.g. airflow.cfg). For instance, in the OpenLineageAdapter. This requires quite some effort and deliberate planning.
> Otherwise, all places which interact with the environment would need to be augmented to also be able to work with airflow.cfg. And this is a bad idea from perspective as creates (further) unwanted coupling and reduces maintainability.


Agreed.
My idea is to centralize this configuration in OL Client - as transport configuration is already developed there. 
Then Airflow integration would just take Airflow configuration, and pass it to client to deserialize it.

**Comment by saidst** [comment]
That sounds good! 
Considering this separate thread, do you see sense for continued efforts in this thread? Or to put it differently, do I get right that you will take it and no implementation efforts from my side are required?

**Comment by mobuchowski** [comment]
Already merged in Airflow. https://github.com/apache/airflow/pull/30735
