### ISSUE TITLE
[PROPOSAL] OpenAPI code generation improvements

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1176]
# Problem
The current java code generation, based on the openapi spec located here: https://github.com/OpenLineage/OpenLineage/tree/main/spec has some limitations.
- The Java client code generation relies on poet library, along with custom parser and generator, which works only for JAVA and is not portable to other target languages.
- The client/server code generation therefore is not provided for python clients, and much of the works are manual.
- Generating docs using the current spec is also limited, as it does NOT have the full facet references.

# Solution
- Devise a better openapi code generation library/tool which can automatically generate client libraries for multiple languages.
- Devise a better spec definition that can be used to create API docs automatically.

**Comment by mobuchowski** [comment]
I think adding another tool for Python is better idea than replacing current one. The code generators usually generate terrible code, and I think the Java one is doing exactly what we want.

**Comment by howardyoo** [comment]
> I think adding another tool for Python is better idea than replacing current one. The code generators usually generate terrible code, and I think the Java one is doing exactly what we want.
> 
> I would also add that we only want to generate spec models, not http client itself as well.

I see, my past experiment with code generation tool was somewhat better than what you described - especially when generating object codes for client libraries. Right now, we have two programming languages: java and python - for clients emitting openlineage events, but if the project becomes more popular, I guess we might see other languages like ruby, golang, javascript, and even c or c++, so just wanted to make sure our current approach of generating code from spec is sustainable.

I just wonder, if anybody has tried using https://github.com/OpenAPITools/openapi-generator and what the experience was like, compared to what we're doing using poet and client code generator...

**Comment by howardyoo** [comment]
I recently took a look at the code generation code in Java client. I am still trying to understand how everything works, but from what I've seen, the generation code seems to have certain limitations:
- does not properly process $refs inside the `properties` on certain specs
- does not support `anyOf` as well as other openapi settings
- fails to retrieve certain Object types - if that object type is not referenced anywhere (on the leaf level)
I definitely feel there are rooms for improvements - since in the future, we should try implementing openlineage clients for other popular languages like golang , ruby, node.js , etc.
