### ISSUE TITLE
[PROPOSAL] add Dependabot to the project for dependency monitoring

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/OpenLineage#1179]
**Purpose:**
The LFAI requires that we employ some mode of dependency monitoring. GitHub offers a built-in solution called [Dependabot](https://docs.github.com/en/code-security/dependabot). It automatically opens PRs to update dependencies when there is a known security issue and/or when a newer version is available. We are already using it in Marquez for security updates. It is very easy to deploy but would require some configuration to be effective for OpenLineage.

**Proposed implementation:**
All configuration is done in a single `dependabot.yml` file in the `.github` directory. There, one can specify particular package ecosystems to be monitored (e.g., `gradle`), the location of their manifests (e.g., `client/java`), the desired frequency of monitoring (e.g., `weekly`), and dependencies to be allowed or ignored.

If we decide to implement this solution, we would need to determine the package managers that need monitoring and the desired frequency, the dependencies to include or exclude, etc. I propose that these determinations could easily be made in a PR. 

**Resources:**
- The Dependabot docs include a [list of package managers currently supported by the tool](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file). 
- An approach to configuring the tool for monitoring a monorepo is covered by [this blog post](https://www.csrhymes.com/2022/03/03/using-github-dependabot-with-a-monorepo.html).

**Comment by mobuchowski** [comment]
Looks good!
