### ISSUE TITLE
Update spec release script with new website location

### ISSUE THREAD

**Issue by rossturk** [OpenLineage/OpenLineage#1181]
The `spec/release.sh` script currently publishes new versions of the spec into the `main` branch of the [OpenLineage.github.io](https://github.com/OpenLineage/OpenLineage.github.io) repository.

We are trying to switch the website deployment process for this site so that it's closer to what happens currently in Marquez: single repo called `website` with the source in `main` and the built site served from `gh-pages`. However, if we make that change now we will break the automatic publication of new spec versions.

First, this release script should instead publish the spec into a new `static/spec` directory in the [website](https://github.com/OpenLineage/website) repo.

**Comment by howardyoo** [comment]
Currently the release.sh residing inside the OpenLineage/OpenLineage repo will push the updated specs into the https://github.com/OpenLineage/website. Once those spec files are pushed, perhaps we could create a GitHub Action to detect it and run `redoc-cli build` to build up the openapi.html within the website repo - and make it available.
