### ISSUE TITLE
[PROPOSAL] Generate deterministic run ids for Airflow tasks

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#1185]
**Purpose:**
Currently, the Airflow integration generates random UUIDs for task runs. With Airflow's introduction of [Deferrable Operators](https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html), task execution follows this workflow:
> * A task instance (running operator) gets to a point where it has to wait, and defers itself with a trigger tied to the event that should resume it. This frees up the worker to run something else.
> * The new Trigger instance is registered inside Airflow, and picked up by a triggerer process
> * The trigger is run until it fires, at which point its source task is re-scheduled
> * The scheduler queues the task to resume on a worker node

Once the task is resumed on the worker node, the run UUID will be randomly generated, meaning that it will not have the same UUID as the start of the task. 

**Proposed implementation**
DagRuns have deterministic UUIDs generated based on the DAG name and the execution time. TaskInstances can have a similarly deterministic UUID based on the task name, the execution date, and the try number

**Comment by wslulciuc** [comment]
@collado-mike, sounds reasonable. Only question I have is whether we care about the semantics of try number vs retry. I mean, try number will also be 1, then increment there on. Anyways, more of a comment than anything 🛳️ it!
