### ISSUE TITLE
Correct OpenLineage spec

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1189]
Fix the references in current OpenLineage spec such that it will reflect correct references to the child Elements under each facets of OpenLineage event spec. For example, the current spec defines DataSet facets as such:
```json
    "Dataset": {
      "type": "object",
      "properties": {
        "namespace": {
          "description": "The namespace containing that dataset",
          "type": "string",
          "example": "my-datasource-namespace"
        },
        "name": {
          "description": "The unique name for that dataset within that namespace",
          "type": "string",
          "example": "instance.schema.table"
        },
        "facets": {
          "description": "The facets for this dataset",
          "type": "object",
          "additionalProperties": {
            "$ref": "#/$defs/DatasetFacet"
          }
        }
      },
      "required": [
        "namespace",
        "name"
      ]
    },
```
But, because of that, the `facets` section does not contain what kind of child properties may be added to it, so the user does not have ways to determine what is legal and what is not legal.

The solution is to add a more definite child facets as such:
```json
    "Dataset": {
      "type": "object",
      "properties": {
        "namespace": {
          "description": "The namespace containing that dataset",
          "type": "string",
          "example": "my-datasource-namespace"
        },
        "name": {
          "description": "The unique name for that dataset within that namespace",
          "type": "string",
          "example": "instance.schema.table"
        },
        "facets": {
          "description": "The common facets for this dataset",
          "type": "object",
          "allOf": [
            { "$ref": "facets/ColumnLineageDatasetFacet.json" },
            { "$ref": "facets/DatasourceDatasetFacet.json" },
            { "$ref": "facets/DataQualityAssertionsDatasetFacet.json" },
            { "$ref": "facets/LifecycleStateChangeDatasetFacet.json" },
            { "$ref": "facets/OwnershipDatasetFacet.json" },
            { "$ref": "facets/SchemaDatasetFacet.json" },
            { "$ref": "facets/StorageDatasetFacet.json" },
            { "$ref": "facets/SymlinksDatasetFacet.json" },
            { "$ref": "facets/DatasetVersionDatasetFacet.json" }
          ],
          "additionalProperties": {
            "$ref": "#/$defs/DatasetFacet"
          }
        }
      },
      "required": [
        "namespace",
        "name"
      ]
    },
```
So that the spec files contain the proper referenced elements.

**Comment by howardyoo** [comment]
@collado-mike , what do you think? This may involve changes in the current OL spec, so wanted to get your feedback on this as well.

**Comment by collado-mike** [comment]
I don't think this does what you think it does. From https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof (bold added for emphasis)

> allOf takes an array of object definitions that are used for independent validation but together **compose a single object**. Still, it does not imply a hierarchy between the models. For that purpose, you should include the [discriminator](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject). **To be valid against allOf, the data provided by the client must be valid against all of the given subschemas**.

That is, you've defined a facet that must have _all_ of the properties defined in _each_ of the facet schemas you included.

The `DatasetFacet` `$ref` should be enough to indicate to users what facets are valid types for this field. It doesn't tell them which facets implement that type, it's true. IDEs can do a good job of that, as the code generator does generate a super class for `DatasetFacet` and each implementation inherits from that super class. Thus the IDE can show all subclasses of the `DatasetFacet` type with a single keyboard shortcut. This is less helpful in languages other than Java, I admit. But I think the solution there is better code generators, not updates to the spec.

**Comment by pawel-big-lebowski** [comment]
Comment in different issue related to a discussion above: https://github.com/OpenLineage/OpenLineage/issues/1190#issuecomment-1301761985

**Comment by howardyoo** [comment]
> I don't think this does what you think it does. From https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/#allof (bold added for emphasis)
> 
> > allOf takes an array of object definitions that are used for independent validation but together **compose a single object**. Still, it does not imply a hierarchy between the models. For that purpose, you should include the [discriminator](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject). **To be valid against allOf, the data provided by the client must be valid against all of the given subschemas**.
> 
> That is, you've defined a facet that must have _all_ of the properties defined in _each_ of the facet schemas you included.
> 
> The `DatasetFacet` `$ref` should be enough to indicate to users what facets are valid types for this field. It doesn't tell them which facets implement that type, it's true. IDEs can do a good job of that, as the code generator does generate a super class for `DatasetFacet` and each implementation inherits from that super class. Thus the IDE can show all subclasses of the `DatasetFacet` type with a single keyboard shortcut. This is less helpful in languages other than Java, I admit. But I think the solution there is better code generators, not updates to the spec.

Hey, thanks for the comments - I see this from the perspective of how 'useful' the spec is, not only for tools like IDE, but for human users who need to understand the spec. It is true that technically, having the ref of `DatasetFacet` is legitimate, and I'm sure it is for the code generator as well.

However, I do want our spec to do more, and be more, so my issue is that when I tried to go through generating open API documentation from our openlineage spec, using tools like [redoc-cli](https://redocly.com/docs/redoc/deployment/cli/), the doc was not really that useful to the users, since under the `facets`, for example, user couldn't see the list of valid facets that can be available for `run`, `job`, `input`, and `output`. All they saw was DatasetFacets, or JobFacets, which were too generic for them to properly learn the specifics.

This is actually in-line with the work related to improving our OL documentation - and one area that Ross and I agreed was that we need to, perhaps, use `redoc-cli` for our next openlineage openapi doc, and believe having these updates to the spec would go a long way.

**Comment by collado-mike** [comment]
Sure, that goal makes sense. Unfortunately, your spec changes aren't going to accomplish that, per the OpenAPI documentation I linked to. We need another way of generating more comprehensive documentation from the spec.

**Comment by howardyoo** [comment]
> Sure, that goal makes sense. Unfortunately, your spec changes aren't going to accomplish that, per the OpenAPI documentation I linked to. We need another way of generating more comprehensive documentation from the spec.

I see, and am open to anything better. This issue is not a PR, so I'd be happy to see if we could highlight any shortcomings of the current OL spec, and make necessary changes that will have a more correct representation of the spec. If there's anybody who wants to take a poke at this, more than happy for them to also chime in.
