### ISSUE TITLE
CI to push spec openapi document into OL website branch

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1191]
# Problem
The current `release.sh` script defined in https://github.com/OpenLineage/OpenLineage/blob/main/spec/release.sh does the following:
```bash
# check if there are any changes in spec in the latest commit
if git diff --name-only --exit-code $PREV_SPEC_COMMIT HEAD 'spec/*.json' >> /dev/null; then
  echo "no changes in spec detected, skipping publishing spec"
  exit 0
fi

echo "Copying spec files from commit $PREV_SPEC_COMMIT"

# Mark last commit on which we finished copying spec
echo "$CIRCLE_SHA1" > "$WEBSITE_COMMIT_FILE"

# Copy changed spec fils to target location
git diff --name-only HEAD~1 HEAD 'spec/*.json' | while read LINE; do
  # extract target file name from $id field in spec files
  URL=$(cat $LINE | jq -r '.["$id"]')

  # extract target location in website repo
  LOC="${WEBSITE_DIR}/${URL#*//*/}"
  LOC_DIR="${LOC%/*}"

  # create dir if necessary, and copy files
  mkdir -p $LOC_DIR
  cp $LINE $LOC
done
```
So, basically it only adds whatever is 'changed' in the spec file, and then puts it into the website repo (so eventually it is available via website). 
However, it does `NOT` do the following:
- Generate openapi.html (spec documentation)
- pushes the updated openapi.html into the appropriate location in website.

# Solution
- Add the code to generate openapi.html (using redoc-cli)
- pushes the updated openapi.html to the appropriate website location
- Make sure all the files version are correct, as well as their json spec urls.

## How to install and run redoc-cli
- https://redocly.com/docs/redoc/deployment/cli/ has comprehensive instructions on installing redoc-cli
Running it is easy. For example, if you want to generate the full openapi.html doc, simply run the below command:
```
redoc-cli build --output ~/temp/openapi.html ./openlineage.yml
```

**Comment by mobuchowski** [comment]
I think this should be done inside website CI, not in this repo CI. The parts that interact between different repos should be as small as possible, if we need to do a lot of cross-repo communication it might be better to just put the website into this monorepo.

**Comment by howardyoo** [comment]
> I think this should be done inside website CI, not in this repo CI. The parts that interact between different repos should be as small as possible, if we need to do a lot of cross-repo communication it might be better to just put the website into this monorepo.

But it does make sense of having this feature located where the 'change' actually happens, so that the change can then be applied to the openapi docs and published into the website. It may be difficult for website to detect, for example, the change made to the spec and pull the changes.

**Comment by rossturk** [comment]
I think I agree with @howardyoo here - this should be triggered on a spec change, and the spec changes in this repo.

**Comment by mobuchowski** [comment]
I propose to keep current spec copying. So 

1. spec is copied to website repo by OL repo ci - because it happens there
2. website is build on website CI repo, which is triggered by process 1.

**Comment by rossturk** [comment]
Once the spec is published into the `openlineage/website` repo, I can set up CI to automatically deploy the site upon merges to main. I can't do it now because the script currently publishes the spec into the generated website repo, not the source website repo, and it would be clobbered by CI.

**Comment by howardyoo** [comment]
> Once the spec is published into the `openlineage/website` repo, I can set up CI to automatically deploy the site upon merges to main. I can't do it now because the script currently publishes the spec into the generated website repo, not the source website repo, and it would be clobbered by CI.

Hey @rossturk , I do believe that according to https://github.com/OpenLineage/OpenLineage/blob/main/spec/release.sh, the spec would get published to the website repo's /spec directory, does it not? BTW, does the /spec/release.sh get called by OpenLineage's circleci workflow whenever the spec changes?

**Comment by rossturk** [comment]
> Hey @rossturk , I do believe that according to https://github.com/OpenLineage/OpenLineage/blob/main/spec/release.sh, the spec would get published to the website repo's /spec directory, does it not? BTW, does the /spec/release.sh get called by OpenLineage's circleci workflow whenever the spec changes?

The current release.sh script publishes the spec into `/spec` in the `openlineage/openlineage.github.io` repository, and it should publish it into the `openlineage/website` repo into `/static/spec`.

Once that happens, we can update `openlineage/website` to build and deploy the site on updates.

**Comment by rossturk** [comment]
The first half of this has now been done with #1295 #1296 #1298 #1299 and #1300.

The second half is being worked on in the website repo: https://github.com/OpenLineage/website/pull/70 - once that is merged successfully, we can close this issue.

**Comment by howardyoo** [comment]
> The first half of this has now been done with #1295 #1296 #1298 #1299 and #1300.
> 
> The second half is being worked on in the website repo: [OpenLineage/website#70](https://github.com/OpenLineage/website/pull/70) - once that is merged successfully, we can close this issue.

Looks like the https://github.com/OpenLineage/website/pull/70 is merged, so I'm going to go ahead and close off this issue.
