### ISSUE TITLE
Include SQL facet for Spark SQL jobs if SQL was executed

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#1250]
Spark SQL is extremely popular usage scenario for Spark. Currently, OpenLineage integration makes use of `LogicalPlan` to prepare OL event. Executed SQL is not even sent within an event. SQL query would have been extremely useful on a backend side to allow data practitioners map Spark jobs to executed code parts.

**Comment by pawel-big-lebowski** [comment]
This does not seem to be easy. 

It seems sql text is being executed within [SparkSession code:](https://github.com/apache/spark/blob/7429223cfd6c53f9d847d58e43190d2a0311f6c4/sql/core/src/main/scala/org/apache/spark/sql/SparkSession.scala#L617) 
```
  def sql(sqlText: String): DataFrame = withActive {
    val tracker = new QueryPlanningTracker
    val plan = tracker.measurePhase(QueryPlanningTracker.PARSING) {
      sessionState.sqlParser.parsePlan(sqlText)
    }
    Dataset.ofRows(self, plan, tracker)
  }
```
The method above loses `sqlText` which is translated to a plan.  The `ofRows` method within `Dataset.scala` looks like:
```
 /** A variant of ofRows that allows passing in a tracker so we can track query parsing time. */
  def ofRows(sparkSession: SparkSession, logicalPlan: LogicalPlan, tracker: QueryPlanningTracker)
    : DataFrame = sparkSession.withActive {
    val qe = new QueryExecution(sparkSession, logicalPlan, tracker)
    qe.assertAnalyzed()
    new Dataset[Row](qe, RowEncoder(qe.analyzed.schema))
  }
}
```
and this is a method that creates `QueryExecution`. 

Openlineage integration within Spark relies on `QueryExecution` objects and `sqlText` is not present anymore when such object is instantiated.

**Comment by mobuchowski** [comment]
I guess we could have that if we had state?

**Comment by pawel-big-lebowski** [comment]
Based on the comment above, fetching executed SQL is not feasable within current integration model. Although a title of the issue is *"Include SQL facet"*, I think the real intention is:
 
*"Provide a human readable job identifier to let users understand which Spark job or which part of the Spark job is responsible for triggering the OpenLineage event found on the backend"*. 

Having the problem rewritten to such a form, we could replace `SQL facet` with `ExplainQueryFacet` that contains an explained query execution, for example: 
```
EXPLAIN EXTENDED select k, sum(v) from values (1, 2), (1, 3) t(k, v) group by k;
...
== Optimized Logical Plan ==
 Aggregate [k#47], [k#47, sum(cast(v#48 as bigint)) AS sum(v)#50L]
 +- LocalRelation [k#47, v#48]
...
```

**Comment by pawel-big-lebowski** [comment]
Not able to extract SQL while the explain part is already contained within `LogicalPlanFacet`.
