### ISSUE TITLE
[Integration][Airflow] DefaultExtractor should accept `task_instance` argument in on_complete extract method.

### ISSUE THREAD

**Issue by JDarDagran** [OpenLineage/OpenLineage#1256]
DefaultExtractor implements logic to run `get_openlineage_facets_on_complete` when defined in the operator. It should serve as replacement for `extract_on_complete` in extractors. However, DefaultExtractor does not pass `task_instance` argument which results in the error: `TypeError: get_openlineage_facets_on_complete() missing 1 required positional argument: 'task_instance'`.

**Comment by rajaths010494** [comment]
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/92459020/200528970-a1c7a696-209b-495e-9211-dcac53971b79.png">

**Comment by rajaths010494** [comment]
When is this expected to be released?

**Comment by JDarDagran** [comment]
@rajaths010494 it's first business day of each month [(https://github.com/OpenLineage/OpenLineage/blob/main/GOVERNANCE.md#release-cadence](https://github.com/OpenLineage/OpenLineage/blob/main/GOVERNANCE.md#release-cadence)) so you can expect it 1st/2nd of December

**Comment by pankajastro** [comment]
> @rajaths010494 it's first business day of each month [(https://github.com/OpenLineage/OpenLineage/blob/main/GOVERNANCE.md#release-cadence](https://github.com/OpenLineage/OpenLineage/blob/main/GOVERNANCE.md#release-cadence)) so you can expect it 1st/2nd of December

Hi @JDarDagran, Would it be possible to do a patch release for this? We are blocked because of this. Thank you!

**Comment by JDarDagran** [comment]
Hey, the voting for the release was successful yesterday. We should expect release today.
