### ISSUE TITLE
Python client: add facets validator

### ISSUE THREAD

**Issue by JDarDagran** [OpenLineage/OpenLineage#1257]
Base facets are defined as JSON Schema files in `spec` directory. There could be validation step done in CI process to compare attr-decorated facets classes to those from spec.

**Comment by howardyoo** [comment]
I like this idea, and in the future, maybe we could even generate python clients completely via code generation, much similar to how we're doing with java clients.

**Comment by JDarDagran** [comment]
We could generate but I foresee some issues. One of them is that we mark some fields in Python to skip redaction. That's probably possible to do that when generating but harder and more complex, maybe unreadable too.

**Comment by mobuchowski** [comment]
@howardyoo yes - but probably we'd need to write our code generator too.

**Comment by kacpermuda** [comment]
@JDarDagran Should this be closed now that #2520 is merged?
