### ISSUE TITLE
Spark extractor is very verbose

### ISSUE THREAD

**Issue by harels** [OpenLineage/OpenLineage#1260]
The Spark extractor can emit very large events, that contains a lot of data.
This might be overloading both in terms of information content (with irrelevant data) as well as causing performance issues.
We would want to research what should included / excluded when sending over the OL event from Spark jobs

**Comment by pawel-big-lebowski** [comment]
worth linking this PR #1271 - which adds the ability to exclude specified facets and excludes by default `spark_unknown` facet.
