### ISSUE TITLE
[INTEGRATION] Airflow DBT cloud integration

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1261]
### What is the target system?

Apache Airflow + DBT Cloud

### What kind of integration is this?

- [X] Produces OpenLineage metadata
- [ ] Consumes OpenLineage metadata
- [ ] Something else

### How should this integration be implemented?

This integration will produce OpenLineage events by implementing Extractor for Apache Airflow's DBT cloud operators outlines here: https://airflow.apache.org/docs/apache-airflow-providers-dbt-cloud/stable/operators.html :
The proposed extractor will be executed during the run of the following operators:
1. DbtCloudRunJobOperator
2. DbtCloudJobRunSensor

When the run job operator runs as 'sync' mode (meaning the operator waits until the completion of the DBT cloud job) - then the extractor, upon completion of the run, will try to obtain the run artifacts from DBT cloud and then produce lineage data and emit it. So, in case the DbtCloudRunJob Operator times out without seeing the end of the DBT job to be completed, since the lineage data cannot be created, it will emit failed event with error facet to indicate the lineage data won't be available due to the timeout instead.

When the run job operator runs as 'async' mode, then the extractor will not perform such operation, but would delegate that to the DbtCloudJobRunSensor. DbtCloudJobRunSensor pretty much waits for the job completion, and upon completion, performs the same logic of retrieving job runs and extracting lineage data from it.

### Where should this integration be implemented?

- [ ] In the target system
- [X] In the OpenLineage repo
- [ ] Somewhere else

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work

**Comment by mobuchowski** [comment]
I think there is one problem here, we lack `profiles.yml` file that we use to get the dataset naming right in `dbt cli`. Not sure how to solve this, maybe there is additional metadata `dbt cloud` has.

Also, the integration should use metadata processor from `integration/common`, modifying it to work with data gathered from HTTP requests, not only files.

**Comment by virajmparekh** [comment]
Thanks for writing this up @howardyoo ! Few things:
- This will also work for the async operators that we've developed right? 
https://github.com/astronomer/astronomer-providers/tree/main/astronomer/providers/dbt/cloud

- Will there be any changes to user DAG code for this?

- Remind me again, why aren't we implementing this in the target repo?

- Can you give a breakdown of what lineage information will be collected? Will it be equivalent to what gets collected with the dbt ol wrapper?

**Comment by howardyoo** [comment]
> I think there is one problem here, we lack `profiles.yml` file that we use to get the dataset naming right in `dbt cli`. Not sure how to solve this, maybe there is additional metadata `dbt cloud` has.
> 
> Also, the integration should use metadata processor from `integration/common`, modifying it to work with data gathered from HTTP requests, not only files.

So, I did some research and it looks like the information that our integration needs from the profiles.yml can be provided from the dbt cloud's REST API, so I don't believe we would need `profiles.yml` (good news).

Yes, I did check the metadata processor under that location (thank you for mentioning that!) - I think we might be able to create a new metadata processor that can work both for dbt core and dbt cloud, with some addition of methods.

**Comment by howardyoo** [comment]
> Thanks for writing this up @howardyoo ! Few things:
> 
> * This will also work for the async operators that we've developed right?
>   https://github.com/astronomer/astronomer-providers/tree/main/astronomer/providers/dbt/cloud
> * Will there be any changes to user DAG code for this?
> * Remind me again, why aren't we implementing this in the target repo?
> * Can you give a breakdown of what lineage information will be collected? Will it be equivalent to what gets collected with the dbt ol wrapper?

- Yes, it will.
- No, the target is to have no code change on DAG side, so the lineage generate happens transparently (by OL extractor)
- Not sure what you mean by `target repo` 
- The initial goal would be to have identical set of data collected that from the dbt ol wrapper - not going to introduce anything new here, unless it is necessary.

**Comment by sungchun12** [comment]
Watching this issue!

**Comment by howardyoo** [comment]
this Integration will be in blocked state - as a future improvement related to newer version of Airflow needs to take place first in order to resolve the 'timeout' issue related to extracting dbt cloud artifacts. Apparently, the way the current extractor is handled is via a thread that will time-out after 30 seconds of it running, whether the extraction finishes or not.

Checking, downloading, processing, and submitting lineage data may take longer than that period, so the work is currently not so readily achievable.
