### ISSUE TITLE
SQL Parser (Snowflake) Bug

### ISSUE THREAD

**Issue by fritz-astronomer** [OpenLineage/OpenLineage#1333]
Valid SQL
```
ALTER SESSION SET QUERY_TAG = 'FOO' ;
 
INSERT
....
```

returns
```
SQL parser failed: sql parser error: Expected TABLE, found: SESSION
```

https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/parser.rs#L3160
looks like only `ALTER TABLE` is recognized

**Comment by fritz-astronomer** [comment]
Additional failures reported in larger SQL query. 
- `INSERT ALL WHEN` is a [feature of Snowflake](https://docs.snowflake.com/en/sql-reference/sql/insert-multi-table.html)
- `%(foo)s` - query parameterization is not recognized in this form (the valid form for the snowflake connector)

Query
```
ALTER SESSION SET QUERY_TAG = %(QUERY_TAG) s;

INSERT ALL
    WHEN (SELECT COUNT(1) = 0 FROM DATABASE_B.TABLE_B) THEN
        INTO DATABASE_B.TABLE_B (
             HOSTUSERID, HOSTID, USERID, CREATEDATE, LASTUPDATED, STATUS, QLK_CHANGE_SEQ,
             QLK_CHANGE_OP,
             QLK_LOAD_TIMESTAMP, SRC_STG_LOAD_TS, IS_ACTIVE, IS_PROCESSED
        )
SELECT HOSTUSERID
     , HOSTID
     , USERID
     , CREATEDATE
     , LASTUPDATED
     , STATUS
     , QLK_CHANGE_SEQ
     , QLK_CHANGE_OP
     , QLK_LOAD_TIMESTAMP
     , CURRENT_TIMESTAMP AS SRC_STG_LOAD_TS
     , 'Y'               AS IS_ACTIVE
     , 'N'               AS IS_PROCESSED
FROM DATABASE_A.TABLE_A;


INSERT INTO DATABASE_B.TABLE_B
( HOSTUSERID
, HOSTID
, USERID
, CREATEDATE
, LASTUPDATED
, STATUS
, QLK_CHANGE_SEQ
, QLK_CHANGE_OP
, QLK_LOAD_TIMESTAMP
, SRC_STG_LOAD_TS
, IS_ACTIVE
, IS_PROCESSED)
SELECT SRC.HOSTUSERID
     , SRC.HOSTID
     , SRC.USERID
     , SRC.CREATEDATE
     , SRC.LASTUPDATED
     , SRC.STATUS
     , SRC.QLK_CHANGE_SEQ
     , SRC.QLK_CHANGE_OP
     , SRC.QLK_LOAD_TIMESTAMP
     , CURRENT_TIMESTAMP AS SRC_STG_LOAD_TS
     , 'Y'               AS IS_ACTIVE
     , 'N'               AS IS_PROCESSED
FROM DATABASE_A.TABLE_A SRC
         LEFT OUTER JOIN DATABASE_B.TABLE_BTGT
                         ON IFNULL(SRC.HOSTUSERID, '0') = IFNULL(TGT.HOSTUSERID, '0')
                             AND SRC.QLK_CHANGE_SEQ = TGT.QLK_CHANGE_SEQ
WHERE SRC.QLK_LOAD_TIMESTAMP > % (PRCSSNG_RNGE_STRT_DT_TM)s
 	AND SRC.QLK_LOAD_TIMESTAMP <=  %(PRCSSNG_RNGE_END_DT_TM)s
 	AND TGT.QLK_CHANGE_SEQ IS NULL;


UPDATE DATABASE_B.TABLE_BT
SET IS_ACTIVE = S.FINAL_STATUS
FROM (SELECT HOSTUSERID
           , QLK_CHANGE_SEQ
           , CASE
                 WHEN ROW_NUMBER() OVER
                     (PARTITION BY
                         HOSTUSERID
                     ORDER BY QLK_CHANGE_SEQ DESC) = 1 THEN 'Y'
                 ELSE 'N' END AS FINAL_STATUS
      FROM DATABASE_B.) TABLE_B AS S
WHERE IFNULL(T.HOSTUSERID, '0') = IFNULL(S.HOSTUSERID, '0')
  AND T.QLK_CHANGE_SEQ = S.QLK_CHANGE_SEQ
  AND T.IS_ACTIVE <> S.FINAL_STATUS;

UPDATE DATABASE_B.TABLE_B
SET IS_ACTIVE = 'N'
WHERE UPPER(QLK_CHANGE_OP) = 'DELETE'
  AND IS_ACTIVE = 'Y';

SELECT 
    COALESCE(
       MAX(TO_CHAR(QLK_LOAD_TIMESTAMP, 'YYYY-MM-DD HH:MI:SS')),
       '1900-12-31 00:00:00'
    ) AS NEW_PRCSSNG_RNGE_STRT_DT_TM,
    %(QUERY_TAG)s AS ABC_QUERY_TAG
FROM DATABASE_B.TABLE_B;
```

**Comment by fritz-astronomer** [comment]
We should also consider allowing partial failures if we can't parse one query in many of a SQL script

**Comment by mobuchowski** [comment]
I think we have this idea: https://github.com/OpenLineage/OpenLineage/issues/1052 however partial failure should be somehow indicated too.

**Comment by JDarDagran** [comment]
#1052 seems to se be aiming into sending some sort of fail facet that tells you why parser failed. @fritz-astronomer suggested we could continue on parsing next statements (separated by `;` I guess) even if previous failed. I'm not sure if that's possible with the current implementation of parser in Rust. However, even in this case, it may not be desired behaviour in some cases, instead enabling this could be configurable.

**Comment by howardyoo** [comment]
Perhaps for most of the run-time errors, we might leverage this : https://github.com/OpenLineage/OpenLineage/blob/main/spec/facets/ErrorMessageRunFacet.json . I do not believe there's any extractor that actually uses this facet, and it's not being displayed in the lineage UI, but in the future there is a plan for UI to support displaying this, so...

**Comment by mobuchowski** [comment]
@howardyoo `ErrorMessageRunFacet` is ment for execution time failures, not failures in extraction.

**Comment by howardyoo** [comment]
> @howardyoo `ErrorMessageRunFacet` is ment for execution time failures, not failures in extraction.

I see. That's fine. Thanks for letting me know. I'm sure you'll think of an appropriate ways to indicate error condition, @mobuchowski :-)
