### ISSUE TITLE
Extractor for Cloud Storage (S3, Azure, GCS) to Snowflake

### ISSUE THREAD

**Issue by manmeetkaur** [OpenLineage/OpenLineage#1335]
**Purpose:**
One of the most common use-case in data pipelines is when the data moves from Cloud Storage (AWS, GCP or Microsoft Cloud Storage) to Snowflake. Currently no extractor exists for this.

Example Use-Case:
- Load data or Ingest raw data from S3 to Snowflake using S3ToSnowflakeOperator

**Proposed implementation**
- I have currently implemented separate extractors for S3ToSnowflake, GCSToSnowflake etc. Planning to abstract out what we can and setting up a class that can be inherited. if it will not be possible, I can keep these separate. Will post my PR tagged to this issue and keep pushing updates.

**Comment by JDarDagran** [comment]
@manmeetkaur thank you for creating the issue. It would be so great of you to post the PR! I'll be glad to help in case of any questions.

**Comment by manmeetkaur** [comment]
@JDarDagran I am unable to push a branch up to the repo, getting Access Denied. Could you please help ? 
```➜  extractors git:(feature/extractor_s3_to_snowflake) git push origin feature/extractor_s3_to_snowflake
remote: Permission to OpenLineage/OpenLineage.git denied to manmeetkaur.
fatal: unable to access 'https://github.com/OpenLineage/OpenLineage.git/': The requested URL returned error: 403
```
