### ISSUE TITLE
[Bug] dbt-ol test breaks lineage graph

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1354]
Issue:
When running the following three dbt commands:

`dbt-ol docs generate && dbt-ol run && dbt-ol test`

I found that my lineage graph gets built as expected after `run`, then tasks and datasets are un-coupled across models after running `test`. So, after the `run` command, I would have a graph showing 3 tasks and 3 datasets linked together. Then, after the `test` command, each of those pairs of tasks and datasets generated by the models will be their own graph, missing their former upstream and downstream neighbors.

Expected behavior:
Graph should remain intact with upstream and downstream tasks and datasets after `dbt-ol test` command.

Using:
```
openlineage-airflow==0.13.1
openlineage-dbt==0.16.1
openlineage-integration-common==0.16.1
openlineage-python==0.16.1
openlineage_sql==0.13.1
```

**Comment by mobuchowski** [comment]
@denimalpaca can you send the events somewhere else to see how they look like, or at least how to reproduce?

**Comment by denimalpaca** [comment]
Sure, how to reproduce:

- Set up a dbt project and OpenLineage environment
- Run `dbt-ol docs` and `dbt-ol run`
- Check Astro or Marquez UI for lineage graph
- Run `dbt-ol test`
- Refresh Astro or Marquez UI page
