### ISSUE TITLE
[PROPOSAL] OpenLineage client side proxy as a sidecar

### ISSUE THREAD

**Issue by fm100** [OpenLineage/OpenLineage#1412]
# Problem Statements
Currently OpenLineage integrations are directly sending events to the configured backend, which is not flexible enough for some situations such as 
- Not responsive backend due to an outage or a network issue
- Long latency of the API that adds extra delay to the processing

The first scenario will likely cause the data loss which we would like to avoid as much as possible. The second one is less critical and could be mitigated by implementing asynchronous integrations, but it is very hard to do so for every single integrations.

# Proposal
In this proposal, I suggest to implement OpenLineage Proxy that is lightweight, fast, and can be run as a sidecar along with the processing engine. This sidecar proxy will be run in the same network as the processing engine and the network delay will be minimal. Integrations may or may not implement asynchronous call, but anyway it is simple super fast call which brings very minimal extra latency. The sidecar proxy is also responsible for dealing with the backend outage. Even if the backend is not able to respond, the sidecar will keep the OpenLineage events locally and retry them. This prevents the data loss even in the case of the backend outage, and we are able to have a full picture of the lineage.

# Requirements
- Proxy must implement the HTTP POST API which receives an OpenLineage JSON event according to the [OpenLineage spec](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.yml).
- Proxy must be able to validate the OpenLineage events against the spec including standard facets.
    - Proxy must return 200 if the event is compliant to the spec regardless of the actual OpenLineage backend service availability.
    - Proxy must pass the event to configured *FailedEventHandler* if the event is non-compliant to the spec.
        - Proxy should return 400 for this.
- Proxy must buffer the OpenLineage events locally and send them to the backend when possible.
    - If the backend is available, the proxy should send the events as soon as possible
    - If the backend is unavailable for any reasons, proxy must keep events locally until it hits the buffer limit, and send them to the backend later when it’s available.
        - Buffer is limited by following parameters, whatever hits the limit first
            - T: hours to keep events to the buffer
            - B: bytes of the messages to keep events to the buffer
- Proxy must guarantee the order of the messages to be sent to the backend as the order it is received.

## Lightweight Proxy
This proposal will not mention how much lightweight it should be such as memory requirements or the latency, but the general idea is to be minimal enough to run as a sidecar of the processing engines.

# Proposed Design

## Language Options - Go
Among many programming language options, I propose using Go/Gin. Go is lightweight, verified in many productions, and has big community. Gin is a web framework for Go and has 64.5K stars in Github at the time of writing this. Go programs are compiled into single binary file, which is compact and no additional runtime is needed. There are many other languages with big community such as java, python, or node, but they require additional runtime environment in order to run the software, which is unlike lightweight proxy. Rust/Rocket is another option for lightweight, fast proxy implementation, however, considering the size of the community and the maturity of the project, I would like to propose Go/Gin.

## Design
![OpenLineage Proxy Sidecar](https://user-images.githubusercontent.com/316191/207163645-990a0eee-16c0-45aa-9993-175ac24c3645.svg)

### Router(api/v1/lineage)
This component is a Gin router that creates an API endpoint of `POST /api/v1/lineage`. This will get the actual OpenLineage events payload, validate it via EventValidator, and send it to the EventLogger for local buffering. This is responsible for returning proper response code based on the validation result.

### Event Validator
This validates that if the event payload is compliant to OpenLineage specification including standard facets. It will pass the invalid events to the FailedEventHandler, which will take care of  putting into the DLQ, logs, or either. In OpenLineage, we will provide a standard interface for it and users could implement their own handler. The implementaion of validator could be as a middleware of Gin router, or a separate component. I will leave the choice to the one who actually implement this.

### Event Logger
*EventLogger* buffers the OpenLineage events to the temporal local storage. This is responsible for writing events to the log file, and rotating the log based on the configuration. The events must be written to the file by preserving the order of the events that the proxy received. At this point, the event is already validated.

### Event Log Consumer
This log consumer reads the log written by the *EventLogger*, and send them to the configured backend. It checkpoints the offset of the logs so that it can restart in case of proxy app restart. It is also responsible for retry in case of the backend outage. Backend might not respond to the requests for many possible reasons and this will retry until it succeeds. This will not skip an event and move on to the next in order to avoid data loss.

### Metric Publisher
*MetricPublisher* gets the data from Event Logger and Event Log Consumer, how many messages are being written to the local storage and how many are being sent to the backend, and it keeps track of the consumer lag metrics. This uses the the *statsd* client so that the metrics can be sent to any *statsd* implementation.

### Event Log Storage
Event Log Storage is a local storage that stores OpenLineage events. It has a configured limit by age and size and drops old events when it hits the limit. Event Log Consumer should be able to read events from the checkpoint when starting. Here I compare two options, file based log tailing and using sqlite3 for local database.

#### Option 1. File Based Log Tailing
With the help of a logging library, we can write OpenLineage events to the log files. A decent logging library support log rotation which closes and recreate a log file when it hits the configured limit. We can also get a help from tail library which tails the log entries from the file that recognizes the rotation of the log files. The pro of this approach is that decent libraries are already available and the implementation is simple and easy.
![OL Proxy File Based Event Storage](https://user-images.githubusercontent.com/316191/207164322-0d64b1e3-e35b-4b7d-87d2-2f0a052df75f.svg)
As described from the above diagram, the logging and tailing libraries take care of abstraction of the log rotation, and the Event Logger and the Event Consumer implementation don’t need to care of them. They simply open a file and read from it.

However, There is a clear limit of this approach. By nature of the logging library, rotation happens when it hits the configured limit. When rotated, the new file is created and the consumer keeps reading from the new file. The problem happens with a backend outage scenario. If the log is rotated during the outage, the tailor is still waiting for the backend to be available but the file gets rotated. Besides, If the proxy app restarts and the next message we have to send to the backend is in the rotated file, we should be able to track and read from it. When checkpointing, in order to solve this problem, we have to keep track of in which file the checkpoint exists, and read from the rotated file. This eliminates the abstraction provided by the logger an tailor library, which makes the implementation complicated but loses the benefit of using library.

#### Option 2. Local database with Sqlite3 - proposed
![OL Proxy Sqlite Event Storage](https://user-images.githubusercontent.com/316191/207164633-77598b19-e80b-4ac5-a0fd-ba7b83665020.svg)
As a second option, in order to avoid the problems happen with option 1, we can implement custom event log rotation and checkpoint mechanism. We no longer leverage file based logging library, and using a sqlite3 database is a great alternative because it allows us explicit schema management and transactional operations.

With this approach, *Event Logger* is responsible for partition rotation as well as putting events to the event table. Partition rotation can be done with the smaller partition limit, like rotate hourly when the configured limit is given to 24 hours.

Following pseudo codes describe the logic of each component.

##### Event Logger:
```
channel = channel for lineage events

current_partition = `SELECT * FROM partitions WHERE current=TRUE`

IF current_partition DOES NOT EXIST:
    current_partition = CREATE PARTITION
    CREATE CHECKPOINT FOR current_partition WITH OFFSET 0

FOR lineage_event IN channel:
    event_size = len(lineage_event)
    cont = current_partition.size + event_size < PARTITION LIMIT
            && current_partition.created_at > NOW() - PARTITION_LIMIT_HOUR
    
    IF cont:
        IN TRANSACTION:
            next_partition = CREATE PARTITION
            current_partition.current = FALSE
            next_partition.current = TRUE
            INSERT INTO current_partition (event, continue) VALUES (lineage_event, FALSE)
            current_partition.size += event_size
            current_partition = next_partition
    ELSE:
        INSERT INTO current_partition (event, continue) VALUES (lineage_event, TRUE)
```

##### Event Consumer
```
partition, offset = `SELECT name AS partition, offset FROM checkpoint c INNER JOIN partitions p ON c.partition_id=p.rowid`
lineage_event, cont = read(partition, offset)
offset += 1

WHILE TRUE:
    IF cont == FALSE:
        partition = GET NEXT PARTITION
        offset = 0
    lineage_event, cont = read(partition, offset)
    SEND lineage_event TO BACKEND
    checkpoint(partition, offset)
    offset += 1

/**
 * Blocking read which wait until the event is available.
 * It might be implemented with retry and sleep.
 */
FUNC read(partition, offset):
    return `SELECT event, continue FROM partition WHERE rowid=offset`
```

##### Partition GC: runs periocally
```
/* Delete partitions that are already processed */
checkpointed_partition_id = `SELECT partition_id FROM checkpoint`
deletion_candidates = `SELECT * FROM partitions WHERE rowid < checkpointed_partition_id`
delete_partitions(deletion_candidates)

/* Delete partitions that are older than limit hour */
deletion_candidates = `SELECT * FROM partitions WHERE created_at < NOW() - LIMIT HOURS`
delete_partitions(deletion_candidates)

/* Delete oldest partitions until the total size is smaller then limit size */
deletion_candidates = list()
current_total_size = `SELECT SUM(size) FROM partitions`
partition_records = `SELECT * FROM partitions ORDER BY rowid ASC`
FOR partition_record IN partition_records:
    if current_total_size < LIMIT SIZE:
        BREAK
    deletion_candidates.append(partition_record)
    current_total_size -= partition_record.size
delete_partitions(deletion_candidates)

FUNC delete_partitions(deletion_candidates):
    FOR partition IN deletion_candidates:
        DROP TABLE partition IF EXISTS
        DELETE FROM partitions WHERE rowid=partition.rowid
```

# Future Milestone
We might add a Kafka transport for the consumer so that it can send to not only the lineage API backend but also the kafka topic. With this implemented, we are able to use this proxy as a replacement of the backend proxy. The major job of both of proxy is receiving and forwarding events, which is quite an overlap, and we could be able to replace the proxy backend with this, like just one proxy implementation that can be used as either a client proxy or server side reverse proxy. One missing piece of this design for that is ability to forward events to the multiple destination that the proxy backend can do. Having multiple destination will require the change of the design in order to deal with the outage of subset of backends which will complicate the design, and I will put this as a future work.

# Appendix
- [Gin](https://github.com/gin-gonic/gin) is a web framework written in Go
- [Lumberjack](https://github.com/natefinch/lumberjack) is a logging library that support rotation based on size and ages
- [Tail](https://github.com/hpcloud/tail) is a go library for log tailing that is designed to work with a log rotation
- [Sqlite](https://www.sqlite.org/) is a database engine that strives to provide local data storage for applications

# Side Note
As this proposes a client side proxy, which will make a confusion with existing Kafka proxy, I would like to propose rename the Kafka proxy to the reversed proxy, as it sits in front of the backend.

**Comment by mobuchowski** [comment]
>As this proposes a client side proxy, which will make a confusion with existing Kafka proxy, I would like to propose rename the Kafka proxy to the reversed proxy, as it sits in front of the backend.

Shouldn't this replace the existing Java proxy? Your design seems to be more robust, and I don't understand why wouldn't it function well in this role too - just that the `EventLogConsumer` should support Kafka and other `Transports`

**Comment by fm100** [comment]
> > As this proposes a client side proxy, which will make a confusion with existing Kafka proxy, I would like to propose rename the Kafka proxy to the reversed proxy, as it sits in front of the backend.
> 
> Shouldn't this replace the existing Java proxy? Your design seems to be more robust, and I don't understand why wouldn't it function well in this role too - just that the `EventLogConsumer` should support Kafka and other `Transports`

I don't see the reason not to, but it might be a too big task for the first step. We may add a `Transport` interface and implement the first thing to send it to configured backend, and add a Kafka transport. Once we have that, then we can deprecate the Kafka proxy we have now.

**Comment by pawel-big-lebowski** [comment]
When looking at the problem statements, `not responsive backend` and `long latency in API call` can be solved at the server side by a message broker like Hermes:
 * https://hermes.allegro.tech
 * https://hermes-pubsub.readthedocs.io/en/latest/

which provides a REST endpoint that writes messages to Kafka and publishes to other REST consumers.
This adds no extra effort nor issues on client side which are pretty hard to debug. 

Network outage is the only problem which has to be solved on client side. 
But, doing the client side solution will introduce new problems: 
 * what to do with buffered events when job is finished (Spark, Flink, Airflow)?
 * what should be the buffer capacity no to exceed user quota? 

In existing integrations we avoided storing any state on client side because stateful architecture can make things hard.

**Comment by fm100** [comment]
> When looking at the problem statements, `not responsive backend` and `long latency in API call` can be solved at the server side by a message broker like Hermes:
> 
>     * https://hermes.allegro.tech
> 
>     * https://hermes-pubsub.readthedocs.io/en/latest/
> 
> 
> which provides a REST endpoint that writes messages to Kafka and publishes to other REST consumers. This adds no extra effort nor issues on client side which are pretty hard to debug.
> 
> Network outage is the only problem which has to be solved on client side. But, doing the client side solution will introduce new problems:
> 
>     * what to do with buffered events when job is finished (Spark, Flink, Airflow)?
> 
>     * what should be the buffer capacity no to exceed user quota?
> 
> 
> In existing integrations we avoided storing any state on client side because stateful architecture can make things hard.

Firstly, this is to give users an option. You're right that having another backend proxy playing in the middle could deal with the OpenLineage backend outage. However, it often requires cost setting them up, and this is to give an option as a lightweight solution. This is designed to run as a sidecar with minimal memory. Besides, for the backend such as marquez, the order of the messages is critial for processing, and not sure the proposed broker service guarantees that. It uses Kafka but we don't seem to have a control over the number of partitions and their partition key. Secondly, long latency is not only caused by the backend app processing time, but we also need to consider network delay caused by the physical distance. This may not be a critical concern but want to call out.

I don't think it introduces new problems. Integration such as Spark, Flink, and Airflow will work as is. They will send the events to the proxy by simply changing the `OPENLINEAGE_URL`. Integration will send `START` and `COMPLETE` event as is, so there is nothing to do with events when job is finished. Proxy just receives and sends them to the backend.

I don't get what user quota you mean by. Con you please elaborate it? The limit is implemented in backend, and the integration will get `429` when it exceeds the limit. Handling this from integration is difficult, but the proxy can keep them. 

This does not make integrations store states and requires no change. From the integrations' perspective, the proxy is the configured backend that happens to be in the same network.

**Comment by pawel-big-lebowski** [comment]
@fm100 I think I wrongly assumed proxy will be colocated per processing job. You're right, it is a good option that some users may want to have. 
 
Kafka guarantees ordering within a partition and a server proxy that uses Kafka as a backend, events can be assigned to partitions based on namespaces for example (message producer is able to set message key and partition key is evaluated from message key). Guarantee on ordering per namespace should be enough. 

Do you think this proxy may be helpful for heavy backend upgrades like Marquez database migrations that cause backend downtime?

**Comment by fm100** [comment]
@pawel-big-lebowski I think it depends. If every client sends the OL events through the proxy, then it could keep the data while the backend is down for any reason, and yeah it could help. However, usually the ownership between clients and the backend is separated, the data engineers setup pipelines and configure openlineage integrations, and the data platform team owns backend like marquez. When the organization is small enough, they are able to communicate and let the clients use the proxy and take some downtime for backend as needed, but when the org size gets bigger, it gets harder to do so. In that case the owner of the OpenLineage backend just should guarantee the uptime of the service. Service side upgrade is usually being done in a rolling upgrade manner or blue-green style and they both require no downtime. What we need to make sure is that the marquez database migration is backward compatible, so that the application does not break with the new database schema while the app is running with the old code.

**Comment by mobuchowski** [comment]
```
I don't see the reason not to, but it might be a too big task for the first step. We may add a Transport interface and implement the first thing to send it to configured backend, and add a Kafka transport as a follow up. Once we have that, then we can deprecate the Kafka proxy we have now.
```

I agree, but would like if this proposal included that step, even as a suggestion. The feature set is IMO too similar to justify keeping both solutions supported and I like a lot of design choices here.

**Comment by fm100** [comment]
> 

Let me add that as a possible future milestone. At the moment, the proxy backend is able to stream events to the multiple destinations like multiple kafka topics, but this does not. Having multiple destination configured would require dealing with the outage of subset of backends, which will complicate the design.
