### ISSUE TITLE
[PROPOSAL] Add custom environment variables to the RunEvent

### ISSUE THREAD

**Issue by Anirudh181001** [OpenLineage/OpenLineage#1419]
Hi,
I would like to capture some custom environment variables and send it along with the column lineage to the server. This feature will be of great use as there is a potential use case to capture and persist some environment-specific metadata from spark clusters.
Wondering if this feature can be supported, or is on the roadmap potentially? Thanks a lot!
cc: @pawel-big-lebowski

**Comment by Anirudh181001** [comment]
@pawel-big-lebowski Hi, is there a potential roadmap for this issue? Thanks!

**Comment by pawel-big-lebowski** [comment]
Yeah, this seems to be pretty cool generic feature. 
It's great we have an issue for that.
I don't think it's on a roadmap soon, but I would be happy to help other contributors to tackle with this.

**Comment by Anirudh181001** [comment]
Hi @pawel-big-lebowski I have extended the EnvironmentFacet class, to have a CustomEnvironmentFacetBuilder clas to support this use case for my own use. However, I would like to generalize it, to contribute back to the open source. Just bouncing off an idea to see whether this might be appealing. I was thinking if the following flow might work for a more general use case.
1. Set an env variable "CUSTOM_VARS"='["VAR1","VAR2","VAR3","VAR4"]'
2. If CUSTOM_VARS is present in env, then CustomEnvironmentFacetBuilder will collect VAR1, VAR2, VAR3, and VAR4 env variables, and pass it onto the start event.
Thanks!
