### ISSUE TITLE
`pip install openlineage-dbt` not working

### ISSUE THREAD

**Issue by fm100** [OpenLineage/OpenLineage#142]
```
(py39) ➜  ~ python --version
Python 3.9.6
(py39) ➜  ~ pip install openlineage-dbt
ERROR: Could not find a version that satisfies the requirement openlineage-dbt (from versions: none)
ERROR: No matching distribution found for openlineage-dbt
(py39) ➜  ~
```

Tried as instructed from dbt integration README, but _pip install_ command didn't work. Tested on python 3.6, 3.7, 3.8 and 3.9 and nothing worked.

**Comment by wslulciuc** [comment]
We haven't yet released  the `openlineage-dbt` lib, but we're working on it :)

**Comment by mobuchowski** [comment]
@fm100 rc version is now released: https://pypi.org/project/openlineage-dbt/

**Comment by simran-suri** [comment]
I'm facing issue while doing pip install openlineage-dbt

**Comment by JDarDagran** [comment]
@simran-suri  could you give some more context, e.g. logs from failed installation?

**Comment by simran-suri** [comment]
Collecting openlineage-sql
  Using cached openlineage_sql-1.6.2.tar.gz (32 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by JDarDagran** [comment]
Are you running `pip install openlineage-dbt` or `pip install -e .` to install from source?

**Comment by simran-suri** [comment]
pip install openlineage-dbt

**Comment by simran-suri** [comment]
pip install openlineage-dbt
Collecting openlineage-dbt
  Using cached openlineage_dbt-1.6.2-py3-none-any.whl.metadata (2.7 kB)
Collecting tqdm>=4.62.0 (from openlineage-dbt)
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Collecting openlineage-integration-common==1.6.2 (from openlineage-integration-common[dbt]==1.6.2->openlineage-dbt)
  Using cached openlineage_integration_common-1.6.2-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: attrs>=19.3.0 in c:\users\ssu460\appdata\local\programs\python\python310\lib\site-packages (from openlineage-integration-common==1.6.2->openlineage-integration-common[dbt]==1.6.2->openlineage-dbt) (23.1.0)
Collecting openlineage-python==1.6.2 (from openlineage-integration-common==1.6.2->openlineage-integration-common[dbt]==1.6.2->openlineage-dbt)
  Using cached openlineage_python-1.6.2-py3-none-any.whl.metadata (5.1 kB)
Collecting openlineage-sql==1.6.2 (from openlineage-integration-common==1.6.2->openlineage-integration-common[dbt]==1.6.2->openlineage-dbt)
  Using cached openlineage_sql-1.6.2.tar.gz (32 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by simran-suri** [comment]
Facing same issue while doing pip install openlineage-dbt and pip install openlineage-sql

**Comment by JDarDagran** [comment]
I can see you're trying to install it on Windows machine. However, there's no `openlineage-sql` binary built for Windows. You could try to install Rust toolchain and build the package on your own.
