### ISSUE TITLE
[ci, integration/spark] spark related ci failures

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#1458]
# Problem
Observed circle/ci integration-test-integraiton-spark-* to fail:
![Screen Shot 2023-01-03 at 9 32 12 PM](https://user-images.githubusercontent.com/32691630/210479890-c4fdaba9-2871-4def-b6cb-defed50e6a4c.png)
And the reason for failure is same across all spark-related tests:
![Screen Shot 2023-01-03 at 9 32 30 PM](https://user-images.githubusercontent.com/32691630/210479914-de848093-e0a7-4bd8-86a2-d8bd55f947aa.png)

# Solution
Not sure what the solution is, but ideally, all the spark integration tests should pass without any errors.

**Comment by mobuchowski** [comment]
@howardyoo what PR is that?

**Comment by howardyoo** [comment]
> @howardyoo what PR is that?
the PR was :
https://github.com/OpenLineage/OpenLineage/pull/1402

**Comment by pawel-big-lebowski** [comment]
@howardyoo I saw circle-ci problem and I think we solved that yesterday in [#1485](https://github.com/OpenLineage/OpenLineage/pull/1485). 

Could you verify if this issue is still valid?

**Comment by howardyoo** [comment]
> @howardyoo I saw circle-ci problem and I think we solved that yesterday in [#1485](https://github.com/OpenLineage/OpenLineage/pull/1485).
> 
> Could you verify if this issue is still valid?

Hi @pawel-big-lebowski , I believe the issue is now resolved! closing it..!
