### ISSUE TITLE
Spark configs with semicolons (;) in their value get split into an array

### ISSUE THREAD

**Issue by Varunvaruns9** [OpenLineage/OpenLineage#1506]
Semicolon (;) is being used as the delimiter for array configs like `disabled.facets` but this also converts string configs which require a semicolon into arrays. For example, EventHub authentication requires a SAS key which has a semicolon in it but it doesn't need to be converted into an array.

This conversion is being done in the following lines
https://github.com/OpenLineage/OpenLineage/blob/92adbc877f0f4008928a420a1b8a93f394530d04/integration/spark/app/src/main/java/io/openlineage/spark/agent/ArgumentParser.java#L150-L154

**Comment by Varunvaruns9** [comment]
Based on @tnazarew's suggestion, I will add an additional requirement that array configs must start with `[` and end with `]`.

**Comment by pawel-big-lebowski** [comment]
Hi @Varunvaruns9, it's great PR and we're super excited to welcome you among the commiters 🚀 👍 💯 
Please take a look at my comment and concern within the PR code.

**Comment by Varunvaruns9** [comment]
Thank you @pawel-big-lebowski! Looking forward to contributing more.
