### ISSUE TITLE
JFrog Credentials Requested on Apache Spark Integration Build

### ISSUE THREAD

**Issue by dmc1899** [OpenLineage/OpenLineage#1513]
The gradle build process fails when following the build instructions on the [Apache Spark integration README](https://github.com/OpenLineage/OpenLineage/tree/main/integration/spark).  The error message returned by Gradle is as follows:
`
 > Could not GET 'https://astronomer.jfrog.io/artifactory/maven-public-libs-snapshot/io/openlineage/openlineage-java/0.20.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized`

It appears that the remote repository containing the openlineage dependency requires an account.

Can you please advise on this issue please?

**Comment by mobuchowski** [comment]
@dmc1899 you need to run `./gradlew publishToMavenLocal` in `clients/java` directory first. 

https://github.com/OpenLineage/OpenLineage/tree/main/integration/spark#preparation

**Comment by dmc1899** [comment]
Thankyou, @mobuchowski .

Issue resolved.

Regards,
Darragh
