### ISSUE TITLE
Proposal for a ProxyBackend

### ISSUE THREAD

**Issue by mandy-chessell** [OpenLineage/OpenLineage#152]
This issue is to track the discussion and development of a proxy backend.  The diagram below shows the basic idea.

![image](https://user-images.githubusercontent.com/12354195/128734055-2a08372e-8d1b-426e-9c25-c06aeb551e36.png)

**Comment by julienledem** [comment]
This initial design looks good to me. I'm looking forward to see it.

**Comment by wslulciuc** [comment]
Fixed #400
