### ISSUE TITLE
Spark Warning: RddExecutionContext Unable to access job conf from RDD

### ISSUE THREAD

**Issue by perttus** [OpenLineage/OpenLineage#1521]
PySpark functions `describe` and `summary` give this warning when reading Parquet files from Dell ECS S3 bucket and emitting metadata to Marquez.

Using Spark 3.3 and `io.openlineage:openlineage-spark:0.19.2` and `org.apache.hadoop:hadoop-aws:3.3.`
Marquez version 0.29.0.

```python
sdf = spark.read.parquet('s3a://bucket/parquet-files/').persist()
sdf.describe()
sdf.summary()
```

> 23/01/23 09:28:58 WARN RddExecutionContext: Unable to access job conf from RDD
> java.lang.NoSuchFieldException: Field is not instance of HadoopMapRedWriteConfigUtil
> 	at io.openlineage.spark.agent.lifecycle.RddExecutionContext.lambda$setActiveJob$0(RddExecutionContext.java:117)
> 	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
> 	at io.openlineage.spark.agent.lifecycle.RddExecutionContext.setActiveJob(RddExecutionContext.java:115)
> 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
> 	at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$onJobStart$9(OpenLineageSparkListener.java:148)
> 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
> 	at io.openlineage.spark.agent.OpenLineageSparkListener.onJobStart(OpenLineageSparkListener.java:145)
> 	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
> 	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
> 	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
> 	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
> 	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
> 	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
> 	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
> 	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
> 	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
> 	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
> 	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
> 	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
> 	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)

**Comment by mobuchowski** [comment]
@perttus I think it can also be [`HadoopMapReduceWriteConfigUtil`](https://github.com/apache/spark/blob/cc1674d66ef34f540aa7bd5c7e465605e264e040/core/src/main/scala/org/apache/spark/internal/io/SparkHadoopWriter.scala#L309). I have a branch where I add check for this too, and it should fix it, unless something like S3 also adds instance of this class.

**Comment by mobuchowski** [comment]
This was also reported on Slack recently.

**Comment by sanandarao** [comment]
@mobuchowski I wanted to follow-up with you to see if this would be included in upcoming release. Our team is waiting for this change to further our exploration with Spark integration.

**Comment by mobuchowski** [comment]
@sanandarao yes! I forgot to close the issue. It was fixed here: https://github.com/OpenLineage/OpenLineage/pull/1557
