### ISSUE TITLE
[Airflow] macros.OpenLineagePlugin.lineage_run_id returning empty string

### ISSUE THREAD

**Issue by perttus** [OpenLineage/OpenLineage#1530]
Are the macros broken or am I doing something wrong here? Nothing is seen on the logs, just empty strings.

Using apache/airflow:2.3.3-python3.8 and openlineage 0.19.2. Also tried Airflow 2.4.3.

Is there any other way to get the run_id? I think the parent_id is trivial when using `SparkSubmitOperator`
`'spark.openlineage.parentJobName': "{{ dag.dag_id }}." + "{{ task.task_id }}"`

```python
import airflow
from datetime import timedelta
from airflow import DAG
from airflow.operators.python_operator import PythonOperator
from airflow.operators.bash_operator import BashOperator
from airflow.utils.dates import days_ago

from pprint import pprint


default_args = {
    'owner': 'airflow',
    'retry_delay': timedelta(minutes=5),
}

dag = DAG(
    dag_id="test_dag",
    default_args=default_args,
    schedule_interval=None,
    dagrun_timeout=timedelta(minutes=60),
    description='use case of openlineage macros in airflow',
    start_date=days_ago(1)
)

t1 = PythonOperator(
    dag=dag,
    task_id='py_op',
    python_callable=pprint,
    op_args=['{{ macros.OpenLineagePlugin.lineage_run_id(run_id, task) }}']
)

t2 = BashOperator(
    task_id='bash_op',
    bash_command="echo " + '{{ macros.OpenLineagePlugin.lineage_parent_id(run_id, task) }}',
    dag=dag
)

t1 >> t2
```

**Comment by mobuchowski** [comment]
`Marquez 0.19.2` you mean `openlineage-airflow`?

**Comment by perttus** [comment]
> `Marquez 0.19.2` you mean `openlineage-airflow`?

Oh, yes openlineage-airflow 0.19.2 and Marquez 0.29.0. 

I also tried to return `lineage_parent_id` and `lineage_run_id` with `user_defined_macros` as in 
https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/tests/integration/tests/airflow/dags/dbt_snowflake.py
and as a result `lineage_run_id` was empty string but `lineage_parent_id` returned `'None/<dag_id>.<task_id>.None'`

I noticed that `JobIdMapping.set()` function is not called from anywhere so I wonder if that should be initialised first?

**Comment by perttus** [comment]
I suppose it should possible to reproduce the ID's from Airflow using the functions in https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/openlineage/airflow/adapter.py

I tried that but for some reason only the `build_dag_run_id` is the same as in Marquez.

```python
def get_ids(**ctx):
    print('build_task_instance_run_id: '+ build_task_instance_run_id(ctx['task'].task_id, ctx['task_instance'].execution_date, ctx['task_instance'].try_number))
    print('build_dag_run_id: ' + build_dag_run_id(ctx['dag'].dag_id, ctx['dag_run'].run_id))

t1 = PythonOperator(
    dag=dag,
    task_id='py_op',
    python_callable=get_ids,
)
```

**Comment by perttus** [comment]
> I suppose it should possible to reproduce the ID's from Airflow using the functions in https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/openlineage/airflow/adapter.py
> 
> I tried that but for some reason only the `build_dag_run_id` is the same as in Marquez.
> 
> ```python
> def get_ids(**ctx):
>     print('build_task_instance_run_id: '+ build_task_instance_run_id(ctx['task'].task_id, ctx['task_instance'].execution_date, ctx['task_instance'].try_number))
>     print('build_dag_run_id: ' + build_dag_run_id(ctx['dag'].dag_id, ctx['dag_run'].run_id))
> 
> t1 = PythonOperator(
>     dag=dag,
>     task_id='py_op',
>     python_callable=get_ids,
> )
> ```

I just realized that for aiflow tasks the ID is stored as `taskUuid` in airflow facet instead of the actual run id which is just randomly generated `run_id = str(uuid.uuid4())`

But I'm still wondering how to get that macro working...

**Comment by mobuchowski** [comment]
>I just realized that for aiflow tasks the ID is stored as taskUuid in airflow facet instead of the actual run id which is just randomly generated run_id = str(uuid.uuid4())

@perttus I think we need to change for AsyncOperators though

**Comment by perttus** [comment]
@mobuchowski I found a workaround for the Spark `parentRunId` while the OL macro is not working. I noticed that execution_date default separator is **T** which is why `isoformat(' ')`is required to get a matching ID with the Task Run ID.

This also solves the issue in #1600

```python
'spark.openlineage.parentRunId': f"{{{{ macros.uuid.uuid3(macros.uuid.NAMESPACE_URL, '{_DAG_DEFAULT_NAMESPACE}.' + task.task_id + '.' + execution_date.isoformat(' ') + '.' + task_instance.try_number|string) }}}}"
```

**Comment by JDarDagran** [comment]
@perttus it's actually a great discovery from yours that now Airflow events get deterministic run IDs and you made use of it. We should update macro to use above. Thank you for this!

As a side note: docs mistakenly describe usage of the `lineage_parent_id` macro. It was supposed to be used only for Airflow 1.10.x versions which got removed from OpenLineage compatibility. I'll post a PR with fixes.
