### ISSUE TITLE
Airflow Operator: non SQL code should be returned in the SourceCodeJobFacet instead of the SQLJobFacet

### ISSUE THREAD

**Issue by Esaych** [OpenLineage/OpenLineage#1553]
The airflow operator is outputting python code that produces SQL into a SQLJobFacet. As a web developer, I'd expected the SQL facet to be formatted into SQL code, but the formatting engine is confused because in reality it is Python code.

The issue can be resolved if instead of using the ["sql" facet](https://github.com/OpenLineage/OpenLineage/blob/main/spec/facets/SQLJobFacet.json), we use the ["sourceCode" facet](https://github.com/OpenLineage/OpenLineage/blob/main/spec/facets/SourceCodeJobFacet.json).

Here is the facet's output currently, the "sql" facet outputting python code.
![image](https://user-images.githubusercontent.com/1761996/216424612-45dc54fc-571b-47c4-ae36-5e850966e9d9.png)

**Comment by mobuchowski** [comment]
@Esaych can you show the whole event? 
As far as I can see PythonExtractor does exactly what you want it to do: https://github.com/OpenLineage/OpenLineage/blob/3d0fee9002a8d7a85f47c8a6e57446174f433e34/integration/airflow/openlineage/airflow/extractors/python_extractor.py#L31

**Comment by JDarDagran** [comment]
@Esaych, looking at the code provided in `query` you're using `aql.run_raw_sql` decorator which is a part of `astro-sdk`. It's probable that implementation of `get_openlineage_facets_on_start/complete` method puts Python code into wrong facet.

**Comment by JDarDagran** [comment]
Hello @Esaych, I was wondering if the issues you mentioned earlier are still persisting. Have you had a chance to try out the suggestions I provided?
