### ISSUE TITLE
automation could ease process of adding PRs to changelog 

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/OpenLineage#1579]
Tools exist that could be used to automate the process of updating the changelog with information about PRs when they are opened. Adding such a tool to the project would ease the process of contributing. Contributors would no longer need to add commits to their branches just to update the changelog. 

[changelog-ci](https://github.com/saadmk11/changelog-ci), for example, can be configured to update the changelog on a per-commit or per-PR basis. It creates a PR for the next release and adds a commit with an update as a PR is opened (or a commit is made, if this is preferred). Our current practice is to add more details than the PR title to the changelog. We could continue to do this.

**Comment by JDarDagran** [comment]
I would love to see this!
