### ISSUE TITLE
Airflow emits Spark jobs twice to Marquez

### ISSUE THREAD

**Issue by perttus** [OpenLineage/OpenLineage#1600]
I have noticed that Spark jobs are emitted as duplicate job events to Marquez backend when using Airflow.

Using Airflow 2.3.4, Spark 3.3.1, openlineage 0.20.4, marquez 0.30.0.
I have noticed the same behaviour with also older openlineage 0.19.2 and marquez 0.29.0

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/18646634/217475471-dddc69cf-d664-41ce-93fa-d078d1e75519.png">

```python
spark_dag = DAG(
    dag_id = "spark_air_dag2",
    default_args=default_args,
    schedule_interval=None,	
    dagrun_timeout=timedelta(minutes=60),
    description='use case of sparkoperator in airflow',
    start_date = days_ago(1)
)

packages = 'io.openlineage:openlineage-spark:0.20.4'

def t1():
    return SparkSubmitOperator(
        application = "/opt/airflow/dags/spark1.py",
        conn_id= 'spark_local', 
        task_id='spark_submit_task', 
        dag=spark_dag,
        packages=packages,
        conf = {
            'spark.extraListeners': 'io.openlineage.spark.agent.OpenLineageSparkListener',
            'spark.openlineage.host': f"{os.getenv('OPENLINEAGE_URL')}",
        }
    )

t1()
```

spark1.py
```python
from pyspark.sql import SparkSession

spark = SparkSession \
    .builder \
    .appName("spark1") \
    .getOrCreate() 

spark.createDataFrame([
    {'col_1': 1, 'col_2': 2},
    {'col_1': 3, 'col_2': 4}
]).coalesce(1).write.mode('overwrite').parquet('dataset_a')
```

Marquez Log:
> INFO  [2023-02-08 07:41:24,165] marquez.db.OpenLineageDao: Created new parent job record JobRow(uuid=7a77f22a-16ba-48ff-9aaf-78f2021e64e5, type=BATCH, createdAt=2023-02-08T07:38:38.005059Z, updatedAt=2023-02-08T07:41:24.165080Z, namespaceName=default, name=spark_air_dag2, simpleName=spark_air_dag2, parentJobName=null, description=Optional.empty, currentVersionUuid=Optional.empty, jobContextUuid=Optional[9981732b-1574-4bbc-9bca-207a510a9df7], location=null, inputs=[], symlinkTargetId=null)
INFO  [2023-02-08 07:41:24,167] marquez.db.OpenLineageDao: Created new parent run record RunRow(uuid=bd6eaa48-f3c6-3d38-ae30-1a58de7d035a, createdAt=2023-02-08T07:41:24.113909Z, updatedAt=2023-02-08T07:41:24.113909Z, jobUuid=7a77f22a-16ba-48ff-9aaf-78f2021e64e5, jobVersionUuid=Optional.empty, parentRunUuid=Optional.empty, runArgsUuid=351a41a4-5b44-4828-9ebc-87a744a06bd5, nominalStartTime=Optional[2023-02-08T07:41:23.063784Z], nominalEndTime=Optional[2023-02-08T07:41:23.063784Z], currentRunState=Optional[RUNNING], startedAt=Optional.empty, startRunStateUuid=Optional.empty, endedAt=Optional.empty, endRunStateUuid=Optional.empty)
INFO  [2023-02-08 07:41:24,178] marquez.logging.LoggingMdcFilter: status: 201
172.19.0.1 - - [08/Feb/2023:07:41:24 +0000] "POST /api/v1/lineage HTTP/1.1" 201 0 "-" "python-requests/2.28.1" 21
INFO  [2023-02-08 07:41:29,845] marquez.logging.LoggingMdcFilter: status: 201
172.19.0.1 - - [08/Feb/2023:07:41:29 +0000] "POST /api/v1/lineage HTTP/1.1" 201 0 "-" "Apache-HttpClient/4.5.14 (Java/11.0.16)" 25
INFO  [2023-02-08 07:41:29,885] marquez.db.RunFacetsDao: Facet 'spark.logicalPlan' has already been linked to run 'de505286-f63d-4f72-8adb-b562ae146c96', skipping...
INFO  [2023-02-08 07:41:29,902] marquez.logging.LoggingMdcFilter: status: 201
172.19.0.1 - - [08/Feb/2023:07:41:29 +0000] "POST /api/v1/lineage HTTP/1.1" 201 0 "-" "Apache-HttpClient/4.5.14 (Java/11.0.16)" 26
INFO  [2023-02-08 07:41:57,897] marquez.db.RunFacetsDao: Facet 'spark.logicalPlan' has already been linked to run 'de505286-f63d-4f72-8adb-b562ae146c96', skipping...
INFO  [2023-02-08 07:41:57,919] marquez.logging.LoggingMdcFilter: status: 201
172.19.0.1 - - [08/Feb/2023:07:41:57 +0000] "POST /api/v1/lineage HTTP/1.1" 201 0 "-" "Apache-HttpClient/4.5.14 (Java/11.0.16)" 30
INFO  [2023-02-08 07:41:57,944] marquez.db.RunFacetsDao: Facet 'spark.logicalPlan' has already been linked to run 'de505286-f63d-4f72-8adb-b562ae146c96', skipping...
INFO  [2023-02-08 07:41:57,963] marquez.logging.LoggingMdcFilter: status: 201
172.19.0.1 - - [08/Feb/2023:07:41:57 +0000] "POST /api/v1/lineage HTTP/1.1" 201 0 "-" "Apache-HttpClient/4.5.14 (Java/11.0.16)" 31
INFO  [2023-02-08 07:41:58,197] marquez.logging.LoggingMdcFilter: status: 201
172.19.0.1 - - [08/Feb/2023:07:41:58 +0000] "POST /api/v1/lineage HTTP/1.1" 201 0 "-" "python-requests/2.28.1" 30

**Comment by mobuchowski** [comment]
@perttus that's by design. Those events capture different things - Spark one captures actual datasets invocation, while Airflow captures finer details about scheduling that job.

**Comment by perttus** [comment]
@mobuchowski ok, thanks for the clarification! However, if I add the dag task parent details to the Spark `conf` I see 2 separate tasks in Marquez and it fails to show them.

```python
def build_task_instance_run_id():
    return str(
        uuid.uuid3(
            uuid.NAMESPACE_URL,
            f"{_DAG_DEFAULT_NAMESPACE}.{{{{ execution_date }}}}.{{{{ task_instance.try_number }}}}"
        )
    )

        conf = {
            'spark.extraListeners': 'io.openlineage.spark.agent.OpenLineageSparkListener',
            'spark.openlineage.host': f"{os.getenv('OPENLINEAGE_URL')}",
            'spark.openlineage.parentJobName': "{{ dag.dag_id }}.{{ task.task_id }}",
            'spark.openlineage.parentRunId': build_task_instance_run_id()
        }
```
http://localhost:3000/api/v1/lineage/?nodeId=job:default:spark_air_dag2.spark_submit_task gives 500 error
http://localhost:3000/api/v1/namespaces/default/jobs/ show `spark_air_dag2.spark_submit_task` twice with same ID

It works normally though if I set the DAG as parent but then I can not deduct which Airflow task created with Spark job.

```python
def build_dag_run_id():
    return str(
        uuid.uuid3(uuid.NAMESPACE_URL, f"{_DAG_DEFAULT_NAMESPACE}.{{{{ dag.dag_id }}}}.{{{{ run_id }}}}")
    )

        conf = {
            'spark.extraListeners': 'io.openlineage.spark.agent.OpenLineageSparkListener',
            'spark.openlineage.host': f"{os.getenv('OPENLINEAGE_URL')}",
            'spark.openlineage.parentJobName': "{{ dag.dag_id }}",
            'spark.openlineage.parentRunId': build_dag_run_id()
        }
```

**Comment by mobuchowski** [comment]
Oh, sorry, I misunderstood the problem. Yeah, that looks like bug.

**Comment by mobuchowski** [comment]
I don't think it has anything to do with Airflow though, those duplicated events are emitted by Spark integration only.

**Comment by perttus** [comment]
`parentRunId` did not match with the task run ID which caused the duplicate task jobs. Spark conf workaround:

```python
'spark.openlineage.parentJobName': "{{ dag.dag_id }}.{{ task.task_id }}",
'spark.openlineage.parentRunId': f"{{{{ macros.uuid.uuid3(macros.uuid.NAMESPACE_URL, '{_DAG_DEFAULT_NAMESPACE}.' + task.task_id + '.' + execution_date.isoformat(' ') + '.' + task_instance.try_number|string) }}}}"
```
