### ISSUE TITLE
Kafka transport needs more DEBUG-level logging

### ISSUE THREAD

**Issue by rossturk** [OpenLineage/OpenLineage#1625]
I believe that the OpenLineage Kafka transport should offer similar logging to the HTTP transport, as much as possible.

Right now, it does not provide any debugging messages. The result is that it is very hard to tell whether events are being emitted from openlineage-airflow - even with logging set to DEBUG, the task logs do not show any attempt to send a message.

The difference in DEBUG logging output can be seen by using the Python client to send messages to a local Kafka service, and then send messages to a local Marquez instance. The HTTP transport provides the payload of each message, while the Kafka transport shows a single message.

Ultimately this debugging information should be visible somewhere inside Airflow, when used as part of `openlineage-airflow`.

**Comment by mobuchowski** [comment]
@rossturk I feel payload being logged on `DEBUG` should be a part of core client, while Transports should deal with logging transport-specific messages. This way any other transport will have this correctly implemented as well.
