### ISSUE TITLE
Airflow - Athena extract wrong database

### ISSUE THREAD

**Issue by rinzool** [OpenLineage/OpenLineage#1627]
## Issue 
The [Athena extractor](https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/openlineage/airflow/extractors/athena_extractor.py#L28) define input/output tables using `operator.database` in every cases. However we can have situation like that
```sql
SELECT * FROM my_db.my_table
```

## Possible solution
Therefore it should be more precise to extract database from table metadata using `table.schema`, and if there are no schema, we can use `operator.database` by default

**Comment by rinzool** [comment]
I will open a PR today with this solution (that I already use with a fork in my company)

**Comment by mobuchowski** [comment]
Thanks @rinzool!

**Comment by rinzool** [comment]
Here is the PR: https://github.com/OpenLineage/OpenLineage/pull/1631 (currently in draft, I need to be sure that integration tests still works with my new test)
