### ISSUE TITLE
Airflow lineage backend high/spiky CPU usage

### ISSUE THREAD

**Issue by perttus** [OpenLineage/OpenLineage#1637]
When OpenLineage backend is enabled Airflow Scheduler CPU usage is capped around every 10 seconds even though no DAGs are running or scheduled. Is there some parameter that could be tweaked in order to minimise the CPU usage? It's especially problematic when Airflow is deployed to Kubernetes so we get lots of alerts:
https://runbooks.prometheus-operator.dev/runbooks/kubernetes/cputhrottlinghigh/

I collected the data from Docker with following command so the X axis interval is around 2 seconds:
```bash
while true; do docker stats docker-spark-airflow-airflow-scheduler-1 --no-stream | grep docker-spark-airflow-airflow-scheduler-1 >> stats.txt; done
``` 

![image](https://user-images.githubusercontent.com/18646634/219347732-9904103d-46cc-46a3-b092-ed67d23b8f57.png)

**Comment by mobuchowski** [comment]
@perttus what OL and Airflow version are you on?

**Comment by perttus** [comment]
@mobuchowski using OL 0.20.6 and Airflow 2.4.3 (Python 3.8)

Now I tried running Airflow locally on my mac without Docker and the CPU usage is close to zero all the time. Locally I'm using Python 3.10 so that could explain the difference. I will try again with Python 3.8 locally and/or Python 3.10 on Docker.

**Comment by mobuchowski** [comment]
If you managed to reproduce high CPU usage in some scenario, could you try the same again with `OPENLINEAGE_DISABLED`?

**Comment by perttus** [comment]
@mobuchowski I failed to reproduce the problem. Disabling OL altogether doesn't affect the CPU usage. However, increasing [min_file_process_interval](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#min-file-process-interval) did the trick. No more alerts from Kubernetes.
