### ISSUE TITLE
Incorrect output identification of LogicalRelationDatasetBuilder

### ISSUE THREAD

**Issue by nataliezeller1** [OpenLineage/OpenLineage#1653]
When reading a table (in my case, glue table) and performing some action on the dataframe, the input dataset is also identified as an output by LogicalRelationDatasetBuilder.

For example:
```
spark.sql("select * from my_db.my_table")
      .collect().map(_.getAs[String]("col1")).toSet
```
Can we remove LogicalRelationDatasetBuilder from the output builder list? In which use case should this builder identify output?

**Comment by pawel-big-lebowski** [comment]
Hi @nataliezeller1, there is one tricky thing in `LogicalRelationDatasetBuilder`. It is used to fetch both inputs and outputs and it is instantiated twice `DatasetBuilderFactory`. The tricky thing is that it is instantiated differently for inputs and outputs based on the last constructor param `boolean searchDependencies`. For outputs it's `false`, for inputs it is set to `true`. In case of `true` whole Spark logical plan is searched for `LogicalRelation`s as inputs leafs within the tree. The output is a root of a tree, so there is no need to search for it. 

Did you define your custom `DatasetBuilderFactory`? If so, could you please check the way `LogicalRelationDatasetBuilder` is instantiated?

**Comment by nataliezeller1** [comment]
Hi @pawel-big-lebowski 
I didn't customize DatasetBuilderFactory, so searchDependencies is false for outputs. Still, in this particular use case, I'm getting the same table as input and output....

**Comment by pawel-big-lebowski** [comment]
@nataliezeller1 Thanks for the info.
