### ISSUE TITLE
sql: Support COMMENT Snowflake query

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1676]
Add SQL parser support for the COMMENT command in Snowflake.

Sample queries:
`COMMENT IF EXISTS ON TABLE MODEL_CRM.SF_OPPS IS 'Cleaned Salesforce opportunity table.'`

```
COMMENT IF EXISTS ON COLUMN PRODUCT_ASTRO.DAG_RUNS.START_TS IS 'Timestamp when the DAG began to run.';
COMMENT IF EXISTS ON COLUMN PRODUCT_ASTRO.DAG_RUNS.DAG_ID IS 'The name given to the dag.';
```

**Comment by pawel-big-lebowski** [comment]
Related PR: https://github.com/sqlparser-rs/sqlparser-rs/pull/831

**Comment by pawel-big-lebowski** [comment]
PR merged in target repo.
