### ISSUE TITLE
sql: Support PIVOT query syntax in SQL parser

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1678]
Add SQL parser support for the remaining (complicated) cases for the CREATE OR REPLACE command in Snowflake.

```
CREATE OR REPLACE table metrics.combined_monthly_tmp AS (    with acct_summary AS (
        SELECT
            u.eom_date,
            u.parent_id,
        FROM metrics.usage_monthly u
    )

    , pivot_summary AS (

        SELECT
            p.*
        FROM summary a
            PIVOT (SUM(a.usage) FOR a.inv_item_type IN ('item1', 'item2', 'item3')) AS p
        (eom_date, parent_id)
    )

    SELECT
        cc.eom_date,
        parent_id,
        ROUND(NVL(u.item1, 0), 2) item1_amt,
        ROUND(NVL(u.item2, 0), 2) item2_amt,
        ROUND(NVL(u.item_3, 0), 2) item3_amt,
    FROM pivot_summary u
        FULL JOIN metrics.usage_monthly c
            USING (parent_id, eom_date)
        LEFT JOIN commons.calendar cc
            ON  cc.date = NVL(u.eom_date, c.eom_date)
    ORDER BY
        parent_id,
        c.eom_date)
```

**Comment by pawel-big-lebowski** [comment]
@denimalpaca Sqlparser library already has support for `create or replace` ([see code](https://github.com/sqlparser-rs/sqlparser-rs/blob/548191814c3ba53c131a53b5035951851bef11f5/src/ast/helpers/stmt_create_table.rs#L48)). Please provide some examples on what is missing.

**Comment by pawel-big-lebowski** [comment]
The issue with the example query provided is related to missing support of PIVOT query syntax ([Snowflake doc](https://docs.snowflake.com/en/sql-reference/constructs/pivot)) within sqlparser.

**Comment by pawel-big-lebowski** [comment]
https://github.com/sqlparser-rs/sqlparser-rs/pull/836
