### ISSUE TITLE
spark: tests run multiple times

### ISSUE THREAD

**Issue by tnazarew** [OpenLineage/OpenLineage#1680]
Tests in `app:test` are run both in `build-integration-spark` and `integration-test-integration-spark` (each is run 3 times because of different spark versions). The workflow should be modified to avoid rerunning jobs that already succeeded.

**Comment by pawel-big-lebowski** [comment]
I think we mitigated it a moment ago with those lines:
 
https://github.com/OpenLineage/OpenLineage/blob/863b42e943417db969cc5b943f12dbc6e4004565/integration/spark/app/build.gradle#L242-L244
