### ISSUE TITLE
sql: Support Create Stage Snowflake Query

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#1703]
The Snowflake queries for `CREATE STAGE ...` are not supported.

Example:
```
CREATE STAGE IF NOT EXISTS IN_OPENLINEAGE.DATA
      URL='gcs://openlineage/data/'
      FILE_FORMAT=(TYPE=PARQUET, TRIM_SPACE=TRUE)
      COPY_OPTIONS=(MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE)
      storage_integration = GCS_INT
```

**Comment by denimalpaca** [comment]
duplicate #1013

**Comment by pawel-big-lebowski** [comment]
Let's reopen it please. There is a PR in sqlparser-rs to include this syntax in parser. 
Then a modification in our SQL integration is required to add input dataset based on the `URL` and output dataset as staging name.

**Comment by denimalpaca** [comment]
Can we add this stage syntax to this Issue as well?:
```sql
COPY INTO {DATABASE}.{SCHEMA}.{TABLE}
FROM (
  SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10
  FROM @ {DATABASE}.{SCHEMA}.{STAGE_NAME}(PATTERN => '{some_pattern}')
);
```

**Comment by pawel-big-lebowski** [comment]
The example statement provided is not valid as per Snowflake documentation: https://docs.snowflake.com/en/sql-reference/sql/create-stage

Issues: 
 * file format options should not be separated by a comma,
* storage_integration should occur before file_format

Example query that will work on the fix implemented: 
```
            CREATE STAGE IF NOT EXISTS IN_OPENLINEAGE.DATA
             URL='gcs://openlineage/data/'
             storage_integration = GCS_INT
             FILE_FORMAT=(TYPE=PARQUET TRIM_SPACE=TRUE)
             COPY_OPTIONS=(MATCH_BY_COLUMN_NAME=CASE_INSENSITIVE)
```
