### ISSUE TITLE
Marquez doesn't collect dataset metadata for BigQueryOperator in Airflow

### ISSUE THREAD

**Issue by mstrbac** [OpenLineage/OpenLineage#171]
Marquez doesn't collect dataset metadata for BigQueryOperator in Airflow. To collect BigQuery metadata, I tried the Airflow [example](https://github.com/MarquezProject/marquez/tree/main/examples/airflow) from the repo, but instead of `PostgresOperator`, I used `BigQueryOperator`. So, for example, I modified operators in `counter.py` as:

```
from airflow.contrib.operators.bigquery_operator import BigQueryOperator

t1 = BigQueryOperator(
    task_id='if_not_exists',
    bigquery_conn_id=BQ_CONN_ID,
    sql='''
    CREATE TABLE IF NOT EXISTS `my-project.my_dataset.counts` (
      value INTEGER
    );''',
    use_legacy_sql=False,
    dag=dag
)
```
```
t2 = BigQueryOperator(
    task_id='inc',
    bigquery_conn_id=BQ_CONN_ID,
    sql='''
    INSERT INTO `my-project.my_dataset.counts` (value)
         VALUES ({{params.value}})
    ''',
    params={
        "value": random.randint(1, 10)
    },
    use_legacy_sql=False,
    dag=dag
)
```

The dags ran successfully in Airflow, the counts and sums tables have been created on GCP, and in Marquez UI, metadata for jobs can be seen, but not for datasets.

**Comment by sar99** [comment]
Hello, 
I am facing the exact same issue, where the metadata for jobs is being registered but not for the datasets in case of BigQueryOeprator.

I wanted to know, by when can we expect a fix for this issue?
Thank you! :)

**Comment by collado-mike** [comment]
Can you give some details on the environment where this is not working for you? E.g., what version of Airflow? Are you running on a single machine? home-grown cluster? Cloud Composer? other hosted environment?

**Comment by virivigio** [comment]
Hi, I have the exact same problem with marquezproject/marquez:0.23.0

My environment: https://marquezproject.github.io/marquez/quickstart.html plain as it is proposed
My code: same as the issue description
My outcome: "No code available" in marquez UI selecting a job
