### ISSUE TITLE
dbt: wrapper breaks with arguments before [run,test,build,seed]

### ISSUE THREAD

**Issue by rossturk** [OpenLineage/OpenLineage#1716]
If I run the following command, the wrapper fails to emit lineage:

```
OPENLINEAGE_URL=http://localhost:5000 dbt-ol --profiles-dir . run
```

This is because the wrapper looks for `sys.argv[1]` to be one of `['run', 'test', 'build', 'seed']`, but dbt allows users to provide arguments before the subcommand.

**Comment by JDarDagran** [comment]
This requires a bit more of research but looks like parsing `run_results.json` should be a more viable option.
cc: @mobuchowski
