### ISSUE TITLE
python: automatically generate facets and core structures from JsonSchema

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#1746]
Since beginning of OpenLineage, facets and core structures are defined by JsonSchema. Java client is generated using that data. Python client is still not. This is a source of some bugs and adds more work for spec authors - it should be automated. 

The difficulty with that task is that Java has very useful JavaPoet library that takes care of serializing AST to working Java code. 
Python does not have a library like that.

Since we're already parsing JsonSchema using Java, it makes sense to create skeleton library providing similar API, but for Python - and reusing JsonSchema generation from existing Java generator.

**Comment by kacpermuda** [comment]
@JDarDagran Should this be closed now that https://github.com/OpenLineage/OpenLineage/pull/2520 is merged?
