### ISSUE TITLE
[PROPOSAL] Support for V2SessionCatalog

### ISSUE THREAD

**Issue by Anirudh181001** [OpenLineage/OpenLineage#1747]
Hi,
Delta catalog uses V2SessionCatalog for some operations under the hood. All catalog calls except the delta lake ones are delegated to V2SessionCatalog. Currently, openlineage does not support this spark catalog. 
Adding support for the V2SessionCatalog will be of great use as we are currently unable to emit metadata from some important pipelines which use this spark catalog, to our backend.
Wondering if this feature can be supported, or is on the roadmap potentially? Thanks a lot!

**Comment by pawel-big-lebowski** [comment]
https://github.com/OpenLineage/OpenLineage/blob/953f859fec14d6abc90c02fdfa02529e8f77200e/integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/catalog/V2SessionCatalogHandler.java#L27-L34

**Comment by pawel-big-lebowski** [comment]
waiting few days for Anirudh181001 to verify if he can reproduce issue and give more details on reproducing it.
