### ISSUE TITLE
Add documentation on how to configure OpenLineage on astronomer

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#176]
In the openlineage-airflow doc we should have a section on how to configure Marquez on Astronomer.

https://www.astronomer.io/docs/cloud/stable/deploy/configure-deployment#set-environment-variables

https://github.com/OpenLineage/OpenLineage/tree/main/integration/airflow#configuration

**Comment by mobuchowski** [comment]
I believe this is done 😉
