### ISSUE TITLE
Null Pointer Exception with OpenlineageSparkListener

### ISSUE THREAD

**Issue by Anirudh181001** [OpenLineage/OpenLineage#1784]
Hi everyone, 
I am facing this null pointer exception in OpenlineageSparkListener for my job saving as a json/parquet.
`ERROR AsyncEventQueue: Listener OpenLineageSparkListener threw an exception
java.lang.NullPointerException
java.base/java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
java.base/java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
io.openlineage.spark.agent.JobMetricsHolder.addMetrics(JobMetricsHolder.java:40)
io.openlineage.spark.agent.OpenLineageSparkListener.onTaskEnd(OpenLineageSparkListener.java:179)
org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45)
org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)`

The spark submit command used is:
`spark-submit --py-files /usr/local/lib/common_utils.zip,/usr/local/lib/team_utils.zip,/usr/local/lib/project_utils.zip
   --conf spark.executor.cores=16
 --conf spark.hadoop.fs.s3a.connection.maximum=100 --conf spark.sql.shuffle.partitions=1000
 --conf spark.speculation=true --conf spark.sql.adaptive.advisoryPartitionSizeInBytes=256MB
  --conf spark.hadoop.fs.s3a.multiobjectdelete.enable=false --conf spark.memory.fraction=0.7 --conf spark.kubernetes.executor.label.experiment=some_label  --conf spark.kubernetes.executor.label.team=team_name --conf spark.driver.memory=26112m   --conf spark.kubernetes.executor.label.app.kubernetes.io/managed-by=pipeline_name --conf  spark.kubernetes.executor.label.instance-type=4xlarge --conf spark.executor.instances=10   --conf spark.kubernetes.executor.label.env=prd --conf spark.kubernetes.executor.label.job-name=job_name --conf spark.kubernetes.executor.label.owner=owner --conf spark.kubernetes.executor.label.pipeline=pipeline --conf spark.kubernetes.executor.label.platform-name=platform_name  --conf spark.speculation.multiplier=10 --conf spark.memory.storageFraction=0.4 --conf  spark.driver.maxResultSize=26112m --conf spark.kubernetes.executor.request.cores=15000m  --conf spark.speculation.interval=1s --conf spark.executor.memory=104g --conf spark.sql.catalogImplementation=hive  --conf spark.eventLog.dir=file:///logs/spark-events --conf spark.hadoop.fs.s3a.threads.max=100   --conf spark.speculation.quantile=0.75 job.py `
  
  Would greatly appreciate any help on this! Thanks!

**Comment by Anirudh181001** [comment]
@pawel-big-lebowski Hi sorry, just an update, this error came about when df was not saved as delta table, but saved as a json... The error was also obtained in a similar pipeline while saving as parquet...

**Comment by pawel-big-lebowski** [comment]
@Anirudh181001 I am preparing PR which prevents NPE (null pointer exception) without root cause analysis. This will let prepare OL events to be generated and sent without `JobMetrics` which are somehow nulls.
