### ISSUE TITLE
Spark dataset replaceName config parameter

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#1794]
There is a common scenario for Spark jobs to write datasets to external paths like:
```
s3://my-whatever-path/year=2023/month=04/day=24
```
which breaks lineage graph, as each day's datasets are different. This is related to partitioning, but supporting partitioning in a way that Openlineage understands partitioning logic of the job is non-trivial issue. However, the broken lineage problem can be solved with implementing a simple feature that gets rid of unwanted path subdirectories. 

This can be done with config parameters like:
```
spark.openlineage.dataset.replaceName.pattern=(.*)\/.*\/.*\/.*
spark.openlineage.dataset.replaceName.replacement=$1
```
which should solve the problem for `s3://my-whatever-path/year=2023/month=04/day=24`. 

The feature would run Java `replaceAll` on all dataset names contained within emitted events.

**Comment by mobuchowski** [comment]
@pawel-big-lebowski what do you think about using regex named groups for that purpose? This way you could match all the dataset name and replace just the group you want to replace, instead of making sure to not match what you don't want to match. I think it's more explicit then too.
