### ISSUE TITLE
[INTEGRATION][Snowflake] Snowflake Integration described in blogpost does not work

### ISSUE THREAD

**Issue by vpulusu** [OpenLineage/OpenLineage#1800]
### What is the target system?

Snowflake

### What kind of integration is this?

- [X] Produces OpenLineage metadata
- [X] Consumes OpenLineage metadata
- [X] Something else

### How should this integration be implemented?

I fount the issue in using this as we followed the blog Data Lineage with Snowflake. We could not see the results of Dag runs. I would request you to help me in setting up with this process. And error handling of this.

### Where should this integration be implemented?

- [X] In the target system
- [ ] In the OpenLineage repo
- [ ] Somewhere else

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work

**Comment by harels** [comment]
Can you please provide more details on this issue?
where are you capturing lineage? airflow version, open lineage version.
which operators are being used?

**Comment by JDarDagran** [comment]
@vpulusu https://github.com/Snowflake-Labs/OpenLineage-AccessHistory-Setup/pull/21 this should probably fix the issue.
