### ISSUE TITLE
[Spark] duplicate events when for delta

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#1828]
Each join query run on top of delta tables have two start and two complete events. Openlineage 0.22..00
https://openlineage.slack.com/archives/C01CK9T7HKR/p1683014620909079

```
Hi Team,
I have configured Open lineage with databricks and it is sending events to Marquez as expected. I have a notebook which joins 3 tables and write the result data frame to an azure adls location. Each time I run the notebook manually, it creates two start events and two complete events for one run as shown in the screenshot. Is this something expected or I am missing something?
```

**Comment by Sai7656** [comment]
Hi @pawel-big-lebowski 
As discussed, we are still seeing two start and two complete events for a single job. I have attached the sample code and log file for reference.

Also, both the events are slightly different in terms of additional information the latest event contains.
for example for two start events the latest start event contains an additional block with "environment-properties"

[OL_Duplicate_Events.zip](https://github.com/OpenLineage/OpenLineage/files/11505548/OL_Duplicate_Events.zip)

**Comment by Sai7656** [comment]
HI @pawel-big-lebowski 
any updates on this issue?

**Comment by pawel-big-lebowski** [comment]
When working on Spark 3.4 support, we are going to introduce extravert filter for delta generating Ol events based on some delta-internal jobs:
https://github.com/OpenLineage/OpenLineage/pull/1790/files#diff-170b33f81a5e8d9d39f4c363923c2b82adfbb0cf27bedb5d575f8e33dacb277a
