### ISSUE TITLE
[INTEGRATION] [Airflow] Support for S3 Operators in marquez_airflow

### ISSUE THREAD

**Issue by nizardeen** [OpenLineage/OpenLineage#183]
Need support for S3 operator and extractor in marquez_airflow to run a DAG.

**Comment by kacpermuda** [comment]
S3 Operators are already supported as listed [here](https://airflow.apache.org/docs/apache-airflow-providers-openlineage/stable/supported_classes.html#apache-airflow-providers-amazon). Closing this
