### ISSUE TITLE
Same Delta Table generating two different dataset names in the event

### ISSUE THREAD

**Issue by Sai7656** [OpenLineage/OpenLineage#1842]
Hi,

I am seeing one issue with OL and databricks integration.
 I have a notebook where I am joining three tables and writing data to a table named "openlineage_poc.test_temp" with its path at mount location "mnt/abc/def/openlineage_poc/gold/temp/test". But while building the lineage the output in the events is appearing as "/mnt/abc/def/openlineage_poc/test_temp" which is following the schema path+table_name pattern. 

when I read the table in subsequent steps, the dataset name for the input entries appearing as the exact path("mnt/abc/def/openlineage_poc/gold/temp/test" ). This is creating dummy datasets which doesn't look good.

OL version : 0.22
code to write data : purchaseorder_header_df.write.mode("overwrite").saveAsTable("openlineage_poc.test_temp")
code to read table: purchase_df=spark.sql("""select * from openlineage_poc.test_temp""")

**Comment by pawel-big-lebowski** [comment]
I was able to reproduce the described behaviour by running following spark code:
```
spark.sql("CREATE database openlineage_poc LOCATION '/tmp/delta/openlineage_poc'");
spark.sql("CREATE TABLE openlineage_poc.test_temp (a INT, b STRING) USING delta LOCATION '/tmp/delta/openlineage_poc/gold/temp/test'");

createExampleDataset().write().mode("overwrite").saveAsTable("openlineage_poc.test_temp");
```

The first create table contains generates Openlineage event with output dataset:
```
  "namespace" : "file",
  "name" : "/tmp/delta/openlineage_poc/gold/temp/test",
```
while, the latter `saveAsTable`:
```
  "namespace" : "file",
  "name" : "/tmp/delta/openlineage_poc/test_temp",
```
Although this looks like a bug at first glance, I realised there are two directories created by spark. 

It seems as `.write().mode("overwrite").saveAsTable` was overwriting a table and NOT using existing table's `location`. Instead, I it puts data it into default location of a database.

**Comment by Sai7656** [comment]
Hi @pawel-big-lebowski 
I don't think so it creates another path and puts data there when we use overwrite. I didn't find any folder under database location. Also, reading data in subsequent steps from same table(or path) fetches the updated records(which should not be the case if it writes to database location)

**Comment by pawel-big-lebowski** [comment]
![image](https://github.com/OpenLineage/OpenLineage/assets/1646950/dfa4a66c-0c50-4684-a9ae-3067bdf2ab98)

directory was cleared before running the test

**Comment by Sai7656** [comment]
![image](https://github.com/OpenLineage/OpenLineage/assets/60571532/c54809db-5684-4dd0-9813-58ca78bd082d)
I don't see any such temp folders(purchaseorder_temp) in my case where writing to a deltalake.
