### ISSUE TITLE
Open-lineage 0.26.0 doesn't create any dataset ? (regression?)

### ISSUE THREAD

**Issue by dkt-sophie-ly** [OpenLineage/OpenLineage#1874]
Hi all ! 

Since this issue (https://github.com/OpenLineage/OpenLineage/issues/1841) is resolved and the PR released in open-lineage 0.26.0, I tried to re-run the script again and now I can't see any dataset created (input and output empty).

New event:

{
  "job": {
    "name": "issue_dag",
    "facets": {},
    "namespace": "airflow_local"
  },
  "run": {
    "runId": "9c9328ce-0ac5-3528-ab5a-ac62f9715f70",
    "facets": {
      "nominalTime": {
        "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/airflow",
        "_schemaURL": "https://raw.githubusercontent.com/OpenLineage/OpenLineage/main/spec/OpenLineage.json#/definitions/NominalTimeRunFacet",
        "nominalEndTime": "2023-05-22T19:18:18.964488Z",
        "nominalStartTime": "2023-05-21T19:18:18.964488Z"
      }
    }
  },
  "inputs": [],
  "outputs": [],
  "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.26.0/integration/airflow",
  "eventTime": "2023-05-22T19:18:19.480704Z",
  "eventType": "START"
}

I can see that I'm using open-lineage 0.20.0 in the producer so I guess it's the right version.

Do you know if it's an issue on my side or a regression in the version of open-lineage ?

Thanks for your help again !

**Comment by mobuchowski** [comment]
@dkt-sophie-ly this looks like Airflow generated event, while the issue you linked was about Spark integration. Are you sure you're looking at the right event?

**Comment by dkt-sophie-ly** [comment]
My job spark is trigger by an airflow job, but yes you right it's an airflow event and I don't have any event on the spark job side. 
It may be a problem during the installation. I'll check that on my side first.

Sorry my bad !
