### ISSUE TITLE
[security] ftp is considered insecure

### ISSUE THREAD

**Issue by merobi-hub** [OpenLineage/OpenLineage#1935]
An FTP-related module is being imported in airflow/extractors/ftp_extractor.py.

```
4	import socket
5	from ftplib import FTP_PORT
6	from typing import List, Optional
```

Recommended solution is to use SSH/SFTP/SCP or some other encrypted protocol.

**Comment by mobuchowski** [comment]
@merobi-hub yes, but we're providing that extractor for Airflow's FTP extractor. If user wants to use it despite the problems, it's their choice - in this case we're merely providing tools, just as Airflow.
