### ISSUE TITLE
spark: two jobs operating on different datasets in same spark file can be named the same

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#1943]
Currently, a Spark job name is created from action name which is misleading as different actions run with the same name can be writing to different output datasets. So, although the jobs are different, they end up within same graph nodes blurring the lineage. 

The solution for this would be to: append dataset name to the end of the job, the same way in which it is actually done for databricks platform.

**Comment by githubopenlineageissues** [comment]
Hi [pawel-big-lebowski](https://github.com/pawel-big-lebowski) , Will appreciate if you can please guide if the resolution is coming in next version. Also if there is a workaround or point to code which we can use for time being to get past this issue. Appreciate you help. Thanks

**Comment by pawel-big-lebowski** [comment]
Hi @githubopenlineageissues. Yes, it's coming, it's important for many people so you can expect it happen soon. Thanks for the interes.

**Comment by githubopenlineageissues** [comment]
Hi, Any movement on this one it has really been a showstopper for us in terms of adopting open lineage. Thank you for your time.

**Comment by pawel-big-lebowski** [comment]
I think we won't make it this release, most probably the next one.

**Comment by merobi-hub** [comment]
@githubopenlineageissues thanks for your interest in the project. In case it's helpful while you're waiting for a fix, [here](https://github.com/OpenLineage/OpenLineage/pull/1330/files) is the solution for databricks that Pawel mentioned.

**Comment by githubopenlineageissues** [comment]
Thank you @merobi-hub

**Comment by githubopenlineageissues** [comment]
Thank you @pawel-big-lebowski , will be big help.
