### ISSUE TITLE
Upgrade org.apache.iceberg:iceberg-spark3-runtime version in spark3

### ISSUE THREAD

**Issue by juancappi** [OpenLineage/OpenLineage#1969]
The current version specified for spark integration in `spark3` project [gradle.build](https://github.com/OpenLineage/OpenLineage/blob/bc1f525ee226741376830b63c45586887508d1a2/integration/spark/spark3/build.gradle#L67C18-L67C66), `0.12.1`, is quite old and missing SQL support for time travel (supported from iceberg 0.14.0 / Spark 3.3 onward)

**Comment by pawel-big-lebowski** [comment]
The code should be working with iceberg 1.3.0. We're testing this iceberg version for spark 3.4
