### ISSUE TITLE
spark: no outputs from merge into queries

### ISSUE THREAD

**Issue by sdkdgrant** [OpenLineage/OpenLineage#2014]
I am trying to get lineage in the form of `inputs -> notebook -> outputs` from a notebook that either creates a new Delta table in an Azure Data Lake, or merges into an existing one. The input files would usually be csv, json, or parquet in case that makes a difference.

However, none of the `merge into` queries I've run have had outputs in the emitted OL events. I used the following code to replicate the problem:

```python
from delta import DeltaTable
import pyspark.sql.functions as f

base_path = "abfss://redacted@redacted.dfs.core.windows.net/DG_test"
dbutils.fs.rm(f"{base_path}/silver/sample", True)

dbutils.fs.put(f"{base_path}/bronze/sample.csv",
"""col1,col2
1,a
2,b""", True)

df = spark.read.option("header", True).csv(f"{base_path}/bronze/sample.csv")
df.write.format("delta").save(f"{base_path}/silver/sample")

dbutils.fs.put(f"{base_path}/sample2.csv",
"""col1,col2
2,bb
3,c""", True)

df = spark.read.option('header', True).csv(f"{base_path}/bronze/sample2.csv")
dt = DeltaTable.forPath(spark, f"{base_path}/silver/sample")
(
    dt.alias("target")
    .merge(source=df.alias("updates"), condition=f.expr("target.col1 = updates.col1"))
    .whenMatchedUpdateAll()
    .whenNotMatchedInsertAll()
    .whenNotMatchedBySourceDelete()
    .execute()
)
```
The issue is present when the base path is a DBFS path, or if the spark/delta code is executing in a Jupyter notebook with local files.

OpenLineage version: 0.30.1 (downloaded from Maven, same issue was present in 0.29.2)
Azure Databricks runtime version: 13.2 (Spark 3.4.0)

I have attached all the emitted events. Here is a summary:
```
runId                                | events | inputs | outputs | job name
-------------------------------------+--------+--------+---------+----------------------------------------------------
066d3185-8062-4ba4-bb12-dc0df06b0938 | 2      | csv 1  | delta   | execute_save_into_data_source_command_silver_sample
4252cd8d-a6bf-4765-a59e-041e3034c3c6 | 5      | csv 1  | none    | execute_write_into_delta_command
71511851-0454-4e10-922e-653dba0d9bc3 | 2      | none   | none    | execute_merge_into_command_edge
2390ea29-9f16-4091-a049-ea25ff7c6d60 | 2      | csv 2  | none    | scan_csv
2653ef71-04f8-4c68-8e26-c260b02e577d | 5      | delta  | none    | execute_write_into_delta_command
```

Maybe my understanding is flawed, but I would expect to see at two runs (runId 1 or 2, and 5) that have both an input and output, along with `environment-properties` that contains the name of the notebook.

**Is the lack of outputs or `environment-properties` expected from the pyspark code I am running, or is this a bug?**

**Comment by sdkdgrant** [comment]
And here is the file I thought I'd attached:
[events.json.gz](https://github.com/OpenLineage/OpenLineage/files/12196358/events.json.gz)

**Comment by sdkdgrant** [comment]
Thanks for getting back to me.

1. I get the same issue with local Jupyter.
2. The behaviour is the same with SQL:
```python
df.createOrReplaceTempView("sample2_csv")
spark.sql(f"""
    MERGE INTO delta.`{base_path}/silver/sample` target
        USING sample2_csv updates
        ON target.col1 = updates.col1
    WHEN MATCHED THEN UPDATE SET *
    WHEN NOT MATCHED THEN INSERT *
    WHEN NOT MATCHED BY SOURCE THEN DELETE
""")
```
(replaces last 9 lines of the original code)

**Comment by pawel-big-lebowski** [comment]
Hi @sdkdgrant , I was able to reproduce the issue within PR https://github.com/OpenLineage/OpenLineage/pull/2026/files

The issue is related to accessing delta tables through the path `delta.`{base_path}/silver/sample`. If you access table by its names, lineage and column level lineage gets' collected.
