### ISSUE TITLE
[SPARK] `ExternalRDD` unsupported in `InputFieldCollector`

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#2037]
```scala
// Given a class
case class Foo(x:String)

// Read
val datasets0 = spark.read.parquet("...").rdd
val dataset1 = spark.read.parquet("...").rdd

// Combined
val input = datasets0.union(dataset1)

// Map, then write
input.map(x => Foo(x.toString())).toDF().write.parquet("...")
```

The above code snippet produces an output dataset, but no input datasets with the following warning:

```
WARN: InputFieldCollector: Could not extract dataset identifier from org.apache.spark.execution.ExternalRDD
```

**Comment by pawel-big-lebowski** [comment]
`InputFieldCollector` collects inputs for column level lineage, which does not support RDDs. The `WARN` you see should be removed for `ExternalRDD` as it's impossible to make column lineage work on the rdd level. 

We need to look at existing DatasetBuilders and DatasetVisitors, try to find out which of them should be applied on ExternalRDD or develop a new one (possibly similar to `LogicalRDD`)

**Comment by pawel-big-lebowski** [comment]
I've tried to reproduce behaviour you describe and written two tests in the PR #2039. Please take a look at `spark_rdd_with_parquet. py` test which does same you do. 

I observed three issues: 
 * it's not working for spark 3.4.0,
 * WARN from `InputFieldsCollector` should not occur for `ExternalRDD`,
 * input datasets in the event are duplicated.

I am happy to work on these, but this is NOT the behaviour you describe in the issue. 

The newly created integration test can be run with: 
```
./gradlew clean build
./gradlew :app:integrationTest -x test --tests io.openlineage.spark.agent.SparkContainerIntegrationTest.testRddWithParquet -Pspark.version=3.3.2
```

Please try to compare this with code on your side and feel free to change `spark_rdd_with_parquet. py` to mimic described behaviour.
