### ISSUE TITLE
Issue with Event Filtering in Databricks Integration for `adaptive_spark_plan`

### ISSUE THREAD

**Issue by algorithmy1** [OpenLineage/OpenLineage#2058]
Hello OpenLineage team,

While implementing the current OpenLineage Spark integration in Databricks, we've made an interesting observation regarding event filtering and its behavior with narrow and wide transformations:

1. For a **narrow transformation** (without shuffle), the event is `execute_insert_into_hadoop_fs_relation_command` and it doesn't include `adaptive_spark_plan`.
2. For a **wide transformation** (with shuffle), the event is `adaptive_spark_plan` and doesn't have `execute_insert_into_hadoop_fs_relation_command`.

We've identified that the `adaptive_spark_plan` is actively filtered out in the `DatabricksEventFilter` class. This results in the event being completely ignored due to this line: https://github.com/OpenLineage/OpenLineage/blob/41dbbf1799595bd9cd1567df0a7027de08619741/integration/spark/shared/src/main/java/io/openlineage/spark/agent/filters/DatabricksEventFilter.java#L30

To validate, we compiled a JAR without this filtering line, and the integration worked perfectly from Databricks.

**Example Spark Jobs:**

1. **Narrow Transformation**
   ```scala
   val data = Seq((1,"a"),(2,"b"),(3,"c"))
   val rdd = spark.sparkContext.parallelize(data)
   val df = rdd.toDF("id", "value")
   df.write.parquet("/path/to/output/narrow_transformation")
   ```
2. **Wide Transformation**
    ```scala
    val data = Seq((1,"a"),(2,"b"),(3,"c"),(1,"d"))
    val rdd = spark.sparkContext.parallelize(data)
    val df = rdd.toDF("id", "value")
    df.groupBy("id").count().write.parquet("/path/to/output/wide_transformation")
    ```

**Proposed Solutions**:

- Short-term fix: Remove adaptive_spark_plan from the excludedNodes in DatabricksEventFilter. 
- Long-term resolution: Consider integrating the proposal from [#2056](https://github.com/OpenLineage/OpenLineage/issues/2056) for a more universal filtering mechanism.

Environment:
Databricks version: 12.2 LTS (includes Apache Spark 3.3.2, Scala 2.12)

I hope this provides a clear picture of the issue at hand. We're eager to collaborate on resolving this.

Thank you!

Best regards,

**Comment by pawel-big-lebowski** [comment]
Please feel free to prepare a PR, that removes `adaptive_spark_plan` line to see if the tests are passing. 

If you like, you can also prepare an extra integration test for databricks here -> https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/app/src/test/java/io/openlineage/spark/agent/DatabricksIntegrationTest.java

with a test body similar to the one here -> https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/app/src/test/java/io/openlineage/spark/agent/lifecycle/SparkEventFilterTest.java

Integration tests on databricks need to be triggered manually on circle-ci but they're really helpful (I can help with that) and you can test this test locally with your own databricks cluster. .

In case of such issues, we want to make sure that valuable events are sent and also make sure that backend is not flooded with dummy events.

**Comment by athityakumar** [comment]
@algorithmy1 @pawel-big-lebowski - Would this be something specific to DBR only, or for spark integration in general when shuffling would be involved?

**Comment by algorithmy1** [comment]
@athityakumar It is not specific to Databricks but the updates made will only affect jobs running in Databricks

**Comment by algorithmy1** [comment]
@pawel-big-lebowski I prepared a PR
