### ISSUE TITLE
[SPARK] Recommended way to add custom facets openlineage-spark

### ISSUE THREAD

**Issue by praveen-kanamarlapudi** [OpenLineage/OpenLineage#2073]
Hello OpenLineage team,

We have been using open lineage and openlineage-spark connector for a while. We have need to add custom facets to run events emitted from openlineage-spark connector.

**Question:**
What is the recommended way to add custom facets in openlineage-spark? We have a need to extend the openlineage-spark connector and add new custom facets to the spark events. Can you please suggest what is the recommended way?

Thanks,
Praveen

**Comment by pawel-big-lebowski** [comment]
Please refer to this when adding custom facets: https://github.com/OpenLineage/OpenLineage/tree/main/integration/spark#api

Do you have any particular facets in your mind? If they solve a generic problem, it may be useful include them in openlineage-spark or even in Openlineage specification.

**Comment by praveen-kanamarlapudi** [comment]
@pawel-big-lebowski thanks for sharing the doc link. 

We are adding a custom facet to include job orchestrator(airflow ..etc) details. It will be helpful to include spark job orchestrator details into run events.
