### ISSUE TITLE
Examples in the default extractor for airflow are not following the standards

### ISSUE THREAD

**Issue by dariospoti** [OpenLineage/OpenLineage#2074]
When checking this example in the repo, to see how the airflow default extractor produces json, https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/tests/integration/requests/default_extractor.json

I noticed it is not producing openlineage compliant json, in fact it does miss fields like: `publisher` and `eventTime` which are marked as mandatory in here https://openlineage.io/apidocs/openapi/

Are they outdated? Is the Default Extractor still relevant?

**Comment by mobuchowski** [comment]
@dariospoti those are not complete events or examples. Those are data used in comparison in integration tests - they only contain keys we want to compare in some particular tests.

**Comment by kacpermuda** [comment]
Closing this. Feel free to reopen if needed.
