### ISSUE TITLE
[PROPOSAL] Support NessieCatalog for Iceberg in Spark integration

### ISSUE THREAD

**Issue by cnatsis** [OpenLineage/OpenLineage#2084]
**Purpose:**
As of now, Spark-Iceberg integration for OpenLineage supports `hive`, `hadoop` and `rest` catalogs. Iceberg provides integration with Nessie, which is a custom REST based transactional catalog for data lakes, enabling various use cases like git-like operations on data and multi-table transactions. In the current version of OpenLineage, it is not possible to use the `rest` based catalog setting with the use of Nessie, and it would be great if it was supported by OpenLineage.

Project Nessie
https://projectnessie.org/

Iceberg integration with Nessie
https://iceberg.apache.org/docs/latest/nessie/

Iceberg catalog configuration
https://iceberg.apache.org/docs/latest/spark-configuration/#catalog-configuration

OpenLineage Iceberg handler
https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/catalog/IcebergHandler.java

**Comment by harels** [comment]
Hey @cnatsis , thanks for creating this issue! Would you be interested in contributing this support? We'd be happy to help out.

**Comment by julwin** [comment]
Hey @harels - I have started an implementation with my limited knowledge of java. As far as I understand, this should solve the integration issue with nessie.

Please guide me if additional steps are necessary to move this issue forward.

**Comment by harels** [comment]
thanks for your contribution @julwin ,we'll review this. tagging @pawel-big-lebowski as well.
