### ISSUE TITLE
dbt target-path yml deprecated

### ISSUE THREAD

**Issue by cmtk** [OpenLineage/OpenLineage#2093]
As of [dbt v1.5](https://github.com/dbt-labs/dbt-core/releases/tag/v1.5.0), usage of `target-path` in the `dbt_project.yml` file has been deprecated, now preferring a CLI flag or env var. It will be removed in a future version. See https://github.com/dbt-labs/dbt-core/issues/6882

Docs: https://docs.getdbt.com/reference/project-configs/target-path

Not having target-path in the dbt_project.yml currently breaks this part of the dbt integration:

https://github.com/OpenLineage/OpenLineage/blob/87653a1d95e2b38c1e79ad3c098918d4e3b1bdd9/integration/common/openlineage/common/provider/dbt/local.py#L52-L65C10

**Comment by JDarDagran** [comment]
@cmtk  thanks for pointing this out!
Docs also mention: `The precedence order is: CLI flag > env var > dbt_project.yml(deprecated)`. Do you possibly know if this is true for all dbt versions? If not, we should enable some sort of version-based behaviors (which I'd really-really like to avoid).

**Comment by cmtk** [comment]
Good question! Going back to the first mention of order in the source doc (aligns with selecting v1.2 on doc site, no direct link available it seems), it does appear to be the same order:
https://github.com/dbt-labs/docs.getdbt.com/blob/8e6f6aab6daaeaac213b39d4a3f23261c411c566/website/docs/reference/project-configs/target-path.md

**Comment by JDarDagran** [comment]
👍 
Seems like you're pretty familiar with the code. Would you be willing to contribute the PR? I'll be glad to help if needed 😃

**Comment by cmtk** [comment]
Looks like according to this comment and the next, it has always been that order:
https://github.com/dbt-labs/dbt-core/issues/7140#issuecomment-1460662616

Unfortunately at this point I'm far better at searching than coding, or I'd have been quite happy to submit a PR as well. 😞
