### ISSUE TITLE
[PROPOSAL] Spark jobs should have a parent Job describing the Run State of Spark pipeline.

### ISSUE THREAD

**Issue by suraj5077** [OpenLineage/OpenLineage#2105]
**Purpose:**
Currently there is no way to group spark jobs running within the same SparkContext since there is no concept of parent Jobs in Spark. In airflow we support Parent Runs and this way we can group Tasks together within a single DAG.

**Use cases:**
- For data catalog based OL backends, a user might want to search for Spark ETL pipelines first and then dive deeper into a specific pipeline to view the Spark Jobs. This is similar to how a user can search for airflow DAG assets and then look into the Tasks for that DAG.
- Also this will help display operational metadata for Spark pipelines. For Airflow we have DAG run status (parent job status), but for Spark we don't have any such concept to display the completion state of a pipeline run. We can only track it at SparkJob level.

**Proposed implementation**
This should be similar to the airflow implementation.

**Comment by pawel-big-lebowski** [comment]
So, for spark run on YARN an applicationId seems to be a parent job marker. For databricks, it could be the notebook name. 

Do you think is it possible to make it generic across all the possible spark runtimes?

**Comment by suraj5077** [comment]
We can use the applicationId as the parent job marker and identify the parentJob. The problem here is that we don't get any information on when the parent Job started and completed. We get the run state of the child jobs but there is no way to mark a complete parent Job Run to track pipeline success/failure. The airflow integration helps us identify the parent run status. 
At a pipeline level such events would be helpful.

**Comment by dolfinus** [comment]
Does the #2371 closes this issue?

**Comment by kacpermuda** [comment]
@pawel-big-lebowski Should this be closed?

**Comment by suraj5077** [comment]
https://github.com/OpenLineage/OpenLineage/pull/2371 closes this issue.
