### ISSUE TITLE
Great Expectations integration doesn't work in Google Cloud Composer

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#211]
The current implementation of the OL integration doesn’t work in Cloud Composer. It’s likely that it doesn’t work with any installation of Airflow using the CeleryExecutor. The current implementation relies on the ability to wrap the execute method of the GreatExpectationsOperator and to capture the returned result before it is passed to the Airflow DAG. For whatever reason, this “[monkey-patching](https://en.wikipedia.org/wiki/Monkey_patch)” doesn’t work in Cloud Composer. It does work correctly when running Airflow locally on a single host. I haven't been able to verify that it works in the existing airflow integration test (GreatExpectations functionality is not exercised in the test).

### XCom
Fortunately, the GreatExpecationsOperator does publish validation results into Airflow’s cross-communication mechanism (XCom), meaning we can fetch the results from the worker host at runtime. The response from the worker host is a json blob that we need to parse. The existing code already navigates this structure. However, the existing solution requires users to call a static set_dataset_info method on the GreatExpectationsExtractor class, passing in the instance of the GreatExpectationsOperator. The operator is then monkey-patched with the additional information. It is unclear whether this method of naming the dataset will work in Cloud Composer.

Alternatively, we can look at the JSON returned from the operator at runtime to determine the dataset name. Unfortunately, the arguments passed to the operator aren’t guaranteed to give an easily parseable dataset name. Two example JSON blobs are below- one for BigQuery and one for GCS:

BigQuery
```json
"meta": {
 "great_expectations_version": "0.13.26",
 "expectation_suite_name": "orders_suite",
 "run_id": {
   "run_name": "20210818T051320.186669Z",
   "run_time": "2021-08-18T05:13:20.186669+00:00"
 },
 "batch_kwargs": {
   "project": "bq-project",
   "table": "orders",
   "dataset": "bq_dataset",
   "datasource": "food_delivery_db"
 },
 "batch_markers": {
   "ge_load_time": "20210818T051320.055448Z"
 },
 "batch_parameters": null,
 "validation_time": "20210818T051320.192586Z",
 "expectation_suite_meta": {
   "BasicSuiteBuilderProfiler": {
     "batch_kwargs": {
       "bigquery_temp_table": "bq-project.bq_dataset.ge_tmp",
       "data_asset_name": "orders",
       "datasource": "food_delivery_db",
       "limit": 1000,
       "schema": null,
       "table": "orders"
     },
     "created_at": 1627943912.4953547,
     "created_by": "BasicSuiteBuilderProfiler"
   },
   "citations": [
     {
       "batch_kwargs": {
         "bigquery_temp_table": "bq-project.bq_dataset.ge_orders_tmp",
         "data_asset_name": "orders",
         "datasource": "food_delivery_db",
         "limit": 1000,
         "schema": null,
         "table": "orders"
       },
     }
   ],
   "columns": {
     "id": {
       "description": ""
     },
     "placed_on": {
       "description": ""
     },
     "menu_item_id": {
       "description": ""
     },
     "quantity": {
       "description": ""
     },
     "discount_id": {
       "description": ""
     },
     "comment": {
       "description": ""
     }
   }
 }
}
```

**GCS**
```json
"meta": {
 "great_expectations_version": "0.13.26",
 "expectation_suite_name": "gcs_orders",
 "run_id": {
   "run_name": "20210819T191553.090700Z",
   "run_time": "2021-08-19T19:15:53.090700+00:00"
 },
 "batch_kwargs": {
   "datasource": "gcs",
   "data_asset_name": "orders_file",
   "path": "gs://the_bucket/the_data/part-00000-ef898d87-fe05-4b1b-8f31-7ec57a8682ac-c000.snappy.parquet",
   "reader_method": "read_parquet"
 },
 "batch_markers": {
   "ge_load_time": "20210819T191551.999073Z",
   "pandas_data_fingerprint": "d41d8cd98f00b204e9800998ecf8427e"
 },
 "batch_parameters": null,
 "validation_time": "20210819T191553.097890Z",
 "expectation_suite_meta": {
   "great_expectations_version": "0.13.26"
 }
}
```

Most of the response fields are omitted, but the fields that can identify a dataset and its composition are included. Notably, the `batch_kwargs` are used to specify the appropriate identifiers for each dataset. The `DataContext` contains specific `DataSource` implementations, such as a `SQLAlchemyDatasource` or a `PandasDatasource`. Each of those knows how to construct the correct `Dataset` implementation based on those `batch_kwargs`. The `DataContext` can return the `Datasource` by calling `get_datasource`.

One viable option is to use the `DataContext` to find the `Datasource`, then, based on the implementation of the DataSource we detect, we can parse the `batch_kwargs` ourselves to construct the `Dataset` name and any necessary facets (schema, datasource, etc.).
This is known to work in a cloud environment, but hasn’t been tested thoroughly.

**Configuration required**: 
None. The user simply includes the OL library in their Airflow instance and our code does everything.

**Coding required**:
Parsing the `batch_kwargs` to construct the dataset name and facets. The code will live in the existing `GreatExpectationsExtractor`

### ValidationAction
GreatExpectations also comes with a callback mechanism called `ValidationAction`s. These actions are custom classes that are invoked by GreatExpectations after validation completes. These actions are invoked whether the validation succeeds or fails. Some example actions that ship with GreatExpectations  include Slack notifications and PagerDuty alerts. 

The `ValidationAction`’s run method is invoked with the fully constructed Dataset (e.g., `PandasDataset` or `SQLAlchemyDataset`), which contains all of the information necessary to construct the OL Dataset, including the connection URL (SQL) or filesystem path (Pandas).

A nice property of the `ValidationAction` approach is that it is not Airflow-specific, so any GreatExpectations job can report Dataset facets to the OpenLineage server. This includes runs in Spark clusters as well as hosted Airflows and custom environments. It also works both locally, on a single host, as well as distributed in a cloud environment. 

**Configuration required**:
The user needs to customize the great_expectations.yml file to specify the `OpenLineageValidationAction`. The user can specify OL configuration in the yml file, such as the host name, namespace, apiKey, etc.

It may be possible to programmatically modify the `DataContext` in Airflow to automatically add the OL `ValidationAction` if the user hasn’t specified it. It hasn’t been tested that this modification will be persisted across the serialization from the scheduler to the worker.

**Coding required**:
1. Create a new `OpenLineageValidationAction`
2. Collect dataset information from `Dataset` impl - if SqlAlchemyDataset, use the `asset.engine.url`. If `PandasDataset`, use `asset.batch_kwargs.path`.
3. There are two options for reporting lineage to OL server-
  1. Return dataset information into the “actions_results” field of the response. Use above XCom logic to find the dataset information and report dataset information and facets. While this works well in the Airflow case, something else would need to report the lineage outside of Airflow.
  2. Post directly from the `OpenLineageValidationAction`. The environment variables pointing to server location, apiKey, etc. are already present on the worker host. The `runId` of the task will need to be reported- it may be possible to use the `lineage_run_id` macro to parameterize the `OpenLineageValidationAction` constructed by the operator. This works in both the Airflow environment as well as any environment in which Great Expectations is running.

**Comment by mobuchowski** [comment]
Great writeup @collado-mike !

If we're purely talking about current Airflow implementation, then using XCom seems to fit closer to what we want to achieve. Hovewer, `batch_kwargs` seems to [become deprecated.](https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/migrating_versions.html#v3-vs-v2-api-v2) It could lead to having to support two separate versions. 

`ValidationAction`'s approach seems more robust - API seems more stable; possiblity to specify OL url/apiKey in config; only three concrete datasets to get the data from. The requirement for adding OL data to `great_expectations.yml` doesn't seem to be big hurdle, and the fact that it can work without airflow is an added bonus.

Mini rant: 
It does not help that related GreatExpectations abstractions seem to be confusing, without specifying which version they target. For example `ValidationOperators` are something else than `ValidationActions`. 

I think exploring second option with cautiousness is the best option - for example, it's unclear to me if the ValidationAction receive results in the same format as current extractor based on Airflow's `GreatExpectationsOperator`.

**Comment by collado-mike** [comment]
> I think exploring second option with cautiousness is the best option - for example, it's unclear to me if the ValidationAction receive results in the same format as current extractor based on Airflow's `GreatExpectationsOperator`.

I diffed the XCOM response and the output of a ValidationAction that serializes the results to JSON. The gist is that the ValidationAction is given the `validation_result` field of the XCOM response. The rest of the suite information is excluded, but we're not really interested in that ATM. 
```bash
$ diff -wy xcom_json.json va_json.json
{								{
  "run_id": {						      <
    "run_name": "20210821T001304.862725Z",		      <
    "run_time": "2021-08-21T00:13:04.862725+00:00"	      <
  },							      <
  "success": true,					      <
  "validation_operator_config": {			      <
    "class_name": "ActionListValidationOperator",	      <
    "module_name": "great_expectations.validation_operators", <
    "name": "action_list_operator",			      <
    "kwargs": {						      <
      "action_list": [					      <
        {						      <
          "name": "openlineage",			      <
          "action": {					      <
            "class_name": "OpenlineageValidationAction",      <
            "module_name": "etl_orders"			      <
          }						      <
        }						      <
      ],						      <
      "result_format": {				      <
        "result_format": "SUMMARY",			      <
        "partial_unexpected_count": 20			      <
      }							      <
    }							      <
  },							      <
  "evaluation_parameters": null,			      <
  "run_results": {					      <
    "ValidationResultIdentifier::orders_suite/20210821T001304 <
      "validation_result": {				      <
        "meta": {						  "meta": {
          "great_expectations_version": "0.13.26",		    "great_expectations_version": "0.13.26",
          "expectation_suite_name": "orders_suite",		    "expectation_suite_name": "orders_suite",
          "run_id": {						    "run_id": {
            "run_name": "20210821T001304.862725Z",		      "run_name": "20210821T001304.862725Z",
            "run_time": "2021-08-21T00:13:04.862725+00:00"	      "run_time": "2021-08-21T00:13:04.862725+00:00"
          },							    },
          "batch_kwargs": {					    "batch_kwargs": {
            "project": "gcp_project",			      "project": "gcp_project",
            "table": "orders",					      "table": "orders",
            "dataset": "food_delivery",				      "dataset": "food_delivery",
            "datasource": "food_delivery_db"			      "datasource": "food_delivery_db"
          },							    },
          "batch_markers": {					    "batch_markers": {
            "ge_load_time": "20210821T001304.608346Z"		      "ge_load_time": "20210821T001304.608346Z"
          },							    },
          "batch_parameters": null,				    "batch_parameters": null,
          "validation_time": "20210821T001304.864608Z",		    "validation_time": "20210821T001304.864608Z",
          "expectation_suite_meta": {				    "expectation_suite_meta": {
            "BasicSuiteBuilderProfiler": {			      "BasicSuiteBuilderProfiler": {
              "batch_kwargs": {					        "batch_kwargs": {
                "bigquery_temp_table": "gcp_project.fo	          "bigquery_temp_table": "gcp_project.food_del
                "data_asset_name": "orders",			          "data_asset_name": "orders",
                "datasource": "food_delivery_db",		          "datasource": "food_delivery_db",
                "limit": 1000,					          "limit": 1000,
                "schema": null,					          "schema": null,
                "table": "orders"				          "table": "orders"
              },						        },
              "created_at": 1627943912.4953547,			        "created_at": 1627943912.4953547,
              "created_by": "BasicSuiteBuilderProfiler"		        "created_by": "BasicSuiteBuilderProfiler"
            },							      },
            "citations": [					      "citations": [
              {							        {
                "batch_kwargs": {				          "batch_kwargs": {
                  "bigquery_temp_table": "gcp_project.	            "bigquery_temp_table": "gcp_project.food_d
                  "data_asset_name": "orders",			            "data_asset_name": "orders",
                  "datasource": "food_delivery_db",		            "datasource": "food_delivery_db",
                  "limit": 1000,				            "limit": 1000,
                  "schema": null,				            "schema": null,
                  "table": "orders"				            "table": "orders"
                },						          },
                "batch_markers": {				          "batch_markers": {
                  "ge_load_time": "20210802T223807.004888Z"	            "ge_load_time": "20210802T223807.004888Z"
                },						          },
                "batch_parameters": null,			          "batch_parameters": null,
                "citation_date": "20210802T223832.521054Z",	          "citation_date": "20210802T223832.521054Z",
                "comment": "BasicSuiteBuilderProfiler added a	          "comment": "BasicSuiteBuilderProfiler added a citat
              }							        }
            ],							      ],
            "columns": {					      "columns": {
              "id": {						        "id": {
                "description": ""				          "description": ""
              },						        },
              "placed_on": {					        "placed_on": {
                "description": ""				          "description": ""
              },						        },
              "menu_item_id": {					        "menu_item_id": {
                "description": ""				          "description": ""
              },						        },
              "quantity": {					        "quantity": {
                "description": ""				          "description": ""
              },						        },
              "discount_id": {					        "discount_id": {
                "description": ""				          "description": ""
              },						        },
              "comment": {					        "comment": {
                "description": ""				          "description": ""
              }							        }
            },							      },
            "great_expectations_version": "0.12.0+0.g9701509a	      "great_expectations_version": "0.12.0+0.g9701509a.dirty
            "notes": {						      "notes": {
              "content": [					        "content": [
                "#### This is an _example_ suite\n\n- This su	          "#### This is an _example_ suite\n\n- This suite wa
              ],						        ],
              "format": "markdown"				        "format": "markdown"
            }							      }
          }							    }
        },							  },
        "success": true,					  "success": true,
        "evaluation_parameters": {},				  "evaluation_parameters": {},
        "results": [						  "results": [
          {							    {
            "meta": {},						      "meta": {},
            "success": true,					      "success": true,
            "expectation_config": {				      "expectation_config": {
              "expectation_type": "expect_table_row_count_to_	        "expectation_type": "expect_table_row_count_to_be_bet
              "meta": {						        "meta": {
                "BasicSuiteBuilderProfiler": {			          "BasicSuiteBuilderProfiler": {
                  "confidence": "very low"			            "confidence": "very low"
                }						          }
              },						        },
              "kwargs": {					        "kwargs": {
                "max_value": 1000,				          "max_value": 1000,
                "min_value": 0,					          "min_value": 0,
                "result_format": {				          "result_format": {
                  "result_format": "SUMMARY"			            "result_format": "SUMMARY"
                }						          }
              }							        }
            },							      },
            "result": {						      "result": {
              "observed_value": 0				        "observed_value": 0
            },							      },
            "exception_info": {					      "exception_info": {
              "raised_exception": false,			        "raised_exception": false,
              "exception_message": null,			        "exception_message": null,
              "exception_traceback": null			        "exception_traceback": null
            }							      }
          },							    },
          {							    {
            "meta": {},						      "meta": {},
            "success": true,					      "success": true,
            "expectation_config": {				      "expectation_config": {
              "expectation_type": "expect_table_column_count_	        "expectation_type": "expect_table_column_count_to_equ
              "meta": {						        "meta": {
                "BasicSuiteBuilderProfiler": {			          "BasicSuiteBuilderProfiler": {
                  "confidence": "very low"			            "confidence": "very low"
                }						          }
              },						        },
              "kwargs": {					        "kwargs": {
                "value": 6,					          "value": 6,
                "result_format": {				          "result_format": {
                  "result_format": "SUMMARY"			            "result_format": "SUMMARY"
                }						          }
              }							        }
            },							      },
            "result": {						      "result": {
              "observed_value": 6				        "observed_value": 6
            },							      },
            "exception_info": {					      "exception_info": {
              "raised_exception": false,			        "raised_exception": false,
              "exception_message": null,			        "exception_message": null,
              "exception_traceback": null			        "exception_traceback": null
            }							      }
          }							    }
        ],							  ],
        "statistics": {						  "statistics": {
          "evaluated_expectations": 2,				    "evaluated_expectations": 2,
          "successful_expectations": 2,				    "successful_expectations": 2,
          "unsuccessful_expectations": 0,			    "unsuccessful_expectations": 0,
          "success_percent": 100.0				    "success_percent": 100.0
        }							  }
      },						      <
      "actions_results": {				      <
        "openlineage": {				      <
          "class": "OpenlineageValidationAction"	      <
        }						      <
      }							      <
    }							      <
  }							      <
}								}
```

**Comment by mobuchowski** [comment]
@collado-mike should we close this?

**Comment by collado-mike** [comment]
Closing as we merged https://github.com/OpenLineage/OpenLineage/pull/234
