### ISSUE TITLE
[SPARK] The namespace of CreateDataSourceAsSelectCommands is always set to "file" when running on Hadoop / Hdfs

### ISSUE THREAD

**Issue by d-m-h** [OpenLineage/OpenLineage#2132]
## Context

We use Spark with YARN, running on Hadoop 2.x (I can't remember the exact minor version) with Hive support.

## Problem

I'm noticed that `CreateDataSourceAsSelectCommand` objects are always transformed to an `OutputDataset` with a namespace value set to "file" - which is curious, because the inputs always have a (correct) namespace of `hdfs://<name-node>`.

Running this: `cat events.log | jq '{eventTime: .eventTime, eventType: .eventType, runId: .run.runId, jobNamespace: .job.namespace, jobName: .job.name, outputs: .outputs[] | {namespace: .namespace, name: .name}, inputs: .inputs[] | {namespace: .namespace, name: .name}}'`

This is an output:

```json
{
  "eventTime": "2023-09-13T16:01:27.059Z",
  "eventType": "START",
  "runId": "bbbb5763-3615-46c0-95ca-1fc398c91d5d",
  "jobNamespace": "spark.cluster-1",
  "jobName": "ol_hadoop_test.execute_create_data_source_table_as_select_command.dhawes_db_ol_test_hadoop_tgt",
  "outputs": {
    "namespace": "file",
    "name": "/user/hive/warehouse/dhawes.db/ol_test_hadoop_tgt"
  },
  "inputs": {
    "namespace": "hdfs://nn1",
    "name": "/user/hive/warehouse/dhawes.db/ol_test_hadoop_src"
  }
}
```

**Comment by pawel-big-lebowski** [comment]
Looks like a problem in `io.openlineage.spark.agent.util.PathUtils#fromCatalogTable(org.apache.spark.sql.catalyst.catalog.CatalogTable)` method which in case of sub-call `io.openlineage.spark.agent.util.PathUtils#prepareDatasetIdentifierFromDefaultTablePath` always uses `DEFAULT_SCHEME`, even if warehouse location is on HDFS.

**Comment by d-m-h** [comment]
@pawel-big-lebowski - the snippet is the proposed future state, yes?

**Comment by pawel-big-lebowski** [comment]
@d-m-h yes, it removes URI -> String -> URI conversion.

**Comment by d-m-h** [comment]
Yes, I tested on our Hadoop cluster - and it looks like the "defaultTablePath()" method includes the "hdfs" scheme along with the name node in the URI.

Though, I want to do 1 more test and make the changes myself and ship the modified JAR to our cluster to test your proposed changes.
