### ISSUE TITLE
[PROPOSAL] Improve dbt local processor.

### ISSUE THREAD

**Issue by JDarDagran** [OpenLineage/OpenLineage#2215]
**Purpose:**
`DbtLocalArtifactProcessor` when loading `dbt_project.yaml` does two things that might be changed/improved:
1. it loads naively whole file when it may not need to use all values
2. uses only its own alternative of `env_var` dbt Jinja macro

**Proposed implementation**
For 1. - we could introduce sort of lazy loading values.
For 2. - when parsing events `macros` from `manifest.json` could be used to provide more context and increase ability to render

**Comment by tatiana** [comment]
Thanks a lot, @JDarDagran , this looks a great proposal!
This will make the openlineage library more reliable - avoiding issues like the ones we've seen in Cosmos - but overall.

**Comment by JDarDagran** [comment]
1. done
2. seems hard to maintain. I might reopen this whenever someone reports a need.
