### ISSUE TITLE
bug with parsing inputs from SnowflakeOperator

### ISSUE THREAD

**Issue by harels** [OpenLineage/OpenLineage#2222]
The following operators does not emit lineage as expected:
`braves = SnowflakeOperator(
    snowflake_conn_id="snowflake",
    sql="SELECT game_id, game_date FROM product_demo.demo.braves_2022_season",
    task_id="braves_select",
)`

The OL event that gets emitted does not contain any input datasets:
`'{"eventTime": "2023-10-31T22:52:39.597152+00:00", "eventType": "COMPLETE", "inputs": [], "job": {"facets": {"sql": {"_producer": "https://github.com/apache/airflow/tree/providers-openlineage/1.1.1", "_schemaURL": "https://raw.githubusercontent.com/OpenLineage/OpenLineage/main/spec/OpenLineage.json#/definitions/SqlJobFacet", "query": "SELECT game_id, game_date FROM product_demo.demo.braves_2022_season"}}, "name": "snowflake_dag.braves_select", "namespace": "earthbound-antenna-1723"}, "outputs": [], "producer": "https://github.com/apache/airflow/tree/providers-openlineage/1.1.1", "run": {"facets": {}, "runId": "74f578f9-65d6-3a9a-a32f-d27aa3d98a0c"}, "schemaURL": "https://openlineage.io/spec/1-0-5/OpenLineage.json#/definitions/RunEvent"}'`
Using the airflow openlineage provider, version 1.1.1.

**Comment by JDarDagran** [comment]
This issue should land in Airflow repo. Btw it got fixed in https://github.com/apache/airflow/pull/35428
