### ISSUE TITLE
openlineage python client KafkaTransport Error

### ISSUE THREAD

**Issue by berezhinskiyo** [OpenLineage/OpenLineage#2225]
There is an error while creating  kafka.Producer `self.producer = kafka.Producer({**added_config, **config})` it should be replaced with `self.producer = kafka.Producer( **config)`. Unfortunately, I don't know how to add added_config.

In last version of openlineage python client appears exception `cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "config""}`

**Comment by JDarDagran** [comment]
Could you please post your config? You may/should hide sensitive data.

**Comment by JDarDagran** [comment]
@berezhinskiyo  did you happen to fix the error?

**Comment by kacpermuda** [comment]
Closing this as stale. Feel free to reopen if needed.
