### ISSUE TITLE
Column level lineage is  not captured for databricks merge statements

### ISSUE THREAD

**Issue by uday1409** [OpenLineage/OpenLineage#2254]
I have observed that column level lineage is not being captured for databricks delta merge. I believe it has to do with difference in implementation of delta commands in databricks. Could you check and confirm. Attaching query and the generated plan.

[execplan.txt](https://github.com/OpenLineage/OpenLineage/files/13336433/execplan.txt)
[SampleQueryWithNestedWindowFunction.txt](https://github.com/OpenLineage/OpenLineage/files/13336434/SampleQueryWithNestedWindowFunction.txt)

**Comment by rodrigo-maia-manta** [comment]
same issue. no input neither output

**Comment by pawel-big-lebowski** [comment]
https://github.com/OpenLineage/OpenLineage/pull/2348 this has been merged recently

**Comment by kacpermuda** [comment]
Should we close this issue as resolved?
