### ISSUE TITLE
Dataset name should not be en empty string in Java client

### ISSUE THREAD

**Issue by kacpermuda** [OpenLineage/OpenLineage#2264]
## Description
When creating a DatasetIdentifier object [here](https://github.com/OpenLineage/OpenLineage/blob/bfd0de04e68c5f092d37f67261ad4698fcab3066/client/java/src/main/java/io/openlineage/client/utils/DatasetIdentifierUtils.java#L30), name of the dataset is stripped of all slashes by the following code:
https://github.com/OpenLineage/OpenLineage/blob/bfd0de04e68c5f092d37f67261ad4698fcab3066/client/java/src/main/java/io/openlineage/client/utils/DatasetIdentifierUtils.java#L35-L39

If the result of `uri.getPath()` is a single slash `/`, the resulting dataset name will be empty string. This can lead to some issues as some services accepting OL events can not handle empty string as dataset name. F.e. [Marquez](https://marquezproject.ai/) is unusable after and event with empty dataset name, as it loads indefinitely. I believe it can be an issue with other providers as well.
![image](https://github.com/OpenLineage/OpenLineage/assets/98873404/43064ee1-c78f-4bc3-86be-1a3381fdf160)

## Proposal
I believe we should modify the way we parse paths so that if a single slash is passed, it remains as is. Consequently, this would alter Datasets that currently have an empty name to be named "/" instead.

F.e. 
```
String path = uri.getPath();
String name = path.equals("/") ? path :
              Optional.of(path)
                      .map(DatasetIdentifierUtils::removeLastSlash)
                      .map(DatasetIdentifierUtils::removeFirstSlashIfSingleSlashInString)
                      .get();
```

However, we should probably extend this code to something like this:
```
String path = uri.getPath();
String name = (path.equals("/") || path.isEmpty()) ? path :
              Optional.of(path)
                      .map(DatasetIdentifierUtils::removeLastSlash)
                      .map(DatasetIdentifierUtils::removeFirstSlashIfSingleSlashInString)
                      .get();
```
so that we can cover cases, when a `getPath()` result is an empty string, not a single slash. I believe this can happen f.e. with an URI like this: `gs://bucket/`.

**Comment by mobuchowski** [comment]
This makes sense 👍
