### ISSUE TITLE
[PROPOSAL] Make the openlineage integrations compatible with 1.8 JDK

### ISSUE THREAD

**Issue by athityakumar** [OpenLineage/OpenLineage#2274]
**Purpose:**

Currently, the OpenLineage Flink integration is configured to work with Java 11 as per the [build.gradle](https://github.com/OpenLineage/OpenLineage/blob/main/integration/flink/build.gradle#L50) - however we could have folks using/extending from versions like JDK 1.8 onwards.

If we configure our integration to be JDK 1.8, it'd also work for customers using Java 11; but the other way around (OL using Java 11 & customers using < 11) wouldn't work due to backward incompatibility.

**Proposed implementation**

- Configure Java version to 1.8 by default in build.gradle files
- Replace any Java 11 specific feature/logic to it's JDK 1.8 equivalent

**Comment by mobuchowski** [comment]
Flink dropped support for Java 8 in 1.15, we're following Flink in that regard.
