### ISSUE TITLE
[INTEGRATION] Add DBT integration with dbt-athena-community adapter

### ISSUE THREAD

**Issue by sanromeo** [OpenLineage/OpenLineage#2288]
### What is the target system?

dbt-athena-community adapter

### What kind of integration is this?

- [ ] Produces OpenLineage metadata
- [ ] Consumes OpenLineage metadata
- [ ] Something else

### How should this integration be implemented?

Integrate the `dbt-athena-community` adapter with OpenLineage, enabling Athena to produce and share lineage metadata. [link to adapter](https://github.com/dbt-athena/dbt-athena)
I'm wanna be able to use openlineage metadata in [Cosmos](https://github.com/astronomer/astronomer-cosmos) for generating outlets from dbt lineage, but it requires integration with `dbt-athena-adapter` in OpenLineage.

### Where should this integration be implemented?

- [ ] In the target system
- [X] In the OpenLineage repo
- [ ] Somewhere else

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

**Comment by svdimchenko** [comment]
@sanromeo could you clarify how dbt-athena-community's dbt metadata differs from other dbt adapters ? What error do you get?

**Comment by moritzsanne** [comment]
I am also trying to get this to work and am interesting in contributing but need need help understanding if this is this needs to be fixed in dbt-athena, cosmos or OpenLineage. 

Any new findings since you opened this, @sanromeo?
