### ISSUE TITLE
Is OpenLineage support airflow version 2.5.2 ?

### ISSUE THREAD

**Issue by itscarill** [OpenLineage/OpenLineage#2299]
Currently im validating OpenLineage with marquez to see the functionality of data lineage with airflow version 2.5.2

But I keep having issue as per stated below

airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "backend" key in "lineage" section. Current value: "'openlineage.lineage_backend.OpenLineageBackend'".

I've installed related library as per below
airflow@f0126ff41da9:~$ pip list|grep -i openlineage
openlineage-airflow                      1.5.0
openlineage-integration-common           1.5.0
openlineage-python                       1.5.0
openlineage_sql                          1.5.0

I've define my environment like below

    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AIRFLOW_DAGS=/home/airflow/airflow/dags
      - AIRFLOW__LINEAGE__BACKEND='openlineage.lineage_backend.OpenLineageBackend'
      - MARQUEZ_URL=http://marquez-web:3000
      - OPENLINEAGE_URL=http://marquez-api:5000
      - OPENLINEAGE_NAMESPACE=lineageman

im referring to this repo as reference https://github.com/OpenLineage/workshops/tree/main/airflow

Anyone can point out wht did I do wrong to fix this? It would be much appreciated

**Comment by itscarill** [comment]
Okeh, noted with thanks @JDarDagran 

Just a quick check, apart from above.. is there any additional variables required to be define?

Also my airflow are not using celery, I guess that shouldn't be a prerequisite for OpenLineage right

**Comment by JDarDagran** [comment]
@itscarill sorry, I missed your message. No additional variables should be required. Celery is also not required.

Please let me know if you need further help.
