### ISSUE TITLE
Questions on Spec 

### ISSUE THREAD

**Issue by mandy-chessell** [OpenLineage/OpenLineage#231]
I have been working through the JSON version of the spec and I want to be sure I am understanding it correctly.

* The examples on this page https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.md show a files called "transition" that contains the enum for "START", "COMPLETE".  However in the spec it seems to be called "eventType". Which is right? Am I misreading the spec?

* The DataSet facet is included in InputDataSet and OutputDataSet.  None of these include BasicFacet.  Is that intended? DataSet has dataSource that identifies the actual data set.  The question is whether the over all schema of these types needs to be versioned?

For interest, here is the picture of the open metadata structure I created for the Egeria community.  Bold means mandatory ...
![image](https://user-images.githubusercontent.com/12354195/131315364-7830659b-6250-4e97-83df-2d2d958469d9.png)

**Comment by julienledem** [comment]
> The examples on this page https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.md show a files called "transition" that contains the enum for "START", "COMPLETE". However in the spec it seems to be called "eventType". Which is right? Am I misreading the spec?
The JSONSchema spec is correct. This field was renamed from `transition` to `eventType`. I'll update the README to be consistent. Thanks for pointing it out

**Comment by julienledem** [comment]
> The DataSet facet is included in InputDataSet and OutputDataSet. None of these include BasicFacet. Is that intended? DataSet has dataSource that identifies the actual data set. The question is whether the over all schema of these types needs to be versioned?

Looking at your picture I think there's a slight disconnect in the level of nestings in the definition of datasets.
`allOf` in JSONSchema means it matches all of the schema. In the Java code generation we map that to an inheritance.

Here is an abbreviated definition of the Dataset and Input Dataset types.
Dataset:
```js
    "Dataset": {
      "type": "object",
      "properties": {
        "namespace": { "type": "string" },
        "name": { "type": "string"},
        "facets": {
          "type": "object",
          "properties": {
            "documentation": { "$ref": "#/definitions/DocumentationDatasetFacet" },
            "schema": {  "$ref": "#/definitions/SchemaDatasetFacet"  },
            "dataSource": {  "$ref": "#/definitions/DatasourceDatasetFacet" }
          },
          "additionalProperties": { "$ref": "#/definitions/CustomFacet" }
        }
      }
    } 
```
Dataset looks like:
```js
{ 
  namespace: ""
  name:
  facets: {}
}
```

InputDataset:
```js
  "InputDataset": {
      "allOf": [
        { "$ref": "#/definitions/Dataset" },
        {
          "type": "object",
          "properties": {
            "inputFacets": {
              "properties": {
                "dataQualityMetrics" : {  "$ref": "#/definitions/DataQualityMetricsInputDatasetFacet" }
              },
              "additionalProperties": { "$ref": "#/definitions/CustomFacet" }
            }
          }
        }
      ]
    }
```
InputDataset looks like:
```js
{ 
  namespace: ""
  name:
  facets: {}
  inputFacets: {}
}
```
So an InputDataset is a Dataset with the additional InputFacets field.

Does that clear up the question?

**Comment by julienledem** [comment]
I addressed your first question at https://github.com/OpenLineage/OpenLineage/pull/241

**Comment by mandy-chessell** [comment]
Thank you for your help :)

**Comment by mandy-chessell** [comment]
Updated picture:
![image](https://user-images.githubusercontent.com/12354195/131965937-831885c9-d193-41af-b6fb-3c67aebf5cdc.png)
