### ISSUE TITLE
Spark column level lineage is not captured for subqueries with window functions.

### ISSUE THREAD

**Issue by uday1409** [OpenLineage/OpenLineage#2469]
We observed that when there are nested queries along with window functions involved, attribute dependency not properly tracked. For example, avg_monthly_purhcase dependency should point to customer_id and purchase_amount but the link is completely broken. Attaching test queries and generated plan.

[openlineageplan.txt](https://github.com/OpenLineage/OpenLineage/files/14397087/openlineageplan.txt)
[SampleQueryWithNestedWindowFunction (1).txt](https://github.com/OpenLineage/OpenLineage/files/14413345/SampleQueryWithNestedWindowFunction.1.txt)

**Comment by uday1409** [comment]
Update query, I also dont see inputs either. I have used 1.8 version and ran in Databricks

**Comment by pawel-big-lebowski** [comment]
hi @uday1409, I am involved in other issues. Would you be willing to investigate it and solve this?
