### ISSUE TITLE
`HttpTransport` timeout unit unclear

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#2474]
In the `HttpTransport`, the docs specify `millis` as the unit, see [`HttpTransport.withTimeout(Double)`](https://github.com/OpenLineage/OpenLineage/blob/main/client/java/src/main/java/io/openlineage/client/transports/HttpTransport.java#L53), but if the timeout is overwritten, the client multiples the timeout * `1000`:

```
private static CloseableHttpClient withTimeout(Double timeout) {
    int timeoutMs;
    if (timeout == null) {
      timeoutMs = 5000;
    } else {
      timeoutMs = (int) (timeout * 1000);
    }
...
```

* Why do we use `double`, not `int`?
* If a user passes `2000`, the timeout would be (based on the above) `2000` * `1000` = `2000000`

**Comment by mobuchowski** [comment]
>Why do we use double, not int?

I think that's the artifact of originally doing this for Python, [where requests library accepts float as timeout parameter.](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts)
