### ISSUE TITLE
release: make Java release jobs fully depend on build jobs to _not_ break release each time something changes in build job

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#2522]
Common failure mode in release is:
- something changes in one of the integrations, for example SQL parser is added
- build CI job or integration test CI job needs to be adjusted for it to pass tests and be merged to main
- release job is not adjusted, and fails with the same error, but on release, leaving release broken.

To fix that, release job must not rebuild the final jar, but depend on build job to prepare it. 

Build jobs must be the only ones to create jar, the other jobs must use it directly. The Java jobs should use the same Java version.

**Comment by mobuchowski** [comment]
https://github.com/OpenLineage/OpenLineage/pull/2788

**Comment by mobuchowski** [comment]
Done two large rebases one by one. 

Simplified code by removing duplication on Scala versions.

**Comment by tatiana** [comment]
We're aiming to release OL 1.20 with the automated process proposed by Maciej

**Comment by mobuchowski** [comment]
Release 1.20.4 done with new workflow.
