### ISSUE TITLE
Flink integration - incorrect dependency required by a published Jar

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#2527]
We are still exepiencing a problem of having gradle dependencies to a submodules within `openlineage-flink.jar`, which are shipped within the main jar and not released. 

This can be observed within the file:
 https://repo1.maven.org/maven2/io/openlineage/openlineage-flink/1.10.2/openlineage-flink-1.10.2.module 

```
"dependencies": [
        {
          "group": "openlineage-flink",
          "module": "app",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.openlineage.flink",
          "module": "shared",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.openlineage.flink",
          "module": "flink115",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.openlineage.flink",
          "module": "flink117",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "io.openlineage.flink",
          "module": "flink118",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
```

A workaround for this is to ignore gradle metadata which can be done within `build.gradle` with:
```
mavenCentral() {
        metadataSources {
            mavenPom()
            artifact()
            ignoreGradleMetadataRedirection()
        }
    }
```

I don't think it's a common problem as users may just add an existing `openlineage-flink.jar` into the class path on their clusters. It is however affecting Flink applications which are built with with integration jar packed into it. 

I would appreciate any hint on how to resolve the problem. 
Any idea @d-m-h ?

**Comment by d-m-h** [comment]
The Spark integration suffered from this problem as well. That's why I assume that there is manual `pom.xml` manipulation in the publishing step of the project.

```groovy
          pom.withXml {
              asNode().dependencies."*".findAll() {
                  it.groupId.text() == "spark"
              }.each() {
                  it.parent().remove(it)
              }
          }
```

In Flink's case, you can change the predicate to `it.groupId.text() == "io.openlineage.flink"`

**Comment by pawel-big-lebowski** [comment]
I've done that before and removed all the dependencies -> https://github.com/OpenLineage/OpenLineage/blob/main/integration/flink/build.gradle#L129

And the pom file is clear. I see that spark publish step does not produce `module` files

<img width="622" alt="Screenshot 2024-03-18 at 14 02 20" src="https://github.com/OpenLineage/OpenLineage/assets/1646950/d0490838-ac48-4b86-92f3-284498940545">

which for some reason are present for Flink. This may be the thing.

**Comment by HuangZhenQiu** [comment]
@d-m-h @pawel-big-lebowski 
Any other insight on this issue?

**Comment by d-m-h** [comment]
@HuangZhenQiu - can we close this issue after the merge?
