### ISSUE TITLE
[PROPOSAL] Consider using uuid7 instead of uuid4 for runId

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2541]
**Purpose:**

uuid4 values have only `random_part`, so values are randomly distributed. This messes up with database indexes (e.g. primary keys) because B-Tree indexes are designed for comparable values, but here random prefix is compared with another random prefix. This also messes up with partitioning, just the same reason - where is no correlation between uuid value and position it should be inserted. More details can be found in [RFC](https://datatracker.ietf.org/doc/draft-ietf-uuidrev-rfc4122bis/).

uuidv7 values are `timestamp` + `random_part` based, which fixes the issue with database indexes and partitioning because values can be properly sorted and compared. The proposal is to replace all occurrences of uuid4 with uuid7 in the source code, and also recommend to use new uuid version for third-party implementations of specification.

For now, there are no builtin implementations for Python and Java. There are several open source ones though:
* https://pypi.org/project/uuid6/
* https://github.com/aminalaee/uuid-utils
* https://github.com/cowtowncoder/java-uuid-generator
* https://github.com/f4b6a3/uuid-creator

**Proposed implementation**

**Comment by mobuchowski** [comment]
We are also using uuid3 in Airflow integration, where we need to generate deterministic run ids, because we're not storing it between START/COMPLETE events

**Comment by dolfinus** [comment]
I see. So the issue with primary key order/partitioning still may be present, if Airflow integration is used.

**Comment by dolfinus** [comment]
Using UUID with time component at the begging allows use partitioned tables on OL consumer side, e.g.
```sql
CREATE TABLE run_events (
  id UUID PRIMARY KEY,
  job VARCHAR, 
  parent_id UUID REFERENCES run_events(id),
  ...
)
PARTITION BY RANGE(extract_timestamp_from_uuid(id))
```
So filter using specific runId will search only in a partition of a table containing values for timestamp it was generated.

For uuid4 additional field is required:
```sql
CREATE TABLE run_events (
  id UUID NOT NULL, 
  created_at TIMESTAMP NOT NULL,
  ended_at TIMESTAMP,
  parent_id UUID,
  ...
)
PARTITION BY RANGE (created_at)
```
and all the queries should filter values by `created_at` to avoid scan of all partitions.

**Comment by dolfinus** [comment]
> UUID can be constructed using raw bytes

Here is an example

```bash
pip install uuid6
```

```python
from uuid6 import UUID
from datetime import datetime
from hashlib import sha1

event_time = "2024-05-07T17:10:51.548Z"
# DagRun/TaskInstance
run = "namespace.dag.dag_run_id"

// get time component from event timestamp, in milliseconds
timestamp_ms = int(datetime.fromisoformat(event_time).timestamp() * 1000)

# get rest of bytes using hash
digest = sha1(run.encode("utf-8")).digest()
rest = int.from_bytes(digest)

uuid_int = (timestamp_ms & 0xFFFFFFFFFFFF) << 80
uuid_int |= (rest >> 86)
uuid = UUID(int=uuid_int, version=7)
# UUID('018f5409-5f9c-71e6-ac71-ec94dca1ed29')
assert uuid.time == timestamp_ms
```

**Comment by dolfinus** [comment]
https://github.com/OpenLineage/OpenLineage/pull/2686#issuecomment-2106816316

> What are the pros of monotonically increasing values of UUIDs?
> The events already contain eventTime field which can be used by backend applications.

Here is my case. I'm building OL consumer which reads runEvents from Kafka and then writes it to a bunch of tables in Postgres. Tables are partitioned by creation date:
```sql
CREATE TABLE runs (
  id UUID NOT NULL,
  parent_id UUID NULL,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ NULL,
  status VARCHAR(10) NOT NULL,
  data JSONB
)
PARTITIONED BY RANGE (started_at)
```

This avoids slowing down INSERT & SELECT queries because of a large table, and also allows deleting old lineage data (e.g. after few months) by dropping the entire partition.

But there is a drawback - I have to include partitioning key in queries to avoid scanning all partitions for the data I need:
```sql
SELECT *
FROM runs
WHERE id = 'some'::uuid AND started_at BETWEEN $actual_start AND now()
```
But runEvent with `eventType=COMPLETE` I have only timestamp of the current event (for my case it is `ended_at`), and there is no timestamp of previous event (`created_at`). So `UPDATE runs SET status='COMPLETE' WHERE id = 'some'::uuid` leads to scanning all partitions of a table.

Using UUIDv7 already stores a timestamp of event creation, so I can use queries like `UPDATE runs SET status='COMPLETE' WHERE id = 'some'::uuid AND started_at = uuidv7_to_timestampz('some'::uuid)`, leading to index scan on just specific partition.


Another advantage is better index locality - for UUIDv7 row position is directly correlated with index position, because UUIDv7 values are monotonically increasing (instead of random for UUIDv4). This reduces B-tree index bloat, and speeds up both SELECT and INSERT queries. I mean, a lot:

UUIDv4
<details>

```sql
CREATE TABLE runs_uuidv4 (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ NULL
);

\timing

-- Insert 45M rows
WITH data AS NOT MATERIALIZED (
  SELECT
    '2024-01-01 00:00:00'::TIMESTAMPTZ + dates.val * interval '1 day' + random() * interval '1 day' AS run_started
  -- create runs for last 3 months
  FROM generate_series(0, 90) AS dates(val)
  -- but randomly distributed across each day
  JOIN generate_series(0, 1000000) AS per_day(val) ON random()::int = 0
)
INSERT INTO runs_uuidv4 (started_at, ended_at)
SELECT data.run_started, data.run_started + (random() * interval '1 day')
FROM data
ORDER BY data.run_started;
ANALYZE runs_uuidv4;

--INSERT 0 45504011
--Time: 1195037.129 ms (19:55.037)

\di+ runs_uuidv4_pkey
-- 1766Mb

explain (analyze, buffers) select * from runs_uuidv4 where id = '3e639304-4ca9-4be2-aa5a-f5d9450e8b4c'::uuid;
                                                          QUERY PLAN                                                           
-------------------------------------------------------------------------------------------------------------------------------
 Index Scan using runs_uuidv4_pkey on runs_uuidv4  (cost=0.56..8.58 rows=1 width=32) (actual time=1.013..1.018 rows=1 loops=1)
   Index Cond: (id = '3e639304-4ca9-4be2-aa5a-f5d9450e8b4c'::uuid)
   Buffers: shared read=5
 Planning Time: 0.138 ms
 Execution Time: 1.088 ms
(5 rows)

Time: 10.942 ms
```
</details>

UUIDv7
<details>

```sql
CREATE TABLE runs_uuidv7 (
  id UUID DEFAULT uuid_generate_v7() PRIMARY KEY,
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ NULL
);


\timing

-- Insert 45M rows
WITH data AS NOT MATERIALIZED (
  SELECT
    '2024-01-01 00:00:00'::TIMESTAMPTZ + dates.val * interval '1 day' + random() * interval '1 day' AS run_started
  -- create runs for last 3 months
  FROM generate_series(0, 90) AS dates(val)
  -- but randomly distributed across each day
  JOIN generate_series(0, 100000) AS per_day(val) ON random()::int = 0
)
INSERT INTO runs_uuidv7 (id, started_at, ended_at)
SELECT uuid_timestamptz_to_v7(data.run_started), data.run_started, data.run_started + (random() * interval '1 day')
FROM data
ORDER BY data.run_started;
ANALYZE runs_uuidv7;

--INSERT 0 4550386
--Time: 19187.405 ms (00:19.187)

\di+ runs_uuidv7_pkey
-- 137Mb

explain (analyze, buffers) select * from runs_uuidv7 where id = '018e227e-ea8d-7f86-816d-26319c9d8a5d'::uuid;
                                                          QUERY PLAN                                                           
-------------------------------------------------------------------------------------------------------------------------------
 Index Scan using runs_uuidv7_pkey on runs_uuidv7  (cost=0.43..8.45 rows=1 width=32) (actual time=0.021..0.023 rows=1 loops=1)
   Index Cond: (id = '018e227e-ea8d-7f86-816d-26319c9d8a5d'::uuid)
   Buffers: shared hit=4
 Planning Time: 0.084 ms
 Execution Time: 0.047 ms
(5 rows)

Time: 0.433 ms
```
</details>

I mean, the difference in size and queries timing is about 10x or even more. Of course, this is just a benchmark, not a real load.

> The cons are:
>  1. we're adding dependency to a library (com.github.f4b6a3) and it's not clear if it is supported nor maintained by any organisation.
>  2. we're adding unclear assumption on monotonically increasing ids that consumer can depend on and which can get broken in future.

1. You're right. But UUID generation is quite simple, it can be vendored to OL client itself (see Python implementation as an example, its just few lines of code).
2. It can be mentioned in documentation that UUID type is not someone should rely on, and can be client specific. But there can be recommendation use UUIDv7 because of pros mentioned above.

**Comment by dolfinus** [comment]
Thanks!
