### ISSUE TITLE
[CI] Passing -Pspark.version to gradle still runs tests for all Spark versions

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2567]
For example, tests are executed in parallel CI jobs with options `-Pspark.version=2.4.8` and `-Pspark.version=3.2.4`. But both of jobs execute `:spark2:tests`, `:spark32:tests`, `:spark34:tests` and so on:
* https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/9954/workflows/1cadbd7c-4acd-4eca-8292-25c5247c1d46/jobs/197776/parallel-runs/0/steps/0-106
* https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/9954/workflows/1cadbd7c-4acd-4eca-8292-25c5247c1d46/jobs/197781/parallel-runs/0/steps/0-106

Can Gradle or CI config can be changed to run tests only for specific Spark version? This can speed up the tests.

Somewhat related - each run of tests in CI also runs [linter](https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/9954/workflows/1cadbd7c-4acd-4eca-8292-25c5247c1d46/jobs/197776/parallel-runs/0/steps/0-108) which apparently does not depend on Spark version, so it can be run just once.

**Comment by pawel-big-lebowski** [comment]
The logic Maciej describes comes from builder classes like (this one)[https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/app/src/main/java/io/openlineage/spark/agent/lifecycle/Spark34DatasetBuilderFactory.java]

In this particular case, spark34 builder factory has following imports:
```
import io.openlineage.spark32.agent.lifecycle.plan.AlterTableCommandDatasetBuilder;
import io.openlineage.spark33.agent.lifecycle.plan.ReplaceIcebergDataDatasetBuilder;
import io.openlineage.spark34.agent.lifecycle.plan.column.CreateReplaceInputDatasetBuilder;
import io.openlineage.spark35.agent.lifecycle.plan.CreateReplaceOutputDatasetBuilder;
```

I don't think it is doable to have dependency logic replicated in CI and consistent with `DatasetBuilderFactory` classes.

**Comment by dolfinus** [comment]
I see.

I've tried to run `./gradlew :spark2:tests` specifically, and it took only 23 seconds. So making CI to run only tests for some specific Spark version actually will not speed up tests much.

Don't mind if I close the issue?
