### ISSUE TITLE
[PROPOSAL] Collect detailed info about Spark job and application

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2589]
**Purpose:**

Currently events produced by OpenLineage integration for Spark are using command names:
![Снимок экрана_20240408_112613](https://github.com/OpenLineage/OpenLineage/assets/4661021/01919f99-d11b-48d1-bb33-434bbba5183c)

With `spark.openlineage.jobName.appendDatasetName:false`:
![Снимок экрана_20240408_112138](https://github.com/OpenLineage/OpenLineage/assets/4661021/da2aeeac-8484-4516-87bd-17a2fd662dc4)

But in SparkUI jobs have different names:
![Снимок экрана_20240408_112111](https://github.com/OpenLineage/OpenLineage/assets/4661021/c099a22c-bacf-4397-b4b1-acceb5bea2c5)

How user can track that some job in SparkUI is corresponding to OpenLineage run event?
Especially when user set custom job description using `spark.sparkContext.setJobDescription` or `spark.sparkContext.setJobGroup`:
![изображение](https://github.com/OpenLineage/OpenLineage/assets/4661021/2d50ebe0-2a05-46f6-b9f1-f8d07372246e)

**Proposed implementation**

My proposal is to add new option for OpenLineage Spark integation, e.g.:
```
spark.openlineage.jobName.useSparkName: true
```

Setting this option to `true` will use Spark job description as a source for OpenLineage job names.

Another way is to add Spark jobId (0, 1, 2, 3 on screenshots above) as prefix for OpenLineage job name.

**Comment by pawel-big-lebowski** [comment]
If tracking is a problem, one can add Spark dedicated facet to contain: jobId and job group and job description to correlate the events with Spark UI. A link to Spark job history server would be also cool to have. 

What would spark job name look like? Screenshots attached show job descriptions.

**Comment by dolfinus** [comment]
> What would spark job name look like?

I mean job description, sorry.

Regarding a dedicated facet for job information, that sounds nice.

**Comment by dolfinus** [comment]
My proposal is:
* Add `processing_engine`, `spark_properties` and `environment-properties` facets to Spark application events. Currently these facets are populated only for Spark job events, but they are usually the same for the entire application (especially `processing_engine`).

* Add following properties to `spark_properties` facet:
* * `spark.app.id` - applicationId in Yarn
* * `spark.submit.deployMode` - `client` or `cluster`
* * `spark.driver.host` - where driver is started
* * `spark.driver.appUIAddress` - e.g. `http://driver.host:43452` of SparkUI, served by driver
* * `spark.org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter.param.PROXY_URI_BASES` - URL of Yarn proxy for SparkUI, e.g. `http://yarn.host:8088/proxy/applicationId`
* * `spark.yarn.historyServer.address` - e.g. `history.server.host:18081`, address of Spark History server UI, can be used to build URL to showing the same interface as SparkUI, but for Spark application which is already stopped.
* * `spark.ui.reverseProxyUrl` - URL for reverse proxy SparkUI is served behind, like Kubernetes ingress.
* * `spark.user` - save here result of calling `spark.sparkContext.sparkUser()`, this is a name of user started the Spark session.

    It's up to user which values he is interested in, because there are a lot of combinations how Spark can be deployed (local, Yarn, K8S, spark-submit with REST API, Spark Connect).

    Probably these values should be set only for Spark application event, mostly to reduce size of Spark job runEvent, and also because these values cannot be changed in runtime.

* Add new `spark_job` facet for Spark job runs with values:
* * `jobId: int` - from `SparkListenerJobStart.jobId()`
* * `jobCallSite: string` - from `SparkListenerJobStart.properties().get("callSite.short")`
* * `jobGroup: string` - from `SparkListenerJobStart.properties().get("spark.jobGroup.id")`
* * `jobDescription: string` - from `SparkListenerJobStart.properties().get("spark.job.description")`

    This allows users to match RunEvent with specific jobId.

    Here are examples of `SparkListenerJobStart.properties()`:
    ```json
    {
        "spark.sql.execution.id": "5",
        "spark.jobGroup.id": "group",
        "spark.job.interruptOnCancel": "false",
        "callSite.short": "collect at /tmp/ipykernel_30402/148600433.py:2",
        "spark.job.description": "description",
        "spark.rdd.scope.noOverride": "true",
        "spark.rdd.scope": "{\"id\":\"56\",\"name\":\"collect\"}"
    }
    ```

    ```json
    {
        "spark.rdd.scope.noOverride": "true",
        "spark.rdd.scope": "{\"id\":\"96\",\"name\":\"collect\"}",
        "callSite.short": "collect at /tmp/ipykernel_30402/3405814930.py:2",
        "spark.job.interruptOnCancel": "false",
        "spark.sql.execution.id": "9"
    }
    ```

* Drop `spark_version` facet as it is deprecated since 1.4.0

**Comment by dolfinus** [comment]
#2641 introduces a similar idea for `spark.app.id`/`spark.app.name`

**Comment by dolfinus** [comment]
Actually, now I think that adding all the described properties to `SparkPropertiesFacet` defaults is quite messy. It's probably better to move these options to another facet, and made them more user friendly:

* `uiUrl: string | null` - URL of either Spark Master or Spark driver. It can be null if `spark.ui.enabled` is `false`.
* `proxyUrl: string | null` - URL of Spark driver if it is served behind a reverse proxy, or YarnUI proxy, if any.
* `historyUrl: string | null` - URL of Spark history server, if any.
* `userName: string` - `spark.sparkContext.sparkUser()`

Currently `sparkDeployMode` is a part of `debug` facet. But I'm not sure if properties above should be filled up only if debug is enabled, as it can produce quite large JSON items.

**Comment by mobuchowski** [comment]
>But I'm not sure if properties above should be filled up only if debug is enabled, because this helps with investigating "who started a session which dropped up a table", "where can I find the logs of this application", and so on.

> Also debug facet contains plan details, OL config and metrics values, so it can be too much to send on just every event.

I agree with both points - if we want to add additional debug information to general event - without debug facet being enabled - we'd need to do this in a way that does introduce information that's limited in size.
