### ISSUE TITLE
[PROPOSAL] Using gzip for HTTP request body

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2595]
**Purpose:**

Currently HTTP request body is just plain JSON values, send to API without any compression. For example, this is one of events send by Spark integration: [event.json](https://github.com/OpenLineage/OpenLineage/files/14934779/event.json)

This is 3.8Kb of raw data. But using gzip, it can be compressed to just 861 bytes [event.json.gz](https://github.com/OpenLineage/OpenLineage/files/14934778/event.json.gz)

**Proposed implementation**

For Java client, wrap `HTTPEntity` with [GzipCompressingEntity](https://www.javadoc.io/doc/org.apache.httpcomponents/httpclient/4.5.2/org/apache/http/client/entity/GzipCompressingEntity.html) to automatically compress body to gzip while sending a request.
For Python client this is as simple as using [builtin zlib module](https://stackoverflow.com/a/38866506/23601543)

To avoid breaking backward compatibility, this can be enabled using HTTPTransport configuration, like:
```yml
transport:
  type: http
  url: http://localhost:5000
  compression: gzip  # deflate, null, etc
```

**Comment by mobuchowski** [comment]
In past jobs I've also seen https://github.com/facebook/zstd used very successfully for similar tasks. Advantage for zlib/gzip is just that it's buildin for Java and Python.

I think adding compression as opt-in mechanism is definitely a good idea - especially we see really some repeated data in the events.

**Comment by dolfinus** [comment]
Just tried zstd, with default compression level 3 it produces file with size 894 bytes, with level compression level 19 it is 860 bytes. So not a much difference, although I've tested file with quite a small file (Airflow task events contains much more data).

**Comment by mobuchowski** [comment]
Yeah, might be not worth the effort for small jsons.

**Comment by dolfinus** [comment]
Here are Python #2604 and Java implementations #2603. Checked on Marquez, it can handle requests with gzipped content.

I haven't added compression to Proxy because it is implemented in third-party package [Jersey](https://javadoc.io/static/org.glassfish.jersey.bundles/jaxrs-ri/2.35/org/glassfish/jersey/message/GZipEncoder.html).

**Comment by dolfinus** [comment]
Documentation: https://github.com/OpenLineage/docs/pull/318
