### ISSUE TITLE
[PROPOSAL] Host updated Airflow constraints files in OL repo to solve MWAA constraints problem

### ISSUE THREAD

**Issue by kacpermuda** [OpenLineage/OpenLineage#2612]
## Purpose:
The problem with MWAA is that if not specified otherwise, [by default](https://docs.aws.amazon.com/mwaa/latest/userguide/best-practices-dependencies.html#best-practices-dependencies-different-ways), it uses constraint files from [Airflow](https://docs.aws.amazon.com/mwaa/latest/userguide/create-environment.html#create-environment-regions-aa-versions) which means that:
- for MWAA 2.7.2 (Airflow 2.7.2, Python3.11 ) the OL provider is [bound to ==1.1.0](https://raw.githubusercontent.com/apache/airflow/constraints-2.7.2/constraints-3.11.txt)
- for MWAA 2.8.1 (Airflow 2.8.1, Python3.11 ) the OL provider is [bound to ==1.4.0](https://raw.githubusercontent.com/apache/airflow/constraints-2.8.1/constraints-3.11.txt)

So whenever you are putting just `apache-airflow-providers-openlineage` in the requirements.txt for the MWAA - it uses that version specified in the constraints file. 
However, if you put a different version f.e. `apache-airflow-providers-openlineage==1.5.0` there is a mismatch (two different versions of the same package are requested), an error is raised and no package is installed.

What one can do, is remove the constraint file by putting `--constraint /dev/null` as the first line of the requirements.txt file. Alternatively, one could modify those standard Airflow constraints (as they are publicly available) by changing the OpenLineage provider version, host it somewhere and then point to that file f.e. by putting this as a first line in `requirements.txt`:

> --constraint "https://somedomain.com/constraints-2.8.1/constraints-3.11.txt"

## Proposed implementation
Maybe we could put some step in the CI, that will prepare a copy of all Airflow constraint files and update the OL version to the latest version we know works fine and put that files in OL repo? This could be helpful for the MWAA users willing ot use latest OL features and fixes but not being able to remove the constraints files. 

## Thoughts
1.  I don’t think there is a way to change the MWAA behaviour, as it’s not some bug or issue but the desired behaviour introduced by them [recently](https://docs.aws.amazon.com/mwaa/latest/userguide/best-practices-dependencies.html#best-practices-dependencies-different-ways):

> Beginning with Apache Airflow v2.7.2, your requirements file must include a --constraint statement. If you do not provide a constraint, Amazon MWAA will specify one for you to ensure the packages listed in your requirements are compatible with the version of Apache Airflow you are using.

And even if we could somehow influence their behaviour, we need to provide a valid alternative. If we asked MWAA to remove the constraints, they would say we can simply use `--constraint /dev/null` and remove them ourselves. If we asked them to use different constraints, with higher version of OpenLineage, somebody would have to prepare and maintain those (also, users are not so eager to use 3rd party provided files, that’s probably why MWAA uses the one from Airflow) and they would say, we can easily do it ourselves as well.

2. I'm not sure if we can guarantee the sync between our constraints and Airflow ones over time, something to think about.
3. Just FYI, [here](https://github.com/apache/airflow/blob/6daceb844c53a4e6c94b516d4f77e684a7de5b7f/dev/MANUALLY_GENERATING_IMAGE_CACHE_AND_CONSTRAINTS.md#manually-generating-constraint-files) are the docs about generating constraints in Airflow

**Comment by mobuchowski** [comment]
I think it would be good to have an option for MWAA users to override their dependencies. 
Not exactly sure we're good place for that - especially if any other dependencies change, and we don't have good ways to test and make sure we're not breaking something else.

**Comment by kacpermuda** [comment]
@rahul-madaan I updated the description on the [PR](https://github.com/apache/airflow/pull/37994) that fixed the issue, providing with a solution. Now that i mentioned this PR, it should be linked to this issue, and users should be able to easily find it, also in Google. So i think for now we can just provide the users with link to this issue and they will be able to figure out the solution. WDYT?

**Comment by rahul-madaan** [comment]
Looks good! let us close the issue?
