### ISSUE TITLE
[PROPOSAL] Allow sending DatasetEvent and JobEvent using Transport.emit of Java client

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2616]
**Purpose:**

Currently `Transport.emit` method of Python client accepts RunEvent, DatasetEvent, JobEvent. But Java client accepts only RunEvent and String, so both DatasetEvent and JobEvent should be serialized to JSON first.

This is actually a transport implementation detail. Some transport may use other formats for serialization, e.g. MsgPack, Avro, Protobuf and so on.

**Proposed implementation**

Allow emmiting DatasetEvent and Job Event by calling `Transport.emit` method. Serialization will be handler by transport, currently this is just JSON.

**Comment by dolfinus** [comment]
Draft implementation: #2611

**Comment by dolfinus** [comment]
@pawel-big-lebowski have a note about Kafka/Kinesis implementation:
> We need first to decide how to handle different event types for Kafka and Kinesis. I would opt for separate topics but I am open to discussion and would love to hear others opinion too.
https://github.com/OpenLineage/OpenLineage/pull/2611#discussion_r1570061883

Kafka shards messages to different topic partitions using the value of `key` field of the message. Sending message with a key `abc` to a topic leads to storing this message in partition with number `hash(key) % num_partitions`. Using `null` as key value stores message in a random partition. For Kinesis it is almost the same, but `partitionKey` should always be set, it cannot be `null`.

Before #2559 Java client used static value for Kafka partition key (total message ordering, bad for performance), but Python used a random key (no ordering at all, bad for event handling). Also Python already supported sending any type of event, not just RunEvent.

#2559 introduced `messageKey` option for Kafka transport, which by default is generated as:
* `run:{jobNamespace}/{jobName}`
* `dataset:{datasetNamespace}/{datasetName}`
* `job:{jobNamespace}/{jobName}`

This unified the message key generation for both Java and Python clients, allowing both to shard messages to different topic partitions, and to keep the order of events related to the same entity (run/dataset/job).
User may override this value by explicitly passing `messageKey` config option of Kafka transport, to send messages of parent and child run events in the same topic.

This leads to sending events of all types to just one topic (currently only for Python client). So any message received from the same topic should be first parsed as raw JSON, and then using value of `schema` field it can be decided which event type should be used to deserialize this message.
This is why `run:`, `dataset:` and `job:` prefixes were added, allowing consumers to route messages related to some specific event type. But this requires all Kafka consumers to share the same implementation detail, and I'm not sure is that correct or not.

Using different topics may solve this issue. But this is not actually only Kafka/Kinesis transport issue, but all of the transport implementations. For example, FileTransport will append different events to the same file, and file reader should then properly deserialize these events depending on event type.

I'm not sure that the solution should be.

**Comment by pawel-big-lebowski** [comment]
The tradeoff is: (1) burden with amount of configuration entries on producers side vs (2) extra complexity on consumer side to detect which even type is actually sent. 

`FileTransport` was introduced for testing purpose. For `HTTP` we have tested that event type can be resolved with standard Jackson library (https://github.com/MarquezProject/marquez/pull/2495/files#diff-baa4affac174a99d36ad8ae509a893002291665ca3deba5dae878301875b136e)

My Kafka experience (from long time ago) is that its consumers were fragile when reading from topic other data than expected. And, a newer version of producer could possibly pose a threat to process reading events from Kafka. 

Would it make sense to at least let client decide whether to send everything in one topic or separately?

**Comment by dolfinus** [comment]
> Would it make sense to at least let client decide whether to send everything in one topic or separately?

IIRC, default integrations with Airflow, Spark and Flink send only RunEvent. For DatasetEvent and JobEvent user have to write some code, and also configure which transport should be used. So user can set proper `topicName` for events generated in his code.

**Comment by pawel-big-lebowski** [comment]
>  . So it's up to user to set `topicName` value.

Yeah, this makes sense.

**Comment by dolfinus** [comment]
So for now keeping the same set of options for all the transport implementations. User should set proper endpoint/topic/file name, which can handle event types.

For Kafka/Kinesis using the same partition key, to distinguish between event types without deserializing `value`:
* `run:{jobNamespace}/{jobName}`
* `dataset:{datasetNamespace}/{datasetName}`
* `job:{jobNamespace}/{jobName}`

Is that OK?

**Comment by dolfinus** [comment]
For Kinesis, should I add explicit `partitionKey` option to allow user to override the value, just like in Kafka?

**Comment by dolfinus** [comment]
Moved changing Kinesis `partitionKey` format to #2620
