### ISSUE TITLE
Setup multi-project builds for `java`

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#262]
Let's define a root `build.gradle` file with each subproject (`openlineage-java`, `openlineage-spark`) defining it's own `build.gradle` file for overrides, dependecies, etc. Use [`marquez/build.gradle`](https://github.com/MarquezProject/marquez/blob/main/build.gradle) as a reference. This will also simplify our releases process ensuring java module versions are aligned.

**Comment by mobuchowski** [comment]
@wslulciuc do you still want to do it? Not sure if it would work so well with our modules having wildly differing requirements.
