### ISSUE TITLE
[PROPOSAL][SPARK] Add GCPEnvironmentFacetBuilder to collect additional properties when running on Google Cloud Platform

### ISSUE THREAD

**Issue by codelixir** [OpenLineage/OpenLineage#2641]
**Purpose:**
This does not add a new facet, rather modifies the environment-properties facet in presence of a GCP runtime. Here are some of the properties which should be contained:
* “spark.project.id”
* “spark.app.id”
* “spark.app.name”
* “origin” : {“name”, “sourceType”}
* “spark.query.node.name”

And then some specific properties will vary depending on whether the environment is dataproc serverless batch, serverless interactive, or if the job is running on a GCE cluster.

**Proposed implementation**
Create a new facet builder class
```
GCPEnvironmentFacetBuilder extends CustomFacetBuilder<SparkListenerEvent, EnvironmentFacet>
```
We add it to the list of builders in `InternalEventHandlerFactory#createRunFacetBuilders` in case this is a GCP runtime.

Create class GCPUtils which will have methods to check whether it is running on a GCP resource, what kind of resource it is, and also to get the properties required for the environment facet. GCPEnvironmentFacetBuilder can then use these to build the facet.

**Comment by dolfinus** [comment]
Hi. I have a similar idea in https://github.com/OpenLineage/OpenLineage/issues/2589#issuecomment-2076816639, but instead of using `environment-properties` facet my proposal is to extend `spark_properties` facet.
