### ISSUE TITLE
[GitHub] Update GitHub issue/PR labels

### ISSUE THREAD

**Issue by kacpermuda** [OpenLineage/OpenLineage#2666]
This is my proposal on how we should update labels on GitHub so that they are more useful and readable. I don't need help with the operation itself, but would like some feedback before i start :slightly_smiling_face:

https://docs.google.com/spreadsheets/d/1WYt0IHc2N5pWhMSfN7vlFaXgssV_pdAlL0UxAo5yblE/edit?usp=sharing

**Comment by mobuchowski** [comment]
This looks great to me. Thanks for the work.
