### ISSUE TITLE
[Java] Move static checks to pre-commit hooks.

### ISSUE THREAD

**Issue by JDarDagran** [OpenLineage/OpenLineage#2680]
**Purpose:**
Make static checks more visible and understandable in Java code.

**Proposed implementation**
It surely requires using docker.
* `language: docker` with `repo: local` requires `Dockerfile` to be in the same directory with `.pre-commit-config.yaml` - bad solution
* `language: docker_image` with `repo: local` - it might require building our own custom image - may be inconvenient to maintain
* have separate repository for Java-related pre-commit hooks just for OL needs (similar to https://github.com/gherynos/pre-commit-java)

**Comment by pawel-big-lebowski** [comment]
would be good to have single docker with java8 & java11 with the ability to switch between the envs.

**Comment by mobuchowski** [comment]
@pawel-big-lebowski wouldn't it be easier just to switch docker image tags? Is there use case where you really want to stay inside single docker env for different task using two Java envs?

**Comment by dolfinus** [comment]
Consider adding `spotlessApply` to pre-commit hooks, and also enabling `prettier` for all JSON files in the repo (not just `spec/**`).

**Comment by mobuchowski** [comment]
I agree with @dolfinus here, all static checks that can fail on CI should be specified as pre-commit hooks first.

**Comment by mobuchowski** [comment]
`https://hub.docker.com/_/gradle/` - why not? 🙂

**Comment by JDarDagran** [comment]
Yeah, but it also needs gradle configuration per project, how to set it up in pre-commit and probably more.

**Comment by JDarDagran** [comment]
Part of if got merged in #2694.

**Comment by dolfinus** [comment]
On my local machine I've got errors like this while commiting changes:
```
.pre_commit/run-pmd.sh: line 43: ./pmd/bin/run.sh: No such file or directory
```

**Comment by JDarDagran** [comment]
> On my local machine I've got errors like this while commiting changes:
> 
> ```
> .pre_commit/run-pmd.sh: line 43: ./pmd/bin/run.sh: No such file or directory
> ```

Would you want to share output from `pre-commit run pmd --all-files -v`?

**Comment by dolfinus** [comment]
```
pmd......................................................................Failed
- hook id: pmd
- duration: 0.64s
- exit code: 127

.pre_commit/run-pmd.sh: line 43: ./pmd/bin/run.sh: No such file or directory
```

If I remove `> /dev/null 2>&1` redirections from `run-pmd.sh`, I've got:
```
pmd.zip: Permission denied
```

This is because docker container is running under `circleci` user with id 1001, but user on my local machine has id 1000. So process inside container cannot download `pmd.zip` or make `pmd` binary executable.

**Comment by JDarDagran** [comment]
It runs with `-u` flag: https://github.com/pre-commit/pre-commit/blob/dd144c95f6cdab42ec8f90011f7d69d6577248f8/pre_commit/languages/docker.py#L106C29-L106C35

I can't really reproduce the issue, could you please try with with the change in entrypoint?
```
entry: -v ./.pmd_cache:/opt/.pmd_cache:rw --entrypoint .pre_commit/run-pmd.sh cimg/openjdk:8.0
```

**Comment by dolfinus** [comment]
`:rw` is default value, so it will not change anything.

I've fixed this by removing `.pmd_cache` and creating it manually.
