### ISSUE TITLE
[BUG] Airflow ethena extractor may produce empty name for Dataset

### ISSUE THREAD

**Issue by dkt-sophie-ly** [OpenLineage/OpenLineage#2699]
### OpenLineage integration/client

Airflow integration

### OpenLineage version

openlineage-airflow==1.14.0

Hi all ! 

Not sure if it's a real bug or not but concerning Airflow Athena Operator, users have to specify an output bucket and sometimes user put the root of a bucket like the following example:

```
read_table = AthenaOperator(
    ...
    output_location=f"s3://my_bucket",
)
```

Which is completely fine for airflow (the DAG is running successfully) but it produces a Event with an empty dataset name:

```
{
  "eventType": "COMPLETE",
  "eventTime": "2020-12-28T19:52:00.001+10:00",
  "run": {
    "runId": "UUID"
  },
  "job": {
    "namespace": "airflow",
    "name": "test"
  },
  "inputs": [],
  "outputs": [
    {
      "namespace": "s3://my_bucket",
      "name": ""
    }
  ],
  "producer": "https://github.com/OpenLineage/OpenLineage/blob/v1-0-0/client",
  "schemaURL": "https://openlineage.io/spec/1-0-1/OpenLineage.json#/definitions/RunEvent"
}
```

An empty name can be problematic for tool like marquez, it makes the UI crash.

### What you think should happen instead

According to the file

the output dataset is created like that:

````
        outputs.append(
            Dataset(
                name=parsed.path,
                source=Source(
                    scheme=parsed.scheme,
                    authority=parsed.netloc,
                    connection_url=output_location,
                ),
            )
        )
````

<img width="769" alt="image" src="https://github.com/OpenLineage/OpenLineage/assets/130998593/764a1bbb-edd1-426f-bbe4-f9e4838f5a02">

In our example with s3://my_bucket, the name of the dataset is parsed.path but in our case parsed.path is empty that's why the name of the dataset is empty.

Should we put a default value then ? Like 'root' ?

### How to reproduce

Use AthenaOperator with an output location at the root of your bucket without the '/' at the end

````
read_table = AthenaOperator(
    task_id="test",
    query="SELECT 1",
    database=athena_database,
    output_location=f"s3://my_bucket",
)

````

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work

**Comment by kacpermuda** [comment]
Hey @dkt-sophie-ly , thanks for using OpenLineage ! Just to let you know, If you're using Airflow 2.7+, you should probably use [native Airflow OpenLineage provider](https://airflow.apache.org/docs/apache-airflow-providers-openlineage/stable/index.html). The ongoing development and enhancements will be focused on the apache-airflow-providers-openlineage package, while the openlineage-airflow will primarily be updated for bug fixes.

As to your question, i believe #2700 should fix that.
