### ISSUE TITLE
[BUG]- drop event is not received from spark 3.4.2 and 3.5.0

### ISSUE THREAD

**Issue by savannavalgi** [OpenLineage/OpenLineage#2716]
### OpenLineage integration/client

Spark integration

### OpenLineage version

latest

### Problem details

tested in spark integration version 3.4.2 and 3.5.0
the logical plan received from spark does not have drop table information ( like name of the table)

logical plan received in spark version 3.3 has information about the drop table.
```
[
  {
    "class": "org.apache.spark.sql.execution.command.DropTableCommand",
    "num-children": 0,
    "tableName": {
      "product-class": "org.apache.spark.sql.catalyst.TableIdentifier",
      "table": "drop_table_test",
      "database": "default"
    },
    "ifExists": false,
    "isView": false,
    "purge": false
  }
]
```

logical plan received in spark version 3.4.2 does not have needed information(tableName property)
```
[
  {
    "class": "org.apache.spark.sql.catalyst.plans.logical.DropTable",
    "num-children": 1,
    "child": 0,
    "ifExists": false,
    "purge": false
  },
  {
    "class": "org.apache.spark.sql.catalyst.analysis.ResolvedIdentifier",
    "num-children": 0,
    "catalog": null,
    "identifier": null
  }
]
```

stack trace on the error received while integration testing with spark version 3.4.2
with command
`./gradlew :app:integrationTest --tests io.openlineage.spark.agent.SparkContainerIntegrationTest.testDropTable -Pspark.version=3.4.2`

  ```2024-05-23 09:27:17 WARN  io.openlineage.spark3.agent.lifecycle.plan.DropTableVisitor - Unexpected child type. Expected ResolvedTable, got class org.apache.spark.sql.catalyst.analysis.ResolvedIdentifier```

### How to reproduce

#2214 

for the newly added integration test for drop table

https://github.com/savannavalgi/OpenLineage/blob/8bbbe630c7a4fc39b057c0fdc1ae2d08339530a2/integration/spark/app/src/test/java/io/openlineage/spark/agent/SparkContainerIntegrationTest.java#L292

https://github.com/savannavalgi/OpenLineage/blob/main/integration/spark/app/integrations/container/pysparkDropTableStartEvent.json 

to reproduce run the below command with the above code.
`./gradlew :app:integrationTest --tests io.openlineage.spark.agent.SparkContainerIntegrationTest.testDropTable -Pspark.version=3.4.2`

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work

**Comment by savannavalgi** [comment]
we have opened a issue on spark jira board as well to track this
https://issues.apache.org/jira/browse/SPARK-48390

**Comment by pawel-big-lebowski** [comment]
Your logs suggest you're using version `1.10.0` which is not the latest per the time of creating this issue. 
Within the code we

The code is doing following thing:
```
    if (!(dropTable.child() instanceof ResolvedTable)) {
      log.warn(
          "Unexpected child type. Expected ResolvedTable, got {}", dropTable.child().getClass());
      return Collections.emptyList();
    }
```
[link](https://github.com/OpenLineage/OpenLineage/blame/e88aaa147edfebd7d1f399b554b846d951a130ee/integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/DropTableVisitor.java#L36)

As your logs suggest the child of logical plan is `ResolvedIdentifier` instead of `ResolvedTable` and, as a solution, one needs to find a way to extract dataset id out of this.

**Comment by savannavalgi** [comment]
@pawel-big-lebowski 

i verified the test with latest openlineage code.
the issue still remains the same, just that the error is being handle gracfully in the latest version.

to extract the table name/dataset id out of the logical plan, 
the logical plan received from spark does not have the table information.
```
[
  {
    "class": "org.apache.spark.sql.catalyst.plans.logical.DropTable",
    "num-children": 1,
    "child": 0,
    "ifExists": false,
    "purge": false
  },
  {
    "class": "org.apache.spark.sql.catalyst.analysis.ResolvedIdentifier",
    "num-children": 0,
    "catalog": null,
    "identifier": null
  }
]

```

logs from the latest version
`  2024-05-23 09:27:17 WARN  io.openlineage.spark3.agent.lifecycle.plan.DropTableVisitor - Unexpected child type. Expected ResolvedTable, got class org.apache.spark.sql.catalyst.analysis.ResolvedIdentifier`
