### ISSUE TITLE
[QUESTION] Glue namespace format

### ISSUE THREAD

**Issue by dolfinus** [OpenLineage/OpenLineage#2765]
**Details:**
Currently there are 2 different formats used by Spark integration for Glue namespace:
* `aws:glue:{region_id}:{account_id}` for main integration:
  https://github.com/OpenLineage/OpenLineage/blob/b107e409bbe526ba491bb5bdb73a6036d80cf800/integration/spark/shared/src/main/java/io/openlineage/spark/agent/util/PathUtils.java#L81-L90
* `s3://bucket/path/to/warehouse/database.db` for Iceberg tables:
  https://github.com/OpenLineage/OpenLineage/blob/b107e409bbe526ba491bb5bdb73a6036d80cf800/integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/catalog/IcebergHandler.java#L105-L109

There probably should be synchronized.

My questions are:
* Is it possible to synchronize Iceberg implementation with main one? Are `AWS_REGION` and `spark.glue.accountId` are set for Iceberg configuration? I see [glue.id](https://iceberg.apache.org/docs/1.5.1/aws/#glue-catalog-id) option in Iceberg documentation, but it is optional.
* What format should be used here? My proposal is `awsglue://{account_id}@glue.{region_id}.amazonaws.com` because it matches with [Naming convention](https://openlineage.io/docs/spec/naming/), in particular AWS Athena, and also matches [Glue documentation](https://docs.aws.amazon.com/general/latest/gr/glue.html). But there can be other cases, like using [assume-role](https://iceberg.apache.org/docs/1.5.1/aws/#cross-account-and-cross-region-access) or connecting to an [access point](https://iceberg.apache.org/docs/1.5.1/aws/#s3-access-points).

**Note:**

I'm **not** a Glue user, and I have no experience with AWS at all. The reason I'm asking this question is to avoid breaking things in #2718 implementation, where table identifier and metastoreUrl will be used as dataset name & namespace respectively, instead of using table location.

**Comment by dolfinus** [comment]
Draft implementation: #2766

**Comment by kacpermuda** [comment]
Maybe we should consider using [ARN's](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html) for all AWS resources and standardize everything to that? Maybe apart from s3 that already has a standard URI representation s3://bucket/file

**Comment by dolfinus** [comment]
As I see, ARN require information like regionId, accountId, resourceId. What should be used as resourceId in the first case?

**Comment by dolfinus** [comment]
Ok, I'll update pull request

**Comment by dolfinus** [comment]
Updated #2766.

For Iceberg integration with Glue, I haven't updated it yet as I don't see which properties could be used to get regionId and accountId. Any ideas?
