### ISSUE TITLE
Extend configurable Spark test to allow running on specified Docker image

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#2804]
A `configurable-test.sh` script at its current shape ([link](https://github.com/OpenLineage/OpenLineage/blob/main/integration/spark/cli/configurable-test.sh))
allows following configuration params:
```
sparkVersion: 3.3.4
scalaBinaryVersion: 2.12
```
Based on them, one of the Docker images available in [Openlineage quai repository](https://quay.io/repository/openlineage/spark?tab=tags) is selected. 

As an extension to this mechanism, we would like to let users provide a docker image, with `pyspark` and `spark-submit` installed to run the test on. This can be initially with https://hub.docker.com/_/spark/tags

**Comment by tatiana** [comment]
Merged to main 🎉
