### ISSUE TITLE
Build OpenLineage-Spark on Java 17 with target compatibility set to Java 8

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#2818]
In few days Spark 4.0 will be released. One of the issues to support it, is related with Java versions that can run Spark 4.0 apps. According to the [docs](https://spark.apache.org/docs/4.0.0-preview1/), it runs on `on Java 17/21` while `shared` submodule is currently compiled with Spark 3.2.3 which according to [its docs](https://spark.apache.org/docs/3.2.3/) runs on `Java 8/11`.

Theoretically it's possible to compile `shared` module on Java 17 with target compatibility set to Java 8. However, building `shared` means running all its tests and some of them run `SparkSession` im memory. So, this in fact means running `Spark 3.2.3` with Java 17. This may be possible according to the comments within: https://issues.apache.org/jira/browse/SPARK-33772:
```
"-XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED"
```

The output of this task would be to know if this is doable. If yes, this will help supporting Spark 4.0. If not, additional CI changes will be necessary to build different submodules on different versions of java virtual machines.

**Comment by mobuchowski** [comment]
I think adding those JVM options might be too cumbersome for Spark users, if at all doable - for example in managed Spark environments.

**Comment by d-m-h** [comment]
It _might_ be possible to add this to the `spark.driver.extraJavaOptions` in either the (a) `spark-defaults.conf` file or via the `--conf` parameters at job submission time. It don't think that this option is changeable at runtime (but I may be mistaken).

**Comment by pawel-big-lebowski** [comment]
One of the possible workarounds would be to upgrade `shared` to Spark 3.3 as this version already supports Java 17 (https://spark.apache.org/docs/3.3.3/). In this case, unit tests for Spark 3.2 will NOT be run. However, integration tests in app module will be run for Spark 3.2, which may be a fair tradeoff.

**Comment by mobuchowski** [comment]
Would that break older versions?

**Comment by pawel-big-lebowski** [comment]
No. However, breaking older staff is possible when:
 * someone modifies `shared` with a code that does not compile on spark 3.2 (like using class that was added in 3.3)
 * unit tests on `shared` will not detect it as they'll be running 3.3
 * integration tests within app will not detect it.

**Comment by pawel-big-lebowski** [comment]
By the way, we can always add an extra CI verification job to run:
```
./gradlew :shared:build
./gradlew :spark3:build
```
on Java 8 and with Spark version 3.2.3 for `shared` and `spark3` as it is now.  This would make sure nothing gets broken in future.
