### ISSUE TITLE
[BUG][Spark] Missing Schema/DB Name and Symlink in outputs when Inserting into Parquet Table on S3

### ISSUE THREAD

**Issue by dechoma** [OpenLineage/OpenLineage#2820]
### OpenLineage integration/client

Spark integration

### OpenLineage version

openlineage-spark_2.12-1.17.1

### Technology and package versions

spark==3.3.1

### Problem details

When inserting into a Parquet table on S3, the schema name is missing in the outputs field, and the symlink is not being added. This makes it impossible to definitively link the result table to the schema/database.

In the attached output event, the output table we are looking for is `testproject.lineage_test_case`, and it cannot be extracted from this event. We cannot rely on the S3 bucket name as the schema/db name.
[ol_event.json](https://github.com/user-attachments/files/16056943/ol_event.json)

### How to reproduce

run spark session and insert data to existing parquet table with location on s3 `spark.table("venus.perftest_iceberg").write.mode("overwrite").format("parquet").insertInto('testproject.lineage_test_case', overwrite=True)`

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work

**Comment by dolfinus** [comment]
This should be solved in #2794

**Comment by dechoma** [comment]
thx @dolfinus , indeed https://github.com/OpenLineage/OpenLineage/pull/2794 fixed the issue
