### ISSUE TITLE
[PROPOSAL] Column lineage cartesian product threshold in Spark

### ISSUE THREAD

**Issue by arturowczarek** [OpenLineage/OpenLineage#2874]
**Purpose:**
In Spark integration, when we have a job with `DISTINCT` clause, it is implemented as an `Aggregate` (`GROUP BY`). It creates the column lineage where every column depends on every column. The size of this cartesian product is becoming a problem for tables where we have many columns. For jobs that simply copy rows from one table to another while removing duplicates, the events generated can become excessively large. It is common for tables to have dozens of columns, resulting in thousands of column lineage connections.

**Proposed implementation**
We could have an additional property `io.openlineage.columnlineage.cartesianProductColumnCardinalityThreshold`. When the aggregate is all-to-all dependency with this many columns, instead of producing every possible combination, we would replace it with a single property for `columnLineage` object: `cartesianProductShortCircuitApplied`. So the output in this form (pseudocode):
```json
{
  "outputs": [
    {
      "facets": {
        "schema": {
          "fields": [
            "field1",
            "field2",
            "field3",
            "field4",
            "field5",
            "field6"
          ]
        },
        "columnLineage": {
          "fields": {
            "field1": [
              "field1",
              "field2",
              "field3",
              "field4",
              "field5",
              "field6"
            ],
            "field2": [
              "field1",
              "field2",
              "field3",
              "field4",
              "field5",
              "field6"
            ],
            "field3": [
              "field1",
              "field2",
              "field3",
              "field4",
              "field5",
              "field6"
            ],
            "field4": [
              "field1",
              "field2",
              "field3",
              "field4",
              "field5",
              "field6"
            ],
            "field5": [
              "field1",
              "field2",
              "field3",
              "field4",
              "field5",
              "field6"
            ],
            "field6": [
              "field1",
              "field2",
              "field3",
              "field4",
              "field5",
              "field6"
            ]
          }
        }
      }
    }
  ]
}
```

would become

```json
{
  "outputs": [
    {
      "facets": {
        "schema": {
          "fields": [
            "field1",
            "field2",
            "field3",
            "field4",
            "field5",
            "field6"
          ]
        },
        "columnLineage": {
          "cartesianProductShortCircuitApplied": true
        }
      }
    }
  ]
}
```

**Comment by mobuchowski** [comment]
I like the idea, but there are some details to be worked on. 

This would only apply for `INDIRECT` transformation types, right? We'd need to make sure it's only affecting those.
I think this should never affect other transformation types. So the result would be 

```
        "columnLineage": {
          "fields": {
            "field1": {
              "inputFields": [
                "namespace": ...
                "name": ...
                "field": "field1",
                "transformations": [{
                      "type": "DIRECT",
                      "subtype": "IDENTITY",
                      "description": "",
                      "masking": false
                }],
               "cartesianProductShortCircuitApplied": true
              ]
            },
            "field2": {
              "inputFields": [
                "namespace": ...
                "name": ...
                "field": "field2",
                "transformations": [{
                      "type": "DIRECT",
                      "subtype": "IDENTITY",
                      "description": "",
                      "masking": false
                }],
               "cartesianProductShortCircuitApplied": true
              ]
            },
          ...
          }
```

I don't love the name too :) 

`cartesianProductShortCircuitApplied` is both too verbose and not understandable for general user.

**Comment by arturowczarek** [comment]
Yes, the names are terrible. The trick should apply only to indirect dependencies. What about: `io.openlineage.indirectAllToAllThreshold` and `"indirectAllToAll": true`? Maybe someone has some better suggestions?

**Comment by mobuchowski** [comment]
I like `indirectAllToAll` more. @pawel-big-lebowski @tnazarew @ngorchakova any comments?

**Comment by dolfinus** [comment]
Could this faced be updated to have not just column -> column mapping, but also column -> dataset mapping? INDIRECT transformations are usually just filters, and applied to the entire dataset, and not individual output fields.

**Comment by pawel-big-lebowski** [comment]
I wouldn't recommend replacing the whole `columnLineage` facet with`"cartesianProductShortCircuitApplied": true`.

I don't like `indirectAllToAll ` because the problem does not have to relate to all-to-all. For example, the query below:
```
WITH temp as (SELECT a,b,c,d,e,f FROM table GROUP BY a,b,c,d,e,f)
SELECT a,b,c,d,e <- NO 'f'
```
leads to the same problem, but it's not all-to-all

Instead, I think we should add extra field `status` which can be `FULLY_COLLECTED` or
```
PARTIALLY_COLLECTED: {
  'reason': 'cartesianProductShortCircuitApplied'
  'reason_desc': 'indirect dependencies caused cartesian product of the fields'}
```
}

**Comment by dolfinus** [comment]
Another way is to add OL config option to disable tracking INDIRECT column lineage, if user does not need it in the first place.

**Comment by arturowczarek** [comment]
https://github.com/OpenLineage/OpenLineage/issues/3084 is a better idea.
