### ISSUE TITLE
[PROPOSAL] Make job run ids unique 

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#29]
**Purpose:**
Currently, the `Run` object has a `runId` property that is defined as "_The id of the run, unique relative to the job_" https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json#L61-L63 . This implies a run id may be reused across jobs so that to link a job run to a parent run, the job name and namespaces are required in addition to the run id (see https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json#L273-L311 ).

In practice, Marquez generates UUIDs for the job run ids (e.g., see the airflow integration at https://github.com/MarquezProject/marquez/blob/main/integrations/airflow/marquez_airflow/dag.py#L228-L229 ). In the spark integration, there's confusion about whether the passed job run parameters belong to the parent run or to a new job run (see the README at https://github.com/MarquezProject/marquez/blob/main/integrations/spark/README.md and the context at https://github.com/MarquezProject/marquez/blob/main/integrations/spark/src/main/java/marquez/spark/agent/MarquezContext.java#L29-L31 ).

Given the implementation already uses UUIDs for job runs, I think the requirement to pass the additional job information is a bit burdensome and redundant. It also leaves room for confusion in implementation projects, which would be nice to eliminate.

**Proposed implementation**
I propose requiring job run ids be globally unique (at least within a given OpenLineage backend) and remove the `job` parameter from the `ParentRunFacet`. Integrations should pass around these globally unique runIds to link job runs to parents. This is in line with the existing Marquez model (see https://github.com/MarquezProject/marquez/blob/main/clients/python/marquez_client/client.py#L325-L327 ) and will reduce confusion in integration implementations, such as the spark integration project.

**Comment by julienledem** [comment]
I'm in favor of making the runId a UUID

**Comment by wslulciuc** [comment]
+1

**Comment by wslulciuc** [comment]
Fixed #65
