### ISSUE TITLE
Allow whole OL configuration to be specified by ENV variables

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#2916]
For now, our main model of OL config is an `openlineage.yml` file with specified nested fields. Over the years, we've had a special set of some configuration variables that accumulated either due to history (like `OPENLINEAGE_URL` to configure HTTP transport before we've had the concept of transport) or operational ease (like `OPENLINEAGE_DISABLED` to stop OL action without need to physically remove all OL code and config from relevant system).

Additional complication is that OL is multi-language project - so Python and Java (and potentially Go, Rust, C++...) clients and configs would necessarily have to differ - and integration specific config - what makes sense in Airflow, is not really relevant in Spark.

So, not all was possible to configure via env variables - we've been adding new configurations with `openlineage.yml` or integration-specific context, as with Airflow or Spark conf. 

However, environment variables are the easiest to use operationally in modern data context, especially running on Kubernetes or so. It would be great if we could use those consistently.

There are few problems with that mechanism.

1. Transports. We want to also configure transports that way. However, they have different types. We want to have some hierarchy mechanism to decide what variables go where. Also, we want to introduce "composite" transport mechanism to allow people to emit events to different destinations, without needing to set up proxy. 
    - Naive way would be to add list of transports to OL transport mechanism. However, we'd prefer that logic to be handled with specialized "composite" transport that would allow us to attach behavior to different transport execution, with added benefit of not requiring change of current configuration. This will be described separately by @JDarDagran 
    - That still leaves us with problem of knowing which env configuration to attach to different mechanism - since env variables badly map to unordered lists. The solution might be to add optional `name` field to transport config - and allow people to configure it this way, with potential hierarchy being resolved by name hierarchy. An example, which would create HTTP transport with configured additional HTTP headers :
     ```env
     OPENLINEAGE_TRANSPORT_BACKEND_TYPE: http
     OPENLINEAGE_TRANSPORT_BACKEND_URL: http://something.datadog.com
     OPENLINEAGE_TRANSPORT_BACKEND_HTTP_HEADERS: key=value;key1=value1
     ``` 
2. Complex names and mixed case. With Spark integration we've had less clarity on the config mechanism in the past and we've introduced "mixed case" configuration variables like `spark.openlineage.circuitBreaker.type`- with unknown env mapping. Should it be `OPENLINEAGE_CIRCUIT_BREAKER_TYPE` or `OPENLINEAGE.CIRCUITBREAKER.TYPE`? 
    - I'm for using `OPENLINEAGE_CIRCUIT_BREAKER_TYPE` - however, we should not do this implicitly. In this case, code of configuration class should have specified annotations/decorators on how to explicitely map the env variable to the concrete configuration. It is further complicated in the case of nested configuration. I

**Comment by mobuchowski** [comment]
We should also consider separation of names - this allows us to separate "sections" with "names" here. 
```
OPENLINEAGE__TRANSPORT__TWO_WORDS
```

**Comment by arturowczarek** [comment]
Double underscore separation seems super easy to deserialize. Just a few replacements, simple transformation and we can use the same mechanism as in Spark `ArgumentParser`.

**Comment by wslulciuc** [comment]
@mobuchowski Will there also be a configuration for transport compression? i.e.:

```
OPENLINEAGE_TRANSPORT_BACKEND_COMPRESSION=gzip
```

**Comment by JDarDagran** [comment]
@wslulciuc yes.
