### ISSUE TITLE
[PROPOSAL] Allow creating datasets via API

### ISSUE THREAD

**Issue by limx0** [OpenLineage/OpenLineage#294]
**Purpose:**
There are cases where data is not created or maintained by a system you own, but you still may want to track lineage within Open Lineage. Examples could be an FTP server, a public S3 bucket or data obtained through some 3rd party provider. This exists in Marquez via `create_dataset` but, from what I can see , doesn't exist in open lineage at this stage. 

**Proposed implementation**
Add something similar to the effect of `create_dataset` to open lineage, such that existing datasets/ouputs can be recognised and captured in downstream lineage.

**Comment by collado-mike** [comment]
Currently, a `Dataset` is created whenever a `RunEvent` references it. This happens whether the data is read or written. There is no requirement that a `Dataset` exists before a `Run` can reference it. Are there reasons that you need a `Dataset` to be created before the `Run` happens?

**Comment by limx0** [comment]
> Are there reasons that you need a Dataset to be created before the Run happens?
Nope - no requirement from me on them being created before an initial run happens I don't think. 

Thanks @collado-mike - I didn't realise they were created when read, closing.
