### ISSUE TITLE
snowflake: make sure normalization of Snowflake account

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#2966]
Snowflake's converting users to new identifier format: https://docs.snowflake.com/en/user-guide/admin-account-identifier#existing-accounts

The region part is not included anymore, and we're wrongly appending it to the new format.

From discussion on Airflow Slack: https://apache-airflow.slack.com/archives/C059CC42E9W/p1724232501955659

**Comment by JDarDagran** [comment]
Released in `openlineage-python==1.21.1`
