### ISSUE TITLE
[Airflow] Use plugins to register macros.

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#306]
We should use [Plugins](https://airflow.apache.org/docs/apache-airflow/stable/plugins.html) to register macros. This way is cross-version between 1.10 and 2. Current one - adding them in DAG - works only for 1.10.

**Comment by julienledem** [comment]
@mobuchowski can you elaborate the context? ex: What are macros used for,...

**Comment by collado-mike** [comment]
We currently have two macros- one for the the `lineage_run_id`- this returns the runId for the current task. This is how we pass, e.g., the parent run id to a downstream task, such as a Spark job.

The other is `lineage_parent_id`- I'm not sure where this is used. @mobuchowski would know better

**Comment by mobuchowski** [comment]
`lineage_parent_id` passes all the information needed to reconstruct `ParentRunFacet` as opposed to only runId. 
It's used mostly for airflow/dbt right now: https://github.com/OpenLineage/OpenLineage/blob/main/integration/airflow/tests/integration/airflow/dags/dbt.py#L59

**Comment by mobuchowski** [comment]
Done.
