### ISSUE TITLE
[PROPOSAL] Add EnvironmentVariablesRunFacet to core spec.

### ISSUE THREAD

**Issue by JDarDagran** [OpenLineage/OpenLineage#3128]
#### Context:
In the current Spark integration, the `spark.openlineage.facets.custom_environment_variables` configuration allows passing environment variables to the EnvironmentFacet. However, this is specific to Spark and is not available at the core client level.

#### Objective:
The goal of this proposal is to extend the ability to provide a set of chosen environment variables at the client level, beginning with the Python client, to ensure more consistent functionality across integrations. The Java implementation is optional but recommended for consistency.

## Proposed implementation
1. Add `EnvironmentVariablesRunFacet` to Core Spec:
  * Introduce a new facet `EnvironmentVariablesRunFacet` to the OpenLineage core specification.
  * This facet will capture **a set of** environment variables that is **explicitly** defined by the user.
  * Proposed definition:
  ```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://openlineage.io/spec/facets/1-0-0/EnvironmentVariablesRunFacet.json",
  "$defs": {
    "EnvironmentVariable": {
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the environment variable.",
          "type": "string"
        },
        "value": {
          "description": "The value of the environment variable.",
          "type": "string"
        }
      },
      "required": ["name", "value"]
    },
    "EnvironmentVariablesRunFacet": {
      "allOf": [
        {
          "$ref": "https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet"
        },
        {
          "type": "object",
          "properties": {
            "environmentVariables": {
              "description": "The environment variables for the run.",
              "type": "array",
              "items": {
                "$ref": "#/$defs/EnvironmentVariable"
              }
            }
          },
          "required": ["environmentVariables"]
        }
      ],
      "type": "object"
    }
  },
  "type": "object",
  "properties": {
    "environmentVariables": {
      "$ref": "#/$defs/EnvironmentVariablesRunFacet"
    }
  }
}
```
 
2. Python Client: Add Support for Environment Variables:
   * Update the Python client configuration to accept a list of environment variables. It should be probably under `facets` section with `environment_variables` key.
   * This list will be passed into the new `EnvironmentVariablesRunFacet`.
   * The facet will be injected after the event is created, ensuring it doesn't interfere with other event generation processes.

3. Optional Java Client Implementation for Consistency:
   * While Spark already supports this functionality, the Java client currently does not.
   * For consistency across clients, it is suggested to add the same capability to the Java client.
   * For alignment with naming conventions, alias `custom_environment_variables` to `customEnvironmentVariables` in Java to follow camelCase standards.

### Additional Notes:
**Facet Addition Timing**: The `EnvironmentVariablesRunFacet` should be added only after the event is already created to avoid potential disruptions or race conditions in event generation.

**Java Client Consistency**: Adding this feature to the Java client is not required immediately, but it would improve consistency across clients. A future implementation would ensure both Python and Java clients can handle environment variables in a similar manner.

## Example Scenario: Capturing Build and Runtime Information
Let’s say you’re running a pipeline in a cloud environment, and you want to track certain key build or runtime details that are specific to the environment in which the job is running. For example, you might want to capture:

* Pipeline version (to track which version of the code or pipeline is being executed)
* Build timestamp (to record when the code or environment was built)
* Cluster ID (to know where the job is running)

You can use environment variables to inject this information into the OpenLineage event, which will help with later troubleshooting or auditing purposes.

Example OpenLineage Event:
```json
{
  "eventType": "START",
  "job": {
    "namespace": "my-pipeline",
    "name": "data-processing-job"
  },
  "run": {
    "runId": "a1b2c3d4e5"
  },
  "facets": {
    "environmentVariablesRunFacet": {
      "_producer": "https://github.com/OpenLineage",
      "_schemaURL": "https://openlineage.io/spec/facet-schema.json",
      "environmentVariables": [
        {
            "name": "PIPELINE_VERSION",
            "value": "v1.2.3"
        },
        {
            "name": "BUILD_TIMESTAMP",
            "value":"2024-09-30T12:34:56Z"
        },
        {
            "name": "CLUSTER_ID",
            "value": "cluster-abc123"
        }
      ]
    }
  }
}
```

In this example you achieve: version tracking, more build info, cluster identification.

**Comment by mobuchowski** [comment]
@JDarDagran I like how the facet looks. 

Could you expand on how would we define those env variables to be captured? Similar to how we do it in Spark?

**Comment by JDarDagran** [comment]
> @JDarDagran I like how the facet looks.
> 
> Could you expand on how would we define those env variables to be captured? Similar to how we do it in Spark?

Added this:
> Update the Python client configuration to accept a list of environment variables. It should be probably under facets section with environment_variables key.

**Comment by harels** [comment]
@JDarDagran do you know when you're planning to work on this? don't mean to rush you, but we are very excited for this, so we wanted to get a sense of when you think you'll get to it.

**Comment by JDarDagran** [comment]
Soon-ish. This month for sure on Python side.
