### ISSUE TITLE
[PROPOSAL] [spark] ability to toggle unknown facet procesing

### ISSUE THREAD

**Issue by OleksandrDvornik** [OpenLineage/OpenLineage#316]
**Purpose:**
Due to possible OOM issue which caused by recursive calls in `LogicalPlanSerializer` and later spark context shutdown I would propose to add ability to disable this feature. 
Example: 
`SparkContext has been shutdown (through reference chain: org.apache.spark.sql.execution.LogicalRDD["rdd"]->org.apache.spark.rdd.MapPartitionsRDD["prev"]->org.apache.spark.rdd.MapPartitionsRDD["prev"]->org.apache.spark.rdd.MapPartitionsRDD["prev"]->org.apache.spark.api.python.PythonRDD["narrowAncestors"]->scala.collection.convert.IterableWrapper[0]->org.apache.spark.rdd.ParallelCollectionRDD["empty"])`

**Proposed implementation**
Adding ability to disable unknown facet information gathering via args (as we do for getting client url) or via env variable

**Comment by fm100** [comment]
Do you happen to have an example spark job code which reproduces the issue?

**Comment by collado-mike** [comment]
Closing in favor of https://github.com/OpenLineage/OpenLineage/issues/402
