### ISSUE TITLE
[BUG] Unable to start docker container as mentioned in quick start guide

### ISSUE THREAD

**Issue by TejasRGitHub** [OpenLineage/OpenLineage#3185]
### OpenLineage integration/client

Spark integration

### OpenLineage version

No idea

### Technology and package versions

Whatever is included in the docker-compose.yaml file 

### Environment configuration

N/A

### Deployment details

N/A

### Problem details

Unable to start the docker containers, It gives me following error - 

### What you think should happen instead

Containers should start successfully and I should be able to start the marquez api and notebook 

### How to reproduce

Follow the instructions in - https://openlineage.io/docs/integrations/spark/quickstart/quickstart_local/ and check if the containers start after `docker compose up`

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

**Comment by arturowczarek** [comment]
Hi @TejasRGitHub . You didn't attach the error message.

**Comment by arturowczarek** [comment]
I tried the docker compose and discovered something related: https://github.com/OpenLineage/OpenLineage/pull/3192
It won't solve your problem, because for me the containers start.
Please also attach information about the container runtime you are using (Docker, Rancher, Podman, etc) operating system and the architecture of your CPU (x86 or Apple ARM processor?).

**Comment by arturowczarek** [comment]
@TejasRGitHub My pull request was merged and your issue closed. Please pull the newest changes, test if it works and reopen the issue with the details if it is still broken.

**Comment by TejasRGitHub** [comment]
Hi @arturowczarek , Sorry I forgot to attach the error 😅 , 
Here's the error I am getting , 
<img width="1190" alt="image" src="https://github.com/user-attachments/assets/ec799248-5264-4b41-ba83-866180474cca">

O.S. - macOS ( Sonoma ) 
Containerization Application - Rancher Desktop 
Architecture - Apple M1 Pro

**Comment by TejasRGitHub** [comment]
> @TejasRGitHub My pull request was merged and your issue closed. Please pull the newest changes, test if it works and reopen the issue with the details if it is still broken.

I did pull in the latest changes but it didn't help 😢

**Comment by arturowczarek** [comment]
Some say that it might be a matter of not enough memory: https://stackoverflow.com/questions/13575916/why-does-my-java-program-shut-down-without-any-error-messages-under-heavy-load
Here someone mentions about a similar Rancher Desktop problem: https://github.com/rancher-sandbox/rancher-desktop/issues/7253. I don't know how they fixed it so it's difficult to say if it is a matter of Marquez problem. Maybe you can switch runtimes and test?

**Comment by mobuchowski** [comment]
@TejasRGitHub the proper repository to report issues with Marquez would be https://github.com/MarquezProject/marquez

**Comment by TejasRGitHub** [comment]
> Some say that it might be a matter of not enough memory: https://stackoverflow.com/questions/13575916/why-does-my-java-program-shut-down-without-any-error-messages-under-heavy-load Here someone mentions about a similar Rancher Desktop problem: [rancher-sandbox/rancher-desktop#7253](https://github.com/rancher-sandbox/rancher-desktop/issues/7253). I don't know how they fixed it so it's difficult to say if it is a matter of Marquez problem. Maybe you can switch runtimes and test?

hey @arturowczarek , I changed the emulation of Rancher from QEMU to VZ ( with Rosetta Support ) and now I am able to start my containers. Thanks for your help
