### ISSUE TITLE
[BUG] DBT integration not compatible with DBT v1.8

### ISSUE THREAD

**Issue by NJA010** [OpenLineage/OpenLineage#3222]
### OpenLineage integration/client

DBT integration

### OpenLineage version

`openlineage-dbt==1.23.0`

### Technology and package versions

dbt-core==1.8.6, manifest=v12

### Problem details

`DbtArtifactProcessor.parse_assertions()` reads the node's name from a `test_metadata` field. However, the schema of the DBT manifest has changed and the name of a node is no longer in the `test_metadata` field. Instead, `name` is a field of each node. 
- manifest v12 docs: https://schemas.getdbt.com/dbt/manifest/v12/index.html#nodes_additionalProperties_anyOf_i6_name
- manifest v11 docs: https://schemas.getdbt.com/dbt/manifest/v11/index.html#nodes_additionalProperties_anyOf_i6_test_metadata_name
Removing `test_metadata` resolves this problem 
Screencap of error: 
![image](https://github.com/user-attachments/assets/2b679b3a-0115-4d92-b670-25276a451845)
Screencap of potential solution:
![image](https://github.com/user-attachments/assets/b2472b93-dab4-455e-9c6e-c24e508de03d)

### What you think should happen instead

Read `name` from `test_node` directly rather than from the `test_metadata` field. Not sure how to ensure backwards compatibility with previous DBT versions.

### How to reproduce

- install `openlineage-dbt==1.23.0`
- install `dbt-core==1.8.6`. 
- run `dbt-ol test`

### Do you plan to make this contribution yourself?

- [X] I am interested in doing this work

**Comment by mobuchowski** [comment]
I think this is first time they've broken compatibility since 1.0. Thanks for catching this up.
