### ISSUE TITLE
[BUG] Delta 3.x support

### ISSUE THREAD

**Issue by Jorricks** [OpenLineage/OpenLineage#3246]
### OpenLineage integration/client

Java client, Other

### OpenLineage version

OpenLineage==1.19.0

### Technology and package versions

I am using the 'acryl-spark-lineage' integration which uses OpenLineage to extract information and ingest into Datahub
https://github.com/datahub-project/datahub/tree/master/metadata-integration/java/acryl-spark-lineage

### Environment configuration

Configured as a SparkListener for Spark on Kubernetes using
- Spark 3.5.2
- Delta 3.2.0

### Problem details

When trying to run the Spark listener for a simple Delta job, I get the following exception;

```
java.lang.NoSuchMethodError: org.apache.spark.sql.delta.catalog.DeltaTableV2.snapshot()Lorg/apache/spark/sql/delta/Snapshot;
at io.openlineage.spark3.agent.lifecycle.plan.catalog.DeltaHandler.getDatasetVersion(DeltaHandler.java:98)
at io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3.getDatasetVersion(CatalogUtils3.java:100)
...
```

### How to reproduce

The incompatibility appears to be with Delta 3.0+.
- In Delta 3.2.1 you should use [initialSnapshot](https://github.com/delta-io/delta/blob/v3.2.1/spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala#L138)
- In Delta 2.0.0 it used to be [snapshot](https://github.com/delta-io/delta/blob/v2.0.0/core/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaTableV2.scala#L102)

In OpenLineage codebase, we assume the `snapshot()` is available here;
- https://github.com/OpenLineage/OpenLineage/blob/e1f41b28b2fad3565463299899cbc33ca9d598e5/integration/spark/spark3/src/main/java/io/openlineage/spark3/agent/lifecycle/plan/catalog/DeltaHandler.java#L98

### Do you plan to make this contribution yourself?

- [ ] I am interested in doing this work

**Comment by mobuchowski** [comment]
@Jorricks please report the issue to `acryl-spark-lineage` repository - we have no control over forks.

**Comment by Jorricks** [comment]
> @Jorricks please report the issue to `acryl-spark-lineage` repository - we have no control over forks.

Hey @mobuchowski,

Thanks for looking at my issue. I think you misunderstood what I indicated though.
If you look at the code samples I provided, the issue in not in `acryl-spark-lineage` but the lack of support in OpenLineage for Delta 3.+. Therefore, I'd expect anyone else using OpenLineage with a more recent delta version to face the same issues. 
Also when you check the Gradle configuration, we don't have any Delta 3.+, we only have Delta 2.+ configurations.

**Comment by mobuchowski** [comment]
@Jorricks sorry for misunderstanding - I get the issue now.

**Comment by pawel-big-lebowski** [comment]
@Jorricks yes, I think you're right. 

What we could do is: 
 * make spark35 submodule depend on delta 4.0
 * implement new version of DeltaHandler within spark35
 * extend `DatasetBuilderFactory` with `getCatalogHandlers` method
 * make `io.openlineage.spark3.agent.lifecycle.plan.catalog.CatalogUtils3#getHandlers` use datasetBuilderFactory to create catalog handlers list
 * implement  `getCatalogHandlers` method in a way that it detects delta version and loads proper handler. 

Another approach, we sometimes did in the past but, is to use reflection in `DeltaHandler` to check if methods exists and if not, use reflection to call another method.
