### ISSUE TITLE
[PROPOSAL] Add standard python client

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#33]
**Purpose:**
A lot of data projects are written in Python.
Having standard Python client would both implementation of OpenLineage from both sides - of 
event producers, who don't need to write their own clients, and from consumers, who can 
use it for tests. Another benefit of having standard client is increased conformance to schema.

**Proposed implementation**
In future, the best way to keep clients conformant to the spec would be to autogenerate them.
In scope of this proposal would be to add simple handwritten client using requests library.

**Comment by julienledem** [comment]
I think this is a great idea to get started.

**Comment by mobuchowski** [comment]
https://github.com/OpenLineage/OpenLineage/pull/34 and https://github.com/OpenLineage/OpenLineage/pull/48
