### ISSUE TITLE
[INTEGRATION] Add init script for Databricks cluster bootstrapping

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#333]
Databricks requires an init script to configure OpenLineage collection from running Spark jobs- the SparkSession is already initialized before a notebook or job is started, so there is no opportunity to configure collection at the job level. 

An untested, but likely usable script is below
```bash
#!/bin/bash

cp /dbfs/FileStore/jars/openlineage_spark_0_2_2.jar /mnt/driver-daemon/jars/

cat << EOL > /databricks/driver/conf/openlineage.conf
[driver] {
    "spark.jars" = "/mnt/driver-daemon/jars/openlineage_spark_0_2_2.jar"
    "spark.extraListeners" = "com.databricks.backend.daemon.driver.DBCEventLoggingListener,io.openlineage.spark.agent.OpenLineageSparkListener"
    "spark.openlineage.url" = "https://api.staging.datakin.com/"
    "spark.openlineage.apiKey" = "abcdefgrzx54pcp3rc9wv01qdehbe9"
    "spark.openlineage.namespace" = "databricks-testing"
}
EOL
```

**Comment by wjohnson** [comment]
Can I ask what `com.databricks.backend.daemon.driver.DBCEventLoggingListener` is used for? I haven't seen that one in other installs of extra listeners.
