### ISSUE TITLE
[PROPOSAL] Add a design doc process for proposals

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#336]
**Purpose:**
Add a design doc section for proposals. The process would be the following:
 - open an issue with the "PROPOSAL" template
 - if the scope warrants it create a PR to add a proposal doc.
 - have the PR approved
 - Once the proposal is accepted you can open another issue for the implementation.

**Proposed implementation**
- Proposals live under OpenLineage/OpenLineage/proposals
- one folder per design (includes images and the proposal document)
- the proposal is keyed by the github issue id: "/proposals/{github issue id}/{short description}.md"
- each doc has a header with:
   - Status: APPROVED | IN PROGRESS | RELEASED
   - Author:
   - Created: 
   - issue tracker: #xxx
- assignees for reviews will be in the issue itself
- community can vote on the issue
```
---
Status: Proposal
Author: 
Created: 
Issue: 
---
```

**Comment by collado-mike** [comment]
I like the process. Some suggestions I would make are

1. If the design doc PR is in a separate branch, can we assume that `APPROVED` status is implied when the doc is merged into `main`?
2. Github [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) could help track the status of the proposal automatically. Perhaps the proposal, once accepted, can link to a milestone where all relevant tasks are collected and we can use a badge (e.g., ![this badge](https://badgen.net/github/milestones/chrislgarry/Apollo-11/1) )

**Comment by julienledem** [comment]
> We should skip CI if pull request modifies only files under `/proposal` directory.

That makes sense: Do you know how to do that?

**Comment by julienledem** [comment]
> I like the process. Some suggestions I would make are
> 
> 1. If the design doc PR is in a separate branch, can we assume that `APPROVED` status is implied when the doc is merged into `main`?
> 2. Github [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) could help track the status of the proposal automatically. Perhaps the proposal, once accepted, can link to a milestone where all relevant tasks are collected and we can use a badge (e.g., ![this badge](https://camo.githubusercontent.com/3c31a5bb010ed9673d122680e26ed4a4aa39855ed5d920ad947efc2436d58f3e/68747470733a2f2f62616467656e2e6e65742f6769746875622f6d696c6573746f6e65732f63687269736c67617272792f41706f6c6c6f2d31312f31) )

I have updated a PR that takes this into account. I would thin that the link to the milestone should go in the ticket itself.
