### ISSUE TITLE
[PROPOSAL] Dataset version facet

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#35]
**Purpose:**
Many databases have explicit versioning in place for datasets. It is highly desirable to track the specific version of the dataset if it is known at consumption/generation time. Rather than relying on the service to correctly tie job inputs to specific versions of a dataset, the client should be allowed to report that information if it is available.

**Proposed implementation**
A dataset version facet may be sufficient to report dataset version information, if it exists. Custom facets can be used to include any database specific version information that may exist, while the minimum required fields should include a versionName string field.

**Comment by julienledem** [comment]
Thank you @collado-mike That makes sense. Could you provide specific examples of databases and what the facet would look like?

**Comment by collado-mike** [comment]
Sure- Apache Iceberg (https://iceberg.apache.org/spark/#time-travel ) and Databricks' Delta Lake (https://docs.delta.io/0.3.0/delta-batch.html#query-an-older-snapshot-of-a-table-time-travel ) are two systems that allow interacting with a dataset as of a specific version. I've also worked with a similar internal system previously.

I suppose we may need to disambiguate between dataset structure changes and content changes. I was thinking specifically of the snapshot version- Job X produces Snapshot A, which is consumed by Job Y- without considering structural changes to the dataset. 

The proposed change for the schema would be

```json
    "Dataset": {
      "type": "object",
      "properties": {
        "namespace": {
          "description": "The namespace containing that dataset",
          "type": "string",
          "example": "my-datasource-namespace"
        },
        "name": {
          "description": "The unique name for that dataset within that namespace",
          "type": "string",
          "example": "instance.schema.table"
        },
        "facets": {
          "description": "The facets for this dataset",
          "type": "object",
          "properties": {
            "documentation": {
              "$ref": "#/definitions/DocumentationDatasetFacet"
            },
            "schema": {
              "$ref": "#/definitions/SchemaDatasetFacet"
            },
            "dataSource": {
              "$ref": "#/definitions/DatasourceDatasetFacet"
            },
            "datasetVersion": {
              "$ref": "#/definitions/DatasetVersionFacet"
            }
          },
          "additionalProperties": {
            "$ref": "#/definitions/CustomFacet"
          }
        }
      },
      "required": [
        "namespace",
        "name"
      ]
    },
    "DatasetVersionFacet": {
      "allOf": [
        {
          "$ref": "#/definitions/BaseFacet"
        },
        {
          "type": "object",
          "properties": {
            "version": {
              "description": "The version of the dataset.",
              "type": "string"
            }
          },
          "additionalProperties": true,
          "required": [
            "version"
          ]
        }
      ],
      "type": "object"
    }
```

I think structural changes may already be adequately addressed by the `SchemaDatasetFacet`, which the lineage service can use to detect new versions of the dataset structure.

**Comment by mobuchowski** [comment]
Nit: I think `VersionDatasetFacet` fits our facet naming convention better, since last word before facet indicates where the facet is attached, as in this case, Dataset. If not, then *correct* name would be `DatasetVersionDatasetFacet`, and that's redundant.

**Comment by collado-mike** [comment]
Despite the redundancy, I think `DatasetVersionDatasetFacet` is a better choice here.
