### ISSUE TITLE
[INTEGRATION] dbt spark adapter

### ISSUE THREAD

**Issue by dvirgiln** [OpenLineage/OpenLineage#363]
**Integration target:**
https://pypi.org/project/dbt-spark

NotImplementedError: Only 'snowflake', 'bigquery', and 'redshift' adapters. Passed spark

**Proposed implementation**
It would be good to have dbt spark adapter and as well Athena. But specially spark one, as Athena is more experimental.

In our company we are thinking to use OpenLineage, but we use DBT Spark adapter mainly. We are starting using as well Athena adapter.

**Comment by julienledem** [comment]
I think it makes sense to support the dbt adapters in the dbt integration.
@dvirgiln should we close #364 as a duplicate?

**Comment by julienledem** [comment]
@mobuchowski eventually this would also be the parent to a spark run that would setup the spark integration but we are not there yet.

**Comment by mobuchowski** [comment]
I agree. We don't have an option to automatically run data yet.
