### ISSUE TITLE
[PROPOSAL] Spark dbt adapter

### ISSUE THREAD

**Issue by dvirgiln** [OpenLineage/OpenLineage#364]
Integration target:
https://pypi.org/project/dbt-spark

NotImplementedError: Only 'snowflake', 'bigquery', and 'redshift' adapters. Passed spark

Proposed implementation
It would be good to have dbt spark adapter and as well Athena. But specially spark one, as Athena is more experimental.

In our company we are thinking to use OpenLineage, but we use DBT Spark adapter mainly. We are starting using as well Athena adapter.

**Comment by mobuchowski** [comment]
Closed as duplicate https://github.com/OpenLineage/OpenLineage/issues/363
