### ISSUE TITLE
[INTEGRATION][Spark] Cover Command in org.apache.spark.sql.catalyst.plans.logical

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#368]
Implementations of Command in org.apache.spark.sql.catalyst.plans.logical
                    

- [x]   ~V2WriteCommand~ -> trait
- [x]   AppendData (depends on provider)
- [x]   OverwriteByExpression -> PR #461
- [x]   OverwritePartitionsDynamic -> PR #461 
- [x]   CreateTableAsSelect
- [ ]   ReplaceTableAsSelect -> PR #463
- [ ]   DeleteFromTable -> PR #463
- [ ]   UpdateTable -> PR #463
- [ ]   MergeIntoTable -> PR #463
- [ ]   DropTable -> waiting for other PR
- [X]   ~NoopDropTable~ -> no operation
- [ ]   AlterTable -> to be merged
- [X]   ~RenameTable~ -> not implemented in iceberg/delta
- [X]   ~AlterTableAddPartition~ -> not implemented in iceberg/delta
- [X]   ~AlterTableDropPartition~ -> not implemented in iceberg/delta
- [X]   ~TruncateTable~  -> not implemented in iceberg/delta

**Comment by harishsune** [comment]
@mobuchowski  I have verified AppendData logical plan, please let me know if more details needs to be added.

**Comment by harishsune** [comment]
@mobuchowski I have verified all remaining logical plans in this issue,  please let me know if more details needs to be added.
