### ISSUE TITLE
airflow: Consider using manual inlets/outlets as a fallback for automatic extractor mechanism

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#384]
There are way more operators than we can reasonably cover. Consider adding manual fallback mechanism that would cover cases where we don't have any extractors. 

Advantage of this approach is that it's generally easier for users to annotate dag than to modify it to use OpenLineage client manually. 

Disadvantage is that it might not work with future mechanism: https://github.com/apache/airflow/issues/17984

**Comment by dvirgiln** [comment]
We are trying to integrate Airflow with Marquez using Open Lineage.

We are using Operators that have not an extractor. Majority of our operators are custom operators, or Python operators. 

We would like to be able to define inlets and outlets in our dags, and then being able to see lineage of our jobs. Relationship between different jobs we have.

For example we have 90 dags. Every dag generates some datasets and has some datasets as inputs. 

If we define correctly our tasks with inlets and outlets in all the dags, we would be able to have a big graph with all the datasets and how they relate between each other. 

This is how i see lineage and is very close to the comment done by @ashb in https://github.com/apache/airflow/issues/17984

**Comment by vietvudanh** [comment]
I am also interested in using Airflow's default linage support using inlets/outlets. Most of our task are BashOperator for spark jobs; writing to HDFS/RMDBS. Therefore the only way I can think of is defining metadata directly in Airflow task; not using extractor.
