### ISSUE TITLE
[INTEGRATION][Spark] heuristically filter out events that operate on metadata

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#423]
Some providers, like Delta Lake do things like running queries on metadata to figure out what files should be read for a particular version of a Delta table. To not emit events that do not correspond to actions done on data (not metadata) we need to filter those out. 

However, we can't just blacklist entire LogicalPlans, because they are often used in some other way. For example, when working on a notebook. The solution to that would be to implement blacklisting of particular LogicalPlan implementation only when there is already job running in that spark session. 

The only downside of this solution is that Spark allows multiple threads to run jobs to run in the same Spark session. That means our solution would not emit events for those parallel jobs when they match blacklist. However, the probability of that affecting real users is small. Long-running Spark session is nearly always used as prototyping or development tool, and production jobs nearly always create their own Spark session. For example, it would not affect jobs submitted via `spark-submit`.

Candidates for blacklisting are 
```
Aggregate
LogicalRelation
LocalRelation
GlobalLimit
```
Maybe more, to check by running some Delta jobs.

Example of Delta spawning multiple jobs with metadata events:

```
scala> spark.sql("CREATE TABLE tbl USING delta AS SELECT * FROM tmp")
21/11/09 19:01:46 WARN SparkSQLExecutionContext: SparkListenerSQLExecutionStart - executionId: 3
21/11/09 19:01:46 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.CreateTableAsSelect
21/11/09 19:01:46 WARN SparkSQLExecutionContext: SparkListenerSQLExecutionStart - executionId: 4
21/11/09 19:01:46 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.LocalRelation
21/11/09 19:01:46 WARN SparkSQLExecutionContext: SparkListenerJobStart - executionId: 4
21/11/09 19:01:46 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.LocalRelation
21/11/09 19:01:47 WARN SparkSQLExecutionContext: SparkListenerJobEnd - executionId: 4
21/11/09 19:01:47 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.LocalRelation
21/11/09 19:01:47 WARN SparkSQLExecutionContext: SparkListenerSQLExecutionEnd - executionId: 4
21/11/09 19:01:47 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.LocalRelation
21/11/09 19:01:48 WARN SparkSQLExecutionContext: SparkListenerSQLExecutionStart - executionId: 5
21/11/09 19:01:48 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.Aggregate
21/11/09 19:01:48 WARN SparkSQLExecutionContext: SparkListenerJobStart - executionId: 5
21/11/09 19:01:48 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.Aggregate
21/11/09 19:01:49 WARN SparkSQLExecutionContext: SparkListenerJobEnd - executionId: 5
21/11/09 19:01:49 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.Aggregate
21/11/09 19:01:49 WARN SparkSQLExecutionContext: SparkListenerSQLExecutionEnd - executionId: 5
21/11/09 19:01:49 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.Aggregate
21/11/09 19:01:49 WARN SparkSQLExecutionContext: SparkListenerSQLExecutionEnd - executionId: 3
21/11/09 19:01:49 WARN SparkSQLExecutionContext: org.apache.spark.sql.catalyst.plans.logical.CreateTableAsSelect
```

**Comment by wjohnson** [comment]
I would like to add a couple candidates that show up in Databricks to this list:

`org.apache.spark.sql.execution.command.AddJarCommand`
`org.apache.spark.sql.execution.command.ShowTablesCommand`

These just spew information out into the log and muddy the waters.  It would be wonderful to ignore these.

**Comment by mobuchowski** [comment]
Superseded by https://github.com/OpenLineage/OpenLineage/pull/905 https://github.com/OpenLineage/OpenLineage/issues/628 - if still needed, then separate issues is required.
