### ISSUE TITLE
Production ?

### ISSUE THREAD

**Issue by rizplate** [OpenLineage/OpenLineage#433]
is any company using it in production?

what are the performance characteristics

I only see 2 or 3 main active committers, is it normal?

**Comment by wjohnson** [comment]
@rizplate - You can take a look at the [OpenLineage blog](https://openlineage.io/blog) which has several talks and webinars.

The most recent one is from [Northwestern Mutual](https://openlineage.io/blog/openlineage-at-northwestern-mutual/) and is a great read.
