### ISSUE TITLE
[INTEGRATION][Spark] provide physical location of a table facet in case we're using logical table name

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#435]
When dealing with a logical Hive table, we've decided to use logical Hive table name as a dataset name. In some other cases, some other job - not necessarily Spark one - might deal with this dataset by directly knowing it's physical location. In this case we'll have the same dataset known by two different names in different namespaces.

To make sure those datasets can be "linked" by OpenLineage consumers, when available, we should provide additional facet (`PhysicalLocationFacet`?) that indicates physical location at a storage system (like `hdfs`, `s3` etc) or other underlying storage mechanism.

Make sure to update Naming.md to standarize how we're naming hive dataset.

**Comment by wjohnson** [comment]
This is a great idea and would be very helpful for our work integrating OpenLineage with Apache Atlas.

**Comment by pawel-big-lebowski** [comment]
One could also consider extending `StorageDatasetFacet` to contain a field with such an information -> https://github.com/OpenLineage/OpenLineage/blob/main/spec/facets/StorageDatasetFacet.json

**Comment by georgeliang0821** [comment]
I have lot of customers using Delta Table on Spark (Databricks), we met the challenge that the OpenLineage might not be able to support SQL table name. May I draw your immediate attention please to consider prioritize this enhancement, thanks.

**Comment by wjohnson** [comment]
@mobuchowski - In what cases does OpenLineage currently report the hive table name?

I couldn't find an example in the unit / integration tests and the [Naming](https://github.com/OpenLineage/OpenLineage/blob/main/spec/Naming.md) guide does not seem to include Hive.

`spark.sql("SELECT * FROM tableName") ` appears to return the physical path rather than the Hive table name. Is that expected or am I just getting a different experience because I'm using Databricks?

**Comment by mobuchowski** [comment]
@wjohnson I think this is also about changing that 😉 a valid point though  - modified issue to indicate that.

@georgeliang0821 this issue shouldn't modify anything regarding Delta Lake AFAIK, just hive for now

**Comment by mobuchowski** [comment]
Also, as you see, this is not a fresh issue - it was made around time when we were filling gaps in Hive coverage with @pawel-big-lebowski - would be easier to do back then rather than now when you're using it already 😞

**Comment by collado-mike** [comment]
I know there's a PR open for this, but I'm wondering whether it is better to include the physical location as a facet or the Hive table information. Assuming a dataset is read outside of Hive (e.g., as in a Hive External Table), the physical location means lineage is immediately established with no work on the server side. If, however, we store physical location as a facet, the server has to know to look at that facet and determine whether there is already an existing dataset at that location.

**Comment by wjohnson** [comment]
> I know there's a PR open for this, but I'm wondering whether it is better to include the physical location as a facet or the Hive table information. Assuming a dataset is read outside of Hive (e.g., as in a Hive External Table), the physical location means lineage is immediately established with no work on the server side. If, however, we store physical location as a facet, the server has to know to look at that facet and determine whether there is already an existing dataset at that location.

I think that's the behavior I'd want too.  Ideally, we could link to the table identifier but still have the physical file path.

* Query: `SELECT * FROM table1` 
* If tabl1 is a managed table
    * name: `table1`
    * namespace `/usr/hive/warehouse`
* If table1 is an external table
    * name: 'someFoldername`
    * namespace: `(abfss|s3|wasb|file|dbfs):/path/to/`
    * facet: `TableIdentifier: default.table1`

**Comment by pawel-big-lebowski** [comment]
Let me sum up my understanding of the discussion above. Some folks may prefer to identify datasets by its physical location, some may want to use logical / relational identifiers like database & table. 

We cannot please them all as we do have just two fields: name & namespace. There are two possible solutions: 
1. Identify datasets by physical location. 
- Introduce extra facet (`CatalogIdentifierFacet`) to contain catalog/datbase/table.
- Modify existing behaviour of the Spark integration for V2 relations to have identifier containing a path instead of table name as currently. Include `CatalogIdentifierFacet` in OL event. 
 - No extra work on backend is required to link datasets. 
 - After a version switch, users may experience having the same datasets identified in a different way. 

2. Introduce `PhysicalLocationFacet` and don't change the current behaviour and 
 - naming convention will stay insonsistent but won't get modified (possible mess in Marquez for current users)
 - `PhysicalLocationFacet` will be always sent

 My initial approach was to go with `2.` in order not to change the existing behavior. 
 @wjohnson  and @collado-mike  are opting for `1.` Right? 
 What about @mobuchowski ?

**Comment by pawel-big-lebowski** [comment]
Let's first describe the currently implemented algorithm to obtain `DatasetIdentifier`. There are two options:
1. If a table is accessed with V2 table API, then `DatasetIdentifer` is evaluated within one of three catalog handlers: 'IcebergHandler', 'DeltaHandler' or 'DatabricksDeltaHandler' (which is pretty similar to 'DeltaHandler'). Each handler implements a method:
```
 public DatasetIdentifier getDatasetIdentifier(
      SparkSession session,
      TableCatalog tableCatalog,
      Identifier identifier,
      Map<String, String> properties)
```
Delta handlers always return a location `path` of a table. `IcebergHandler` returns different results based on the `spark.sql.catalog.<catalogName>.type` which can be `hive` or `hadoop`. In case of `hadoop` location path is used to create `DatasetIdentifier`. In case of `hive`, it is checked if a config field `spark.sql.catalog.uri` is defined. If both conditions are met, then `DatasetIdentifier` containing table name is returned  like `{"name": "database.schema.table", "namespace": "hive://metastore-host:10001"}`).

2. For non v2 tables, methods in `PathUtils` are used to obtain `DatasetIdentifier`. Some of them like `fromPath` or `fromUri` return location identifier but there is a method `fromCatalogTable` which verifies if hive support is enabled and if config entry `spark.sql.hive.metastore.uris` is set. If so, metastore uri enriched with table qualifed name is returned. 

To sum up a database represantation identifier is returned only in two scenarios: 
 * iceberg table with `hive` catalog type,
 * hive enabled Spark session with external metastore uris defined in config.

My initial approach was to add `physicalLocation` facet everywhere which does not change the existing behavior of the code, but requires linking datasets on the backend side and may be overkill as most of the time `physicalLocation` is equal to `DatasetIdentifier`

@wjohnson  and @collado-mike are opting for the approach where we replace existing behavior of the two scenarios with location dataset identifier and introduce extra facet (like `TableIdentifierFacet`) which will contain database and table names (right?). If we are fine with modifying existing behavior, this approach looks cleaner to me either.

**Comment by wjohnson** [comment]
> @wjohnson and @collado-mike are opting for the approach where we replace existing behavior of the two scenarios with location dataset identifier and introduce extra facet (like `TableIdentifierFacet`) which will contain database and table names (right?). If we are fine with modifying existing behavior, this approach looks cleaner to me either.

Thank you for this excellent summary, Pawel!  A good analysis like this belongs in the docs page!

You described exactly what I was looking for in this last section.  I just don't know how to accomplish it.

**Comment by mobuchowski** [comment]
@wjohnson looked at this again, and my opinion has changed. 
I think we also need to take this discussion outside of just Spark context 😉 
Why? Because we also want to support them from other integrations, like Flink integration support for Iceberg.

We generally have three types of systems: 

1. Ones that refer to their datasets by logical names - for example, the traditional relational databases which follow the schema `dataset.table.name` - sometimes changing it by dropping schema like MySQL for example.
2. Others refer to the datasets by physical locations - for example 
3. There is also third type, which can have both logical and physical names. For example [Delta Lake](https://docs.delta.io/latest/delta-batch.html#-ddlcreatetable) and [Iceberg](https://iceberg.apache.org/docs/latest/flink/#creating-catalogs-and-using-catalogs).

In that case, we need to take a look what actual system does: for example, [Delta supports two table types](https://docs.delta.io/latest/delta-batch.html#create-a-table) but actually clearly warns against relying just on the catalog: 

```
The metastore is not the source of truth about the latest information of a Delta table. In fact, the table definition in the metastore may not contain all the metadata like schema and properties. 
It contains the location of the table, and the table’s transaction log at the location is the source of truth.
If you query the metastore from a system that is not aware of this Delta-specific customization, you may see incomplete or stale table information.
```

Iceberg in the face always refers to the datasets as `catalog.schema.table` and requires using catalogs when using Spark SQL, but the catalogs aren't that important too - multiple ones can point to the same location and always having catalog means you can consistently manage metadata without different table types.

In those systems the actual location is most important and it's what defines dataset, so we definitely should refer to it as actual dataset namespace and name. Any logical name should be an additional info. So @pawel-big-lebowski is definitely right in the last paragraph, but we should migrate from database represantation identifier in Iceberg/Hive and just Hive if doable. 

Now, regarding databricks... it's more [complex?](https://docs.databricks.com/lakehouse/data-objects.html)
Looks like it just adds layer on top of Spark complexity with Unity Catalog. I'm not sure if we need to do anything with it yet, and that Spark based approach we have today will work.
