### ISSUE TITLE
[PROPOSAL] Add generic ErrorMessageRunFacet

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#446]
On execution failure, multiple systems provide text-based error messages, like dbt:

```
22:52:07  Database Error in model customers (models/customers.sql)
22:52:07    Syntax error: Expected "(" or keyword SELECT or keyword WITH but got identifier "PLEASE_REMOVE" at [56:12]
22:52:07    compiled SQL at target/run/jaffle_shop/models/customers.sql
```

Airflow:

```
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
```

Spark:
```
org.apache.spark.sql.AnalysisException: Table or view not found: wrong_table_name; line 1 pos 14;
```

We should add simple `ErrorMessageRunFacet` to capture human-readable messages. Currently, we have some custom facets for those for `BigQuery` and `Spark`

Proposed schema would look like that:

```json
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$id" : "https://openlineage.io/spec/facets/1-0-0/ErrorRunFacet.json",
  "$defs" : {
    "ErrorMessageRunFacet" : {
      "allOf" : [ {
        "$ref" : "https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet"
      }, {
        "type" : "object",
        "properties" : {
          "message" : {
            "description" : "A human-readable string representing error message generated by observed system",
            "type" : "string",
            "example" : "org.apache.spark.sql.AnalysisException: Table or view not found: wrong_table_name; line 1 pos 14"
          },
          "stackTrace" : {
            "description" : "A language-specific stack trace generated by observed system",
            "type" : "string",
            "example" : "Exception in thread \"main\" java.lang.RuntimeException: A test exception\nat io.openlineage.SomeClass.method(SomeClass.java:13)\nat io.openlineage.SomeClass.anotherMethod(SomeClass.java:9)"
          }
        },
        "required" : [ "message" ]
      } ],
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "error" : {
      "$ref" : "#/$defs/ErrorMessageRunFacet"
    }
  }
}
```

**Comment by collado-mike** [comment]
This makes sense to me. This may be just the way my brain reads things, but when I see `ErrorRunFacet`, I assume it is a facet for an "error run". I think the naming is following the convention of including the type of facet in the name (i.e., a `RunFacet` in this case) - maybe consider something like `ErrorMessageRunFacet` or `ErrorInfoRunFacet` just to break up the "error" and "run" portion of the name.

**Comment by mobuchowski** [comment]
Agreed, I like `ErrorMessageRunFacet`. Updated schema in a top post.

**Comment by collado-mike** [comment]
Looks great!

**Comment by gvacaliuc** [comment]
thoughts on extending this proposal to include the programming language?  similar to: https://github.com/snowplow/iglu-central/blob/master/schemas/com.snowplowanalytics.snowplow/application_error/jsonschema/1-0-2

**Comment by mobuchowski** [comment]
@gvacaliuc that's a cool idea!

**Comment by denimalpaca** [comment]
@harels why is this in new issues? Looks like it can be closed with the above PR merged.

**Comment by harels** [comment]
agree, closing this issue
