### ISSUE TITLE
[PROPOSAL][SPARK] Support Databricks Synapse Connector

### ISSUE THREAD

**Issue by wjohnson** [OpenLineage/OpenLineage#452]
**Purpose:**

We would like to extend OpenLineage's Spark integration to work with the [Azure Synapse (formerly known as SQL Data Warehouse)](https://docs.microsoft.com/en-us/azure/databricks/data/data-sources/azure/synapse-analytics) in the Databricks Environment. Azure Databricks offers this proprietary package only in the Databricks runtime (across at least Azure and AWS).

This would enable people using Databricks, OpenLineage, and Azure Synapse to observe the input and output to their spark jobs.

**Proposed implementation**

Databricks' Synapse connector extends a Base Relation which works with a JDBC connection to Azure Synapse. As a result, I am proposing that we add a SqlDWRelationVisitor much in the same way as there is a BigQueryNodeVisitor.

A new namespace of "synapsedatabricks" would be added.  Why "synapsedatabricks" and not "synapse"? Because this connector is only found in Databricks and [other Synapse connectors are available in different environments](https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/synapse-spark-sql-pool-import-export). I think the namespace "synapse" should be reserved for a Microsoft derived connector if it ever is implemented for DataSourceV2Relations.

A few caveats:

* The package is proprietary and the SqlDWRelation is a private class.
* As a result, a small use of reflection is necessary to access the underlying `tableNameOrSubquery` class that contains the actual table name.
* In addition, we'd want to extract out the JDBC URL to get the server and database name for the Synapse database. This also requires a bit of reflection.

Lastly, this effort would be made easier with the acceptance / completion of the proposal in #437 .

**Comment by collado-mike** [comment]
This sounds good to me. Re: the reference to #437, is the proposal to include this visitor in the core OpenLineage Spark library or to create an extension package?

**Comment by wjohnson** [comment]
Ah!  Good call, @collado-mike I have a PR ready to go that would be included in the core OpenLineage Spark library (since I was working on it prior to 437 being complete).

In addition, since this is *Databricks* I think it would be relevant for more than just Microsoft customers (although it's geared toward using Databricks to connect with an Azure / Microsoft product).

I would ask for your input.  Would you rather see an extension package (then I guess I wouldn't actually put out a PR to you guys here, right) or keep this as part of OpenLineage's Databricks support?

**Comment by collado-mike** [comment]
If you have an implementation ready, let's go ahead and add it here. We can always move it to a separate package after #437 is merged. I assume we'll need to add a dependency for the `SqlDWRelation` class? Or is this purely reflection based? If we need to add a dependency, be sure to mark it as `compileOnly`

**Comment by wjohnson** [comment]
Thank you for the guidance, @collado-mike ! I've added a PR.  It is all reflection based so no additional dependency.

I would definitely appreciate guidance on what you guys would want to see on tests especially given the cloud infrastructure required.
