### ISSUE TITLE
[PROPOSAL][SPARK] Ability to produce a generic facet to get environment information.

### ISSUE THREAD

**Issue by harishsune** [OpenLineage/OpenLineage#464]
Below are some of the examples Databricks properties which facet should contain:

- "orgId"
- "spark.databricks.clusterUsageTags.clusterOwnerOrgId"
- "spark.databricks.notebook.path"
- "spark.databricks.job.type"
- "spark.databricks.job.id"
- "spark.databricks.job.runId"
- "user"
- "userId"
- "spark.databricks.clusterUsageTags.clusterName"
- "spark.databricks.clusterUsageTags.azureSubscriptionId"

# Implementation

Create a new Facet class called as EnvironmentFacet

```
public class EnvironmentFacet extends OpenLineage.DefaultRunFacet {  
    @JsonProperty("environment-properties")  
    private HashMap<String, Object> properties;  
  
    public EnvironmentFacet(HashMap<String, Object> environmentDetails) {  
        super(OpenLineageClient.OPEN_LINEAGE_CLIENT_URI);  
        this.properties = environmentDetails;  
    }  
}
```

Add Method in OpenLineageSparkListener.java which will run on onJobStart to collect information about Databricks environment.
To achieve this we will need to introduce a new property in SparkSQLExecutionContext.

```
public HashMap<String, Object> EnvironmentProperties;
```

this property will be initialize in OpenLineageSparkListener in sparkSQLExecStart() and get value from getDatabricksEnvironmentalAttributes()

```
private HashMap<String, Object> getDatabricksEnvironmentalAttributes(SparkListenerJobStart jobStart){  
  dbProperties = new HashMap<>();  
  List<String> dbPropertiesKeys = Arrays.asList(  
          "orgId",  
          "spark.databricks.clusterUsageTags.clusterOwnerOrgId",  
          "spark.databricks.notebook.path",  
          "spark.databricks.job.type",  
          "spark.databricks.job.id",  
          "spark.databricks.job.runId",  
          "user",  
          "userId",  
          "spark.databricks.clusterUsageTags.clusterName",  
          "spark.databricks.clusterUsageTags.azureSubscriptionId"  
  );  
  
  dbPropertiesKeys.stream().forEach((p) -> {  
    dbProperties.put(p,jobStart.properties().getProperty(p));  
  });  
 
  return dbProperties;  
}
```

After the execution in sparkSQLExecutionContext class inside Start and End event, EnvironmentProperties will be added to event JSON.

```
new SimpleImmutableEntry("environment_properties", environmentFacet),
```

**Comment by mobuchowski** [comment]
@harishsune shouldn't this be specific custom `DatabricksEnvironmentRunFacet`?

Generic (standarized) facets should be created for properties that are generalized over multiple systems, compared to specific improvements for one system.

>this property will be initialize in OpenLineageSparkListener in sparkSQLExecStart() and get value from getDatabricksEnvironmentalAttributes()

I would also make sure that we're running on Databricks, not an standalone Spark cluster before checking for those properties.

Overall, besides those, looks good to me 👍

**Comment by collado-mike** [comment]
I think the `CustomFacetBuilder` interface outlined in https://github.com/OpenLineage/OpenLineage/pull/437 is helpful here. The work for that proposal is almost ready for merge - at that point, I think the `DatabrickEnvironmentRunFacet` definitely makes sense to include, though I'd include it using an instance of `CustomFacetBuilder` rather than having the OpenLineageSparkListener invoke it directly.

**Comment by harishsune** [comment]
Thanks @mobuchowski , @collado-mike, I will take a look at CustomFacetBuilder. The reason I kept it as EnvironmentFacet is because it is only exposing HashMap, we can include any key-value pair which will be based on the environment.

**Comment by harishsune** [comment]
Hi Team, I have included changes using CustomFacetBuilder, please help with the review.
