### ISSUE TITLE
[INTEGRATION][Spark] Include TableStateChangeFacet in non V2 commands

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#466]
When implementing visitors for V2 commands, we introduced TableStateChangeFacet with possible values like: CREATE, DROP, TRUNCATE or OVERWRITE. They may be useful for non V2 commands like the ones #367 or #369. 

Please include table state change facet in implementation of visitor commands of #367 and #369.

**Comment by mr-yusupov** [comment]
Ready to take
