### ISSUE TITLE
spark: logging from openlineage classes does not work

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#477]
Logging from OL classes stopped working after https://github.com/OpenLineage/OpenLineage/commit/138d1a390bbcc2dac102fc1fe3437fea30e8457b with warning on application start:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

Very likely reason for that is slf4j classes relocation: 
```
    relocate 'org.slf4j', 'openlineage.slf4j'
```

Similar issue here: https://github.com/snowflakedb/snowflake-jdbc/issues/16

**Comment by collado-mike** [comment]
Ugh. I vote we remove Slf4j from the bundle and leave it as a normal transitive dependency. Leaving the interface bundled without renaming is asking for a place in the special hell they reserve for people who create these kinds of classpath conflicts
