### ISSUE TITLE
[INTEGRATION][Dagster] Openlineage-Dagster Integration

### ISSUE THREAD

**Issue by dalinkim** [OpenLineage/OpenLineage#489]
Hello, my team would like to contribute to the OpenLineage-Dagster integration work with the following proposal.

## Integration Target:
[Dagster](https://github.com/dagster-io/dagster)

## Proposal:

New _openlineage-dagster_ library that integrates Dagster with OpenLineage for automatic metadata collection 

## Incremental Support:

1. Initial integration handling basic metadata (job runs)
2. Individual “extractor” handling additional metadata (input/output datasets, data quality metrics, and etc.)

## Proposed Implementation:

Dagster uses an [`Executor`](https://docs.dagster.io/deployment/executors#executors) to [`execute()`](https://docs.dagster.io/_apidocs/internals#dagster.Executor.execute) Dagster job (aka pipeline) runs, and each execution yields a stream of [`DagsterEvents`](https://docs.dagster.io/_apidocs/execution#dagster.DagsterEvent) from different stages of the run.

As Dagster supports custom Executor, we can implement a custom `OpenLineageExecutor` that will:
- act as a thin wrapper over an existing implementation of Executor
- translate given [`PipelineRun`](https://docs.dagster.io/_apidocs/internals#dagster.PipelineRun) during execution and emit parent job (pipeline/job-level) RunEvents
- execute steps using its helper (actual) executor
- intercept yielded DagsterEvents, translate, and emit child job (op/step-level) RunEvents
- yield original DagsterEvents

Similar to openlienage-airflow, Dagster-specific `OpenLineageAdapter` can be implemented as a helper.

## Generated OpenLineage Jobs & RunEvents:

With the above initial work, the following jobs and events can be generated.

### Dagster job (pipeline) run -> OpenLineage parent job run

- During execution, `PipelineRun` is available from `PlanOrchestrationContext`, and we can get job/pipeline-level metadata from this PipelineRun and translate it to an OpenLineage event.
- As an example, given `pipeline_run`, a RunEvent may look like,
```python
RunEvent(
    eventType=event_type,
    eventTime=datetime.now().isoformat(),
    run=Run(
        runId=pipeline_run.run_id,
    ),
    job=Job(
        namespace=namespace,
        name=pipeline_run.pipeline_name,
    ),
    producer=PRODUCER,
)
```

### Dagster op (step) run -> OpenLineage child job run

- Assuming "op" is equivalent to "step" at Dagster's low-level, we can identify op-related events from the returned DagsterEvents based on its [`DagsterEventType`](https://docs.dagster.io/_apidocs/execution#dagster.DagsterEventType). For the initial implementation, the following types can be handled.
  - DagsterEventType.STEP_START
  - DagsterEventType.STEP_SUCCESS
  - DagsterEventType.STEP_FAILURE
- Other types may be usable to extract additional metadata.
- As an example, given `dagster_event`, a RunEvent may look like,
```python
RunEvent(
    eventType=event_type,
    eventTime=datetime.now().isoformat(),
    run=self._build_run(
        namespace=namespace,
        run_id=run_id,  # not associated with Dagster
        parent_run_id=dagster_event.logging_tags.get("run_id"),  # pipeline run id
        parent_job_name=dagster_event.logging_tags.get("pipeline_name"),
    ),
    job=self._build_job(
        namespace=namespace,
        job_name=f"{dagster_event.pipeline_name}.{dagster_event.step_key}",
    ),
    producer=PRODUCER,
))
```

## How to Use in Dagster:

OpenLineageExecutor's ExecutorDefinition can be defined at the job-level like below.

```python
from dagster import job, op
from openlineage.dagster.executor import openlineage_executor

@job(executor_def=openlineage_executor)
def a_job():
    
    @op
    def an_op():
        pass
    
    an_op()
```

And the executor is configurable like below as Dagster's "executor config".

```yaml
execution:
  config:
    openlienage:
      url: "https://..."
      api_key: ""
      namespace: "default"
    executor:
      multiprocess_executor:
        max_concurrent: 2
```

---

This proposal is based on limited research and understanding of Dagster, and there may be better alternatives as well that we are happy to discuss over and learn more so any feedback from the community is appreciated as we lay this initial block. Thank you for reviewing and looking forward to further discussions!

**Comment by mobuchowski** [comment]
Thanks @dalinkim for this proposal.
This looks great from OpenLineage side for first implementation. Definitely would be worth checking with Dagster community and developers on what they think about this method.

One small question:
 
>pipeline_run.run_id

is this `run_id` UUID? We have hard requirement for this being an UUID.

**Comment by dalinkim** [comment]
@mobuchowski, thanks for the review and feedback. 
Based on what I've seen, pipeline `run_id` is UUID. [Here](https://github.com/dagster-io/dagster/blob/master/python_modules/dagster/dagster/core/utils.py#L57) is also their util function to generate a new run id as an example.

**Comment by sryza** [comment]
Hi @dalinkim - I'm a Dagster engineer, here to answer any questions you have. It would be awesome to see a Dagster-OpenLineage integration.

A challenge with accomplishing this via a custom executor is that there are already a number of executor implementations that dagster users rely on.  E.g. some use the K8s executor, some use the in-process executor, and some use the multiprocess executor.  If you wanted to maintain that flexibility and also integrate via the executor, you'd need to write an openlineage version of each of those executors.

The way that we've recommended implementing similar integrations in the past is via a Dagster sensor that tails the Dagster event log.  Something like:
```
@sensor
def openlineage_sensor(context):
    event_records = context.instance.get_event_records(
        EventRecordsFilter(after_cursor=context.cursor),
        ascending=True,
        limit=5,
    )

    for event_record in event_records:
        event_log_entry = event_record.event_log_entry
        storage_id = event_record.storage_id
        # write relevant contents of the event log entry to OpenLineage

    context.update_cursor(storage_id)
```

**Comment by dalinkim** [comment]
Hi @sryza - Thank you for the feedback and suggestions! We were trying to figure out how to support all existing executors, and this looks like a great alternative approach.

As I just started looking into the sensor capability, I have some initial questions.

**Re: logging & monitoring sensor**
It appears that logger is not available with sensor context. Is that correct and if so, do you have some suggestions on where we can log and monitor the sensor runs themselves?

**Re: parallel sensor run**
There was an old post about sensors not running in parallel. Is that within the scope of a single sensor's runs or all sensors in a given repository? Mainly, trying to understand if this sensor could affect other workflows using other sensors.

**Re: getting event records** 
Based on the suggested approach, I just set up a sensor like below. I confirmed the cursor is getting updated, but `get_event_records()` is always returning the first 5 records (in this example) for some reason. This is from a quick local testing, and I was wondering if there are any additional configurations needed besides running dagster-daemon to test this.

```python
@sensor()
def openlineage_sensor(context: SensorEvaluationContext):
    storage_id = int(context.cursor) if context.cursor else 0
    event_log_records: Iterable[EventLogRecord] = context.instance.get_event_records(
        EventRecordsFilter(after_cursor=last_storage_id),
        ascending=True,
        limit=5,
    )

    for event_log_record in event_log_records:
        # process and emit OpenLineage events
        storage_id = event_log_record.storage_id

    yield SkipReason(f"Last processed storage_id: '{storage_id}'")
    context.update_cursor(str(storage_id))
```

Thanks again for your help.

**Comment by sryza** [comment]
> It appears that logger is not available with sensor context. Is that correct and if so, do you have some suggestions on where we can log and monitor the sensor runs themselves?

Our current recommendation here is just to use standard Python logging. E.g. use a [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler) to log to a rotating set of files on the machine that's running the Dagster daemon. The drawback here of course is that the logs won't appear inside Dagit. That's on our radar, but not something that we're currently prioritizing.  We'd be happy to advise on contributions if that's something you would have bandwidth for.

> There was an old post about sensors not running in parallel. Is that within the scope of a single sensor's runs or all sensors in a given repository? Mainly, trying to understand if this sensor could affect other workflows using other sensors.

That's for all sensors within a given repository. We'd like to ultimately make these run in parallel, but we don't have a timeline for this yet.

> get_event_records() is always returning the first 5 records (in this example) for some reason. 

I noticed that the code you posted refers to a variable, `last_storage_id`, which isn't defined inside it. Is that defined somewhere else? Is that possible what's causing the issue?

**Comment by dalinkim** [comment]
Thank you for the insights.

> I noticed that the code you posted refers to a variable, last_storage_id, which isn't defined inside it. Is that defined somewhere else? Is that possible what's causing the issue?

Sorry for the typo from copying over couple snippets here. I updated the above example to `storage_id`, and the actual sample code did use a single variable, but even so, the returned records were the same on every sensor tick. Also tried changing `after_cursor` with some hard coded value, which seems to have no impact.

**Comment by dalinkim** [comment]
Getting events with record filter is more of a general Dagster sensor question so I can take that to the Dagster slack channel for further troubleshooting. 

Otherwise, this sensor approach is great as it provides access to the full event logs while being less intrusive to Dagster core. If everyone is good, I'll pivot and continue exploring OpenLineage sensor.

**Comment by dalinkim** [comment]
Just to close out the mentioned issue with get_event_records, I was able to resolve it by using ConsolidatedSqliteEventLogStorage.

**Comment by dalinkim** [comment]
@sryza, is optional repository detail for each event available from sensor context? Dagster repository seems comparable with OpenLineage namespace, and I was wondering if it would be possible to support using Dagster repository name as the namespace name.

Similar to Airflow integration work, current plan is to have namespace default to "default" or be defined by `OPENLINEAGE_NAMESPACE` environment variable.

**Comment by dalinkim** [comment]
It looks like we can get PipelineRun by run id and get the optional repository name from ExternalRepositoryOrigin. If appropriate, we can set OpenLineage namespace to optional Dagster repository name, and if not available, default to the behavior noted above. Any feedback is appreciated. Thanks!

**Comment by sryza** [comment]
Hey @dalinkim - using the repository name as the OpenLineage namespace sounds reasonable to me, and fetching the repository name through the PipelineRun -> ExternalRepositoryOrigin sounds like the right way to do that.
