### ISSUE TITLE
[PROPOSAL] Integration tests to verify OpenLineage backend failure doesn't break Airflow

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#496]
**Purpose:**
The philosophy of this project is that failure to report lineage should not have any negative impact on the running application (aside from errors in the logs). We should add some simple integration tests to verify

* No response from server (down)
* Timed out waiting for response from server
* Error response from server (bad input, bad server state)

**Comment by mobuchowski** [comment]
We should also verify that bad configuration - for example, not providing `OPENLINEAGE_URL` does not crash application.
