### ISSUE TITLE
Add license header to source files

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#50]
# SPDX-License-Identifier: Apache-2.0

From LFAI&Data:
> We typically recommend that projects include a short license notice in each project source code file, wherever reasonably possible (e.g., don't worry about this for image files, formats without comments like JSON, etc).
> 
> Adding these notices has several benefits, including improving code reuse in other projects by making sure that the license info travels along with the source code file if it is used elsewhere. They can be easily added using a one-line comment with an SPDX short-form identifier, in the following format (adjusting for the file's particular format for comments):
> 
> ```# SPDX-License-Identifier: Apache-2.0```
> 
> More information on this format is available at https://spdx.dev/ids. It looks like several of the documentation files have these already (correctly with the documentation's CC-BY-4.0 license), so I'm noting this primarily for source code files.

**Comment by mobuchowski** [comment]
https://github.com/OpenLineage/OpenLineage/pull/540
