### ISSUE TITLE
[INTEGRATION] [Airflow] collect the query id in an external id facet

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#517]
When running queries/jobs in external systems (bigquery, snowflake, ...) we should collect the queryid in an "external id" facet.
example:
```
external: {
  id: "xxxxxx-xxxx-xxx",
  source: "snowflake:{account id}"
}
```
the source should match job naming conventions

**Comment by mobuchowski** [comment]
@julienledem why do we need `source` for job facet?

**Comment by julienledem** [comment]
My thinking is that the ids are not always globally unique.
The example I provided is meant to start the discussion but feel free to iterate and improve on it.

**Comment by julienledem** [comment]
This deserves a short description of the parent/child relationship with for example an airflow task parent run and a warehouse SQL child run. Could you create a [proposal](https://github.com/OpenLineage/OpenLineage/tree/main/proposals) with the example of what the facets would look like for the parent and child run?
