### ISSUE TITLE
[QUESTION][Spark]Is Spark 3.2.0 supported?

### ISSUE THREAD

**Issue by Taurus-Le** [OpenLineage/OpenLineage#542]
**Environment:**
1. Spark 3.2.0
2. JDK 11.0.10
3. Hadoop 3.2.2
4. Delta Lake 1.1.0
5. openlineage-spark-0.5.2.jar

**Settings in spark-defaults.conf:**
spark.extraListeners=io.openlineage.spark.agent.OpenLineageSparkListener
spark.openlineage.host=http://192.168.21.8:5000
spark.openlineage.namespace=my_job_namespace

**Question:**
Is Spark 3.2.0 supported? I tried to read a CSV file and write to HDFS using Delta Lake，and yet it did not worked. I got the exception below.
`Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.catalyst.plans.logical.AlterTable`

**Full log**
[Full_stack_trace.log](https://github.com/OpenLineage/OpenLineage/files/8076475/Full_stack_trace.log)

**Comment by mobuchowski** [comment]
Will be in the next release. https://github.com/OpenLineage/OpenLineage/pull/607
