### ISSUE TITLE
[INTEGRATION][Airflow] Add a facet to capture job/run dependencies (a task is dependent on another task in the DAG)

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#552]
In Airflow, tasks in a DAG depend on each other in a workflow.
We want to capture those dependencies.

**Comment by mobuchowski** [comment]
How is that different from ParentRunFacet?

**Comment by julienledem** [comment]
This is different from the parent run. it is the task dependency: 
the task in the DAG that was the predecessor in the workflow

**Comment by kacpermuda** [comment]
I believe this PR should resolve that issue: https://github.com/apache/airflow/pull/39520

**Comment by kacpermuda** [comment]
https://github.com/apache/airflow/pull/39520 has been merged
