### ISSUE TITLE
[INTEGRATION][Flink] Create SchemaDatasetFacet from Avro schema

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#568]
If we detect that Kafka source or sink are using Avro to serialize or deserialize data, we should use it to generate SchemaDatasetFacet.

**Comment by mr-yusupov** [comment]
https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/api/common/typeinfo/TypeInformation.java#L80

**Comment by mr-yusupov** [comment]
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/16818028/155318141-8a9122d1-228c-40e7-a43c-aba9f94d7b3d.png">
