### ISSUE TITLE
spark: missing output dataset schema when using delta format to write in ADLS

### ISSUE THREAD

**Issue by ganeshnikumbh** [OpenLineage/OpenLineage#578]
@collado-mike, @wjohnson  after you fixed and merged #491 , I have been testing it in my environment. Although it has fixed the missing output datasets part, it is missing the schema of the output dataset being written. Please see attached log4j file. 

Please let me know if you need any other details.

[log4j_deltaADLS.txt](https://github.com/OpenLineage/OpenLineage/files/8152565/log4j_deltaADLS.txt)

**Comment by ganeshnikumbh** [comment]
also attached an example output event. If you see the see the schema block in the outputs, the fields are missing

"outputs": [{
		"namespace": "abfss://businesslayer@<adlsaccount>.dfs.core.windows.net",
		"name": "dailyProductSales",
		"facets": {"dataSource": {
				"_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
				"_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet",
				"name": "abfss://businesslayer@<adlsaccount>.dfs.core.windows.net",
				"uri": "abfss://businesslayer@<adlsaccount>.dfs.core.windows.net"
			},
			"schema": {
				"_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
				"_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet",
				"fields": []
			}
		},
		"outputFacets": {
			"outputStatistics": {
				"_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
				"_schemaURL": "https://openlineage.io/spec/facets/1-0-0/OutputStatisticsOutputDatasetFacet.json#/$defs/OutputStatisticsOutputDatasetFacet",
				"rowCount": 0,
				"size": 0
			}
		}
	}]

[openLineageOutput-2022-02-28_09_48_44.564443.txt](https://github.com/OpenLineage/OpenLineage/files/8152616/openLineageOutput-2022-02-28_09_48_44.564443.txt)

**Comment by wjohnson** [comment]
@ganeshnikumbh would you please share a minimum viable pieces of PySpark or Scala spark to replicate this?  In addition, you might consider re-running this command with the latest released version and not use the SNAPSHOT and see if this persists.

**Comment by ganeshnikumbh** [comment]
@wjohnson I tested this with latest version 0.6.1, but the issue still persists. Please see attached notebook file. Below is the code snippet. 

`productSaleDF = spark.sql( """select product.productID,to_date(orders.orderDate) as orderDate,sum(orderDetail.quantity) as totalQuantitySold,
sum(orderDetail.quantity * orderDetail.unitPrice) as totalSalesAmount
from orderDF as orders inner join orderDetailsDF as orderDetail
on orders.orderID = orderDetail.orderID
inner join productDF as product
on orderDetail.productID=product.productID
group by product.productID,to_date(orders.orderDate)
""")    

storagecontainerName= "businesszone"
writepath ="abfss://"+storagecontainerName+"@"+adlsstorageaccountname+".dfs.core.windows.net/dailyProductSales/"

productSaleDF.write.format("delta").mode("overwrite").save(writepath)
print("Done")`

Here is the output. The "fields" are still empty.

`"outputs":[{"namespace":"abfss://businesszone@<adlsstrorageaccount>.dfs.core.windows.net","name":"/dailyProductSale/","facets":{"dataSource":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.1/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet","name":"abfss://businesszone@<adlsstrorageaccount>.dfs.core.windows.net","uri":"abfss://businesszone@<adlsstrorageaccount>.dfs.core.windows.net"},"schema":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.1/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet","fields":[]}},"outputFacets":{}}],"producer":"https://github.com/OpenLineage/OpenLineage/tree/0.6.1/integration/spark","schemaURL":"https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunEvent"}`

[log4jOutput.txt](https://github.com/OpenLineage/OpenLineage/files/8238092/log4jOutput.txt)

**Comment by mobuchowski** [comment]
@ganeshnikumbh is this still happening?

**Comment by kacpermuda** [comment]
Closing this as stale. Feel free to reopen if needed.
