### ISSUE TITLE
Airflow tasks fail when OPENLINEAGE_URL is unreachable

### ISSUE THREAD

**Issue by rossturk** [OpenLineage/OpenLineage#579]
I forgot to set my `OPENLINEAGE_URL` before testing an Airflow DAG and my tasks failed with this error in the log:

```
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/v1/lineage (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x40038c8790>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2022-03-01, 04:50:49 UTC] {local_task_job.py:154} INFO - Task exited with return code 1
```

It occurs to me that an unreachable (or misconfigured) OpenLineage backend should raise *many alarms*, but probably not cause a pipeline to fail.

**Comment by mobuchowski** [comment]
Will be fixed here, I just need review... https://github.com/OpenLineage/OpenLineage/pull/557

**Comment by collado-mike** [comment]
Addressed by https://github.com/OpenLineage/OpenLineage/pull/557
