### ISSUE TITLE
Spec: clarify event order lifecycle

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#599]
Current wording leaves too much interpretation for reader. Try to clarify what is valid sequence of OpenLineage events and what is not.

1. Multiple events of same type other than OTHER.
2. Precedence - can START event be send after COMPLETE event.
3. Mixing COMPLETE/FAIL/ABORT events. 
4. When can we send OTHER events. Just between START/COMPLETE or also in different places.

**Comment by cerveada** [comment]
I am not aware of all other use cases, but for us (spline project) lifecycle like this would make sense:

![openlineage-lifecycle](https://user-images.githubusercontent.com/5530211/157708634-59e21b9c-2f08-457f-a1db-79eedb36e785.png)

- There is a value in having a terminal operation. Otherwise, the server never knows whether the data it has are complete or not, and the same applies to the end user. As a user, I would like to know if the job I see in the UI has all the data sources or there is something still missing.
- Multiple START events are less of a problem, but what is a point of having multiple when OTHER can be used? Also if there is just one I can use it's time to know when the job execution started. If there is multiple which one is the real start time?

**Comment by collado-mike** [comment]
Some additional comments in https://github.com/OpenLineage/OpenLineage/issues/636 . After discussion, we are going to add a `RUNNING` state to the enum.

**Comment by cerveada** [comment]
I implemented [open lineage integration](https://github.com/AbsaOSS/spline-open-lineage) for [spline server](https://absaoss.github.io/spline/). This allows for spline to consume lineage data in open lineage format.

There are some differences between the two APIs. For spline the job data comes in just one message and the data are immutable, there is a second message that is sent once for each job run. This is different in open lineage, where the job data can come in several messages. To overcome the difference the integration is aggregating the messages in Kafka and only after the `COMPLETE` message comes it sends all the data to spline.

There were several undefined things in open lineage api  that may cause problems:
- As mentioned already, there is no guarantee that the `COMPLETE` message is the last one. But I must stop somewhere, so this means any following data will be ignored.
- data source `name` and `namespace` are basically uri that is split in two parts. In spline we just use uri and we are planing to let user later define mapping for what uri's are considered the same datasource on the server side. Open lineage is trying to have some format for each schema (file, Postgres, etc), but at the end the same data source will have different uri depending on if it's accessed from localhost, docker or different network. So I don't think there is any other way to solve this.
- were the data in the output appended or was it overwritten?

**Comment by mobuchowski** [comment]
Great to see that!

>As mentioned already, there is no guarantee that the COMPLETE message is the last one. But I must stop somewhere, 
so this means any following data will be ignored.

Agreed. We'll fix that with adding `RUNNING` to the state enum.

>Open lineage is trying to have some format for each schema (file, Postgres, etc), but at the end the same data source will have different uri depending on if it's accessed from localhost, docker or different network. So I don't think there is any other way to solve this.

We'll try to solve that by providing both physical and logical location: https://github.com/OpenLineage/OpenLineage/issues/435

Ultimately, there are cases where we won't have 100% unique and correct names for all the datasets, if you rely on something like network shares instead of globally addressable resources. 

>were the data in the output appended or was it overwritten?

Right now, we have this facet for Spark: https://github.com/OpenLineage/OpenLineage/pull/531/files#diff-584f22b59879726a80ab010ebde0c28f458c02dec84b45525da112dcc4bf4142

**Comment by cerveada** [comment]
> > As mentioned already, there is no guarantee that the COMPLETE message is the last one. But I must stop somewhere,
> > so this means any following data will be ignored.
> 
> Agreed. We'll fix that with adding `RUNNING` to the state enum.

Adding another state is fine, but I don't think it addresses mine issue. For that, the specification must define when all the job information were sent. For example, that after `COMPLETE` there will be no more messages.

**Comment by mobuchowski** [comment]
Agreed. What I ment additionally, is that the events that are now send with `COMPLETE` state and that aren't final will be send with `RUNNING` state.

**Comment by jenspfaug** [comment]
What is the plan for introducing the RUNNING state to the Spark plugin? This does not [seem](https://github.com/search?q=repo%3AOpenLineage%2FOpenLineage+RunEvent.EventType.&type=code) to be implemented yet. AFAIU @collado-mike had originally raised #636 to address the issue with Spark and then closed that issue in favour of this one.
Thanks!

**Comment by pawel-big-lebowski** [comment]
Clarification on run states in docs -> https://openlineage.io/docs/spec/run-cycle#run-states


![Diagram](https://openlineage.io/assets/images/run-life-cycle-1a4dba53c04cf3feb279e961da32dc8a.svg)
