### ISSUE TITLE
[INTEGRATION][SPARK] Implement dataset builders for alter table commands

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#616]
Spark 3.2.1 introduced new alter table commands. In order to collect this information, new dataset builders need to be created. 

https://github.com/apache/spark/blob/v3.2.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/v2AlterTableCommands.scala

**Comment by mobuchowski** [comment]
Can we do it without introducing separate Spark 3.2 tree? Just with `hasClasses`?

**Comment by tnazarew** [comment]
hi, please assign this to me.
