### ISSUE TITLE
[INTEGRATION][SPARK] Support org.apache.spark.sql.catalyst.plans.logical.Project for Delta Tables

### ISSUE THREAD

**Issue by wjohnson** [OpenLineage/OpenLineage#617]
It seems that a `Project` logical plan is the terminal node for a Delta event.  Currently OpenLineage does not support this as a Visitor and as a result, there are no output datasets.  I'd like to propose adding a ProjectVisitor that extracts the appropriate output dataset contents.

This example demonstrates the issue on Azure Databricks Runtime 6.4 (Spark 2.4.5)

```scala
val storageServiceName = "inputservice"
val storageContainerName = "inputcontainer"
val abfssRootPath = "abfss://"+storageContainerName+"@"+storageServiceName+".dfs.core.windows.net"
val outRootPath = "abfss://"+"outputdata"+"@"+storageServiceName+".dfs.core.windows.net"

val exampleA = (
  spark.read.format("delta")
  .load(abfssRootPath+"/examples/data/delta/exampleInputA")
)

val exampleB = (
  spark.read.format("delta")
  .load(abfssRootPath+"/examples/data/delta/exampleInputB")
)
val outputDf = exampleA.join(exampleB, exampleA("id") === exampleB("id"), "inner").drop(exampleB("id"))

outputDf.write.format("delta").mode("append").save(outRootPath + "/outputdata/delta/delta-in-delta-out")
```

Here's the truncated open lineage event that is produced:

```json
{
    "eventType": "START",
    "eventTime": "2022-03-18T12:58:53.112Z",
    "run": {
        "runId": "6068fde5-0e3e-4bd6-8bd9-fc3ebdb283ce",
        "facets": {
            "spark_unknown": {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
                "_schemaURL": "https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet",
                "output": {
                    "description": {
                        "@class": "org.apache.spark.sql.catalyst.plans.logical.Project",
                        "id": 1,
                        "projectList": ["some columns"],
                        "origin": 5,
                        "tags": {},
                        "schema": {
                            "type": "struct",
                            "fields": ["the fields"]
                        }
            },
            "spark_version": {
                "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
                "_schemaURL": "https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunFacet",
                "spark-version": "2.4.5",
                "openlineage-spark-version": "0.6.0-SNAPSHOT"
            }
        }
    },
    "job": {
        "namespace": "adbpurviewol1",
        "name": "databricks_shell.project",
        "facets": {}
    },
    "inputs": [
        {
            "namespace": "abfss://CONTAINER@SERVICE.dfs.core.windows.net",
            "name": "/examples/data/delta/exampleInputA",
            "facets": {
                "dataSource": {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet",
                    "name": "abfss://CONTAINER@SERVICE.dfs.core.windows.net",
                    "uri": "abfss://CONTAINER@SERVICE.dfs.core.windows.net"
                },
                "schema": {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet",
                    "fields": [
                        {
                            "name": "id",
                            "type": "integer"
                        },
                        {
                            "name": "postalCode",
                            "type": "string"
                        },
                        {
                            "name": "streetAddress",
                            "type": "string"
                        }
                    ]
                }
            },
            "inputFacets": {}
        },
        {
            "namespace": "abfss://CONTAINER@SERVICE.dfs.core.windows.net",
            "name": "/examples/data/delta/exampleInputB",
            "facets": {
                "dataSource": {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/DatasourceDatasetFacet.json#/$defs/DatasourceDatasetFacet",
                    "name": "abfss://CONTAINER@SERVICE.dfs.core.windows.net",
                    "uri": "abfss://CONTAINER@SERVICE.dfs.core.windows.net"
                },
                "schema": {
                    "_producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
                    "_schemaURL": "https://openlineage.io/spec/facets/1-0-0/SchemaDatasetFacet.json#/$defs/SchemaDatasetFacet",
                    "fields": [
                        {
                            "name": "id",
                            "type": "integer"
                        },
                        {
                            "name": "city",
                            "type": "string"
                        },
                        {
                            "name": "stateAbbreviation",
                            "type": "string"
                        }
                    ]
                }
            },
            "inputFacets": {}
        }
    ],
    "outputs": [],
    "producer": "https://github.com/OpenLineage/OpenLineage/tree/0.6.0-SNAPSHOT/integration/spark",
    "schemaURL": "https://openlineage.io/spec/1-0-2/OpenLineage.json#/$defs/RunEvent"
}

**Comment by collado-mike** [comment]
Hey @wjohnson , can you post a github gist with the log that's generated by running this Spark application? A `Project` as a final node doesn't really make sense - a `Project` is just a SELECT with some list of columns, but doesn't tell you where the data is going. It could be just printed to the console or stored in memory or anything. I think there must be some other SQL executions and/or RDD jobs that get executed here. If we can stitch together the `Project` with the actual write task, we can capture the actual output dataset.

**Comment by wjohnson** [comment]
@collado-mike You're absolutely right, Mike.  It looks like there was another event that does cover the execution start and job start events with the correct information.  It was buried in my logs due to Delta being so verbose (#423).

However, I'd still like to show you what I'm seeing in the Delta events as provided by OpenLineage. https://gist.github.com/wjohnson/8c6f136e272702793d404c6320cdf48d

You can see that each logical plan terminates with the Project class which is very, very weird.  How would Marquez handle such an event?  It has inputs but no outputs and otherwise looks like a totally valid event.

**Comment by collado-mike** [comment]
The gist of this is two-fold. First, the Delta source code executes a few jobs to read and update the Snapshot state - you can see this in the [source code](https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/Snapshot.scala#L429-L457). The snapshot state is loaded as a DataFrame (initialized to an `EmptyRDD`) so every time it needs to update the snapshot, it triggers a set of Spark SQL jobs.


Additionally, when writing to Delta, the `DeltaDataSource` code gets a `DataFrame`, which is converted to an RDD - see https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/commands/WriteIntoDelta.scala#L103-L201 . When the job executes, we have the plan for the original `DataFrame`, but the plan doesn't indicate what's being done with the data in the RDD. For that, we can fortunately see the original `SaveIntoDataSourceCommand` options, which include the `path` to where the data is written. We can look into how to reduce the number of events that get fired off here - some of them, like the Snapshot update jobs can be detected and filtered on the client side. Some of the events, though, may have to be stitched together or maybe even ignored server-side.

I think we should open a new issue that outlines the Delta source execution flow and we can try to reduce the amount of noise that comes out of it.

**Comment by collado-mike** [comment]
I've opened https://github.com/OpenLineage/OpenLineage/issues/628 which gives some details on the above issue with examples of the events that are being generated.

**Comment by wjohnson** [comment]
I'm closing this issue since, as Mike explained, my suggestion doesn't solve the root of the problem and the delta improvements and recommendations to filter certain events will help greatly.
