### ISSUE TITLE
OpenLineage artifacts published on PRs

### ISSUE THREAD

**Issue by wslulciuc** [OpenLineage/OpenLineage#62]
OpenLineage artifacts (`openlineage-java`, `openlineage-python`) are currently being published in PRs, see https://github.com/OpenLineage/OpenLineage/pull/60. We'll only want to publish artifacts on the `main` branch.

Related to #61

**Comment by mobuchowski** [comment]
This won't happen on ordinary PRs, as release workflow is tied to git tag, not branch or PR.
In this case, I've created RC release from branch to get around blocker with conflicting dependencies here and in airflow integration.
