### ISSUE TITLE
[INTEGRATION][SPARK] Limit number of delta events 

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#631]
Delta provider for Spark causes plenty of unnecessary OpenLineage events, especially for Spark 3.2.1 and delta package `io.delta:delta-core_2.12:1.0.0`. For example, a simple `insert into as select` script can cause 50 SparkListener events  with corresponding `START`/`COMPLETE` events. 

The behaviour was observed within integration test:
https://github.com/OpenLineage/OpenLineage/pull/607/files#diff-013568b94fa9a18c727677a04395c4c821feb51e3081de27a6536bd2a7244e44

A hacky workaround to that specific issue may be filtering within `OpenLineageSparkListener` class like:
```  public void onJobStart(SparkListenerJobStart jobStart) {
     if (jobStart
            .properties()
            .getProperty("spark.sql.extensions", "")
            .equals("io.delta.sql.DeltaSparkSessionExtension")
        && SQLExecution.getQueryExecution(jobStart.jobId()) == null) {
      return;
    }
```
which just prevents sending any `RDD` events in case of delta.

**Comment by wjohnson** [comment]
Just to note, when this is applied to a Databricks Spark cluster, I think the io.delta.sql.DeltaSparkSessionExtension will be different (they have a proprietary version of Delta).  It would be nice to include the Databricks class names or include a way to add that as part of the configuration.

**Comment by pawel-big-lebowski** [comment]
@wjohnson Are you able to find a name of a proprietary extension class?
Closing this task in favor of #628.

**Comment by wjohnson** [comment]
> @wjohnson Are you able to find a name of a proprietary extension class? Closing this task in favor of #628.

At the time I was thinking of `com.databricks.sql.transaction.tahoe.catalog.DeltaCatalog` but given the recent announcement of open sourcing all of Delta 2.0, I'm not sure if they will remove the 'tahoe' namespace.
