### ISSUE TITLE
[BUG][SPARK] LogicalRelationDatasetBuilder is Resulting in Incorrect Output Data Sources

### ISSUE THREAD

**Issue by wjohnson** [OpenLineage/OpenLineage#632]
Since 0.6.2, when a Spark logical plan uses ABFSS as an input data source, the input data source is **also found as an output data source**.

I've narrowed it down to these two commits that introduced the Abstract Query Plan Builder:
* [Abstract query plan builder approach to exposing SparkListenerEvents (08bdb32)](https://github.com/OpenLineage/OpenLineage/commit/08bdb322861dc7dcf40b1ff9e0b8cd20990797cf#)
* [Inject dataset version with AbstractQueryPlanDatasetBuilder (c1a7285)](https://github.com/OpenLineage/OpenLineage/commit/c1a7285d3962b6a1396bd689c8de68ba1d3cdc8c#)

Specifically, the `InternalEventHandlerFactory` class' method `createOutputDatasetBuilder` was modified in 08bdb32 to include `LogicalRelationVisitor` (now renamed to `integration/spark/src/main/common/java/io/openlineage/spark/agent/lifecycle/plan/LogicalRelationDatasetBuilder.java`).

In c1a7285 `Spark3DatasetBuilderFactory.java` was introduced where it calls `integration/spark/src/main/spark3/java/io/openlineage/spark3/agent/lifecycle/plan/LogicalRelationDatasetBuilder.java` the odd part is that its `isDefinedAt` just returns `true` but I think the `isDefinedAtLogicalPlan` balances it and prevents it from being called when it's not an actual LogicalRelation.

**Suggested Solution**: To get it back to the correct behavior for ABFSS, I don't think we should use LogicalRelationDatasetBuilder in the `getOutputBuilders` for 

* [Spark3DatasetBuilderFactory.java getOutputBuilders()](https://github.com/OpenLineage/OpenLineage/commit/c1a7285d3962b6a1396bd689c8de68ba1d3cdc8c#diff-9b3985e540029b0e398c1a10a2e00001f403070e96ddee9c5939694d6d065678R41)
* [Spark2DatasetBuilderFactory.java getOutputBuilders()](https://github.com/OpenLineage/OpenLineage/commit/c1a7285d3962b6a1396bd689c8de68ba1d3cdc8c#diff-60faf9769928ad00674e8961ac27177b10d8eb8caab36a262690186a14dab6f5R31)

Ideally we'd be able to INJECT `LogicalRelationDatasetBuilder` like it was being done in 08bdb32 when it was called `LogicalRelationVisitor`  but do it ONLY for getInputBuilders().

**Comment by wjohnson** [comment]
Tagging @pawel-big-lebowski  and @collado-mike since it was their two commits that changed the behavior.

**Comment by pawel-big-lebowski** [comment]
Hi @wjohnson. Thank you for pointing this out. I think I saw similar issue which occured due to wrong constructor call of `LogicalRelationDatasetBuilder`, specifically `searchDependencies` argument which should be set to `false` for output dataset builders. 

If it is it, then it got resolved within todays merged PR: 
https://github.com/OpenLineage/OpenLineage/pull/607/files#diff-9b3985e540029b0e398c1a10a2e00001f403070e96ddee9c5939694d6d065678R42

**Comment by wjohnson** [comment]
> Hi @wjohnson. Thank you for pointing this out. I think I saw similar issue which occured due to wrong constructor call of `LogicalRelationDatasetBuilder`, specifically `searchDependencies` argument which should be set to `false` for output dataset builders.
> 
> If it is it, then it got resolved within todays merged PR: https://github.com/OpenLineage/OpenLineage/pull/607/files#diff-9b3985e540029b0e398c1a10a2e00001f403070e96ddee9c5939694d6d065678R42

Testing now!

**Comment by wjohnson** [comment]
@pawel-big-lebowski - For the latest commit, I'm getting a complie error :(  I see that it compiles on CI but I've tried a fresh clone and I still can't get it to compile.

```
wj@DESKTOP:~/repos/OpenLineage/integration/spark$ ./gradlew build -x test

> Task :compileJava
/home/wj/repos/OpenLineage/integration/spark/src/main/common/java/io/openlineage/spark/agent/lifecycle/plan/SaveIntoDataSourceCommandVisitor.java:142: error: method newDatasetFacets in class OpenLineage cannot be applied to given types;
                        .newDatasetFacets(
                        ^
  required: DocumentationDatasetFacet,DatasourceDatasetFacet,DatasetVersionDatasetFacet,SchemaDatasetFacet,DatasetProviderDatasetFacet,LifecycleStateChangeDatasetFacet
  found: DocumentationDatasetFacet,DatasourceDatasetFacet,DatasetVersionDatasetFacet,SchemaDatasetFacet,LifecycleStateChangeDatasetFacet
  reason: actual and formal argument lists differ in length
/home/wj/repos/OpenLineage/integration/spark/src/main/common/java/io/openlineage/spark/agent/lifecycle/plan/InsertIntoDataSourceVisitor.java:48: error: method newDatasetFacets in class OpenLineage cannot be applied to given types;
                        .newDatasetFacets(
                        ^
  required: DocumentationDatasetFacet,DatasourceDatasetFacet,DatasetVersionDatasetFacet,SchemaDatasetFacet,DatasetProviderDatasetFacet,LifecycleStateChangeDatasetFacet
  found: DocumentationDatasetFacet,DatasourceDatasetFacet,DatasetVersionDatasetFacet,SchemaDatasetFacet,LifecycleStateChangeDatasetFacet
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

**Comment by collado-mike** [comment]
You'll probably need to build and install the java client locally - from `$PROJECT_DIR/client/java` run `./gradlew publishToMavenLocal`. Then cd back to the Spark directory and re-build

**Comment by collado-mike** [comment]
I actually called this out in https://github.com/OpenLineage/OpenLineage/issues/628 - glad to see the cause was already found and fixed
> Note that here, the input dataset and the output dataset are the same - since the Filter is the root node, its children are analyzed and the dataset is found and assumed to be the output. This is incorrect and shows a loop in the lineage where one does not exist.

**Comment by wjohnson** [comment]
Yes!  @collado-mike thank you for that guidance! And @pawel-big-lebowski  once I got it compiled it worked like a charm.  I'll close this one  Thank you both!!
