### ISSUE TITLE
[INTEGRATION][SPARK] Change event types for JobStart and JobEnd events

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#636]
In Spark SQL, a single QueryExecution can invoke one or more Spark Jobs, initiating multiple `SparkListenerJobStart` and `SparkListenerJobEnd` events. Currently, we emit a `START` event for every `SparkListenerSQLExecutionStart` and for every `SparkListenerJobStart` event. Similarly, we emit a `COMPLETE` event for every `SparkListenerSQLExecutionEnd` and `SparkListenerJobEnd` event. This is confusing to the backend, as a single QueryExecution always emits multiple `COMPLETE` events and in the case where a single QueryExecution invokes multiple jobs, the backend will receive a `START` event after the first `COMPLETE` event.

I propose changing the `SparkListenerJobStart` event to trigger a `STAGE_START` event and the `SparkListenerJobEnd` event to trigger a `STAGE_COMPLETE` event. This makes it clear to the backend that only a portion of the job is complete and that the full job is not completed until the `SparkListenerSQLExecutionEnd` event triggers the final `COMPLETE` event.

Note that this change must only effect Spark SQL QueryExecutions - RDD-only jobs should continue to emit the `START` and `COMPLETE` events as there is no other context with which to bind various RDD jobs together.

**Comment by collado-mike** [comment]
Actually, I forgot the spec dictates an enum for the type here: https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.json#L11-L17 . We can change the event types to `OTHER`, but I kinda hate to lose visibility into the actual lifecycle events.

@julienledem , @wslulciuc , what do you think about updating the spec to be more versatile WRT to lifecycle state changes? Should these just be a new facet? Or can we take advantage of the existing fields?

**Comment by jenspfaug** [comment]
@collado-mike do you have some follow-on thoughts on how to resolve this ambiguity on the backend side, given that #599 did not actually lead to any changes in the Spark plugin?
