### ISSUE TITLE
airflow: Capture DAG runs as parent runs of the tasks.

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#646]

**Comment by mobuchowski** [comment]
What's the difference between this and ParentRunFacet?

**Comment by collado-mike** [comment]
Implemented in https://github.com/OpenLineage/OpenLineage/pull/664

**Comment by conorbev** [comment]
Remaining work:

- Report start time of the DAG
- Report end time of the DAG
- Report whether the DAG was a success or a failure

**Comment by howardyoo** [comment]
So, in order to `properly` capture DAG start and end time, we DEFINITELY need DAG listener, much similar to how we implemented TASK listener in airflow.
