### ISSUE TITLE
[INTEGRATION][SPARK][3.1.2]BigQuery-Broken Lineage

### ISSUE THREAD

**Issue by Grudra1** [OpenLineage/OpenLineage#652]
I am trying to get the lineage for a sample job where source and target both are Bigquery, however I am seeing an issue, that the lineage is broken into two parts.
First, when I trace the lineage from source datasets, I can see the entire flow, but the target is not the actual Bigquery table, rather the temp gcs file, which Bigquery uses to load data into. It has the same schema as expected and it detects it as a valid output dataset and adds this as a dataset in GS namespace.
Second, when we trace the lineage from the actual bigquery sink table, I can see another job where there is no source (probably the temp file was removed by the time this lineage was being built, which ideally would be the source for this job), but a job and the actual bigquery target table.

All the jobs are correctly mapped under same parent job, yet dataset wise lineage is not a single complete one.

Expectaion : The ideal scenario should be to ignore the temp file as a valid dataset, and to show the actual bigquery table as the sink dataset. Current situation is adding new gcs temp files as datasets for each run and flooding the GS dataset namespace.

I am adding the following packages to my spark-submit : 
io.openlineage:openlineage-spark:0.4.0
com.google.cloud.spark:spark-bigquery-with-dependencies_2.12:0.23.2

Below are some screenshots : 

All jobs : 
![image](https://user-images.githubusercontent.com/102662426/161729409-a8c4582c-fa56-4955-bbaf-9f40e7cc097b.png)

First part of lineage where temp file is shown as the final dataset:
![image](https://user-images.githubusercontent.com/102662426/161730359-3df4818c-44bb-466f-a2a0-868cc511d500.png)

Another part of the jobs, where actual Bigquery Table is shown as the sink dataset :

![image](https://user-images.githubusercontent.com/102662426/161730720-53d3d4c6-601a-4cc6-8717-65e1147abe53.png)

New temp files are added as valid datasets at each run of the job : 
![image](https://user-images.githubusercontent.com/102662426/161731571-258328c7-d027-4654-954a-2f4ac868438e.png)

**Comment by howardyoo** [comment]
@Grudra1 , we have a new release of openlineage (0.8.1) would it be possible for you to retest and see if the problem persists with the new version? Thanks.

**Comment by Grudra1** [comment]
Yeah certainly ... have few busy weeks ahead, I'll retest as soon as I get
a chance !

**Comment by mobuchowski** [comment]
I'll close this. If you find anything @Grudra1 feel free to reopen it.

**Comment by Grudra1** [comment]
Sure thing.. apologies for not being able to check this yet...had to focus
on some other areas...would check once opportunity comes up and reopen if
found any issues.

Thanks a ton !!
