### ISSUE TITLE
[EPIC] Column Level Lineage

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#673]
New feature to support Column Level Lineage in OpenLineage Specifications

**Comment by pawel-big-lebowski** [comment]
@howardyoo there is still one column level lineage issue (https://github.com/OpenLineage/OpenLineage/issues/738) that should be a part of this epic.

**Comment by howardyoo** [comment]
> @howardyoo there is still one column level lineage issue (#738) that should be a part of this epic.

Ok, got it. Added it to the EPIC, and also reopened the epic.
