### ISSUE TITLE
[EPIC] OpenLineage SQL parsing improvements

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#675]
# Overview
As OpenLineage is being used more and more, especially with airflow integration, there is number of growing issues related to exporters that primarily uses SQL statements. Various SQL statements, some simple and some complex goes through, and therefore, it is essential for the extractors to be able to properly parse all of those SQL statements and extract the necessary input and output datasets from it.

These parsing requirements are pervasive to number of operators such as PostgreSQL, snowflake, redshift, etc, as SQL language is the common input for those operators (and hence the extractors). This EPIC will contain issues related to the common SQL related issues for OpenLineage.

**Comment by mobuchowski** [comment]
@howardyoo do you have any other issues with SQL parser?
