### ISSUE TITLE
[INTEGRATION][Airflow] SQL Query unable to generate input and output table for MERGE INTO USING

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#679]
The following SQL inside airflow's Snowflake operator did not yield any input and output datasets
```
merge into "m"."d" as d_m using (
    with f_d_u_l_u as (
        select r_number() over (partition by m_id order by c_dt desc) as rownum,
            *
        from "c"."u_l_u"
        where len(m_id) = 32
        and len(c_name) > 1
        and p_at = '2022-04-14'
            qualify rownum = 1
    )
    select
    c,
    c_code,
    c_name,
    r_code,
    r_name,
    z,
    m_id
    from f_d_u_l_u
) as src on d_m.m_id = src.m_id
when matched then update set
d_m.c_name = src.c_name,
d_m.c_code = src.c_code,
d_m.r_name = src.r_name,
d_m.r_code = src.r_code,
d_m.c = src.c,
d_m.z = src.z
when not matched then insert (m_id,c_name,c_code,r_name,r_code,c,z)
values (m_id,c_name,c_code,r_name,r_code,c,z)
;
```
Expected result:
should have input and output datasets for the SQL query.

**Comment by mobuchowski** [comment]
Will be fixed in the new parser as soon as sqlparser-rs releases support for QUALIFY expression: https://github.com/sqlparser-rs/sqlparser-rs/pull/465

(disabled) test here: https://github.com/OpenLineage/OpenLineage/blob/b7f67ae33f8c421f2c07eb49c31a23d4354871a2/integration/sql/tests/tests_merge.rs

**Comment by howardyoo** [comment]
> Will be fixed in the new parser as soon as sqlparser-rs releases support for QUALIFY expression: [sqlparser-rs/sqlparser-rs#465](https://github.com/sqlparser-rs/sqlparser-rs/pull/465)
> 
> (disabled) test here: https://github.com/OpenLineage/OpenLineage/blob/b7f67ae33f8c421f2c07eb49c31a23d4354871a2/integration/sql/tests/tests_merge.rs

Gotit - please keep us updated when the feature is released and then the testing passes!
