### ISSUE TITLE
How to integrate OpenLineage with BigQuery?

### ISSUE THREAD

**Issue by sridhar562345** [OpenLineage/OpenLineage#699]
I want to set up data lineage for BigQuery can someone guide me through this? I am not able to find any proper documentation.

**Comment by collado-mike** [comment]
How are you orchestrating your queries? Are you using Airflow or dbt? Or are you scheduling them in BigQuery itself?

**Comment by howardyoo** [comment]
@sridhar562345 , any more information for your question here? We have not heard back from you for a month.

**Comment by sridhar562345** [comment]
Thanks for the info, I will try and let you know. For now, I am closing this one.
