### ISSUE TITLE
Add a Kafka backend for sending lineage events

### ISSUE THREAD

**Issue by julienledem** [OpenLineage/OpenLineage#70]
The goal is to have a Backend abstraction:
java: https://github.com/MarquezProject/marquez/blob/main/clients/java/src/main/java/marquez/client/Backend.java
python: https://github.com/MarquezProject/marquez/blob/main/clients/python/marquez_client/backend.py
that can be configured to send HTTP posts or Kafka events

**Comment by mobuchowski** [comment]
Closes: https://github.com/OpenLineage/OpenLineage/pull/530
