### ISSUE TITLE
airflow: schemaURL missing in open lineage json message

### ISSUE THREAD

**Issue by cerveada** [OpenLineage/OpenLineage#702]
According to specification `schemaURL` is mandatory field of RunEvent, but airflow integration sends a json messgaes without it.

Tested on
integration/airflow 0.7.1
Airflow 2.2.4

**Comment by kacpermuda** [comment]
I was not able to reproduce this for latest version of OpenLineage, the `schemaUrl` is always present. Closing it for now, feel free to reopen if this issue persists.
