### ISSUE TITLE
Spark S3 and Hive Tables integration

### ISSUE THREAD

**Issue by mdiazmonzon** [OpenLineage/OpenLineage#713]
I have Hive set up over S3. Currently when we run tasks using spark Open Lineage saves the file path as the dataset name in the backend, however when the table is referenced by a hive operator in airflow the dataset name is saved in a database format. The lineage from spark is not linking  to  the table name from hive due to this
E.G.
Spark S3 path: /mypath/schema/tablename (this will save as the dataset name)
Hive : schema.tablename (this will save as the dataset name)

**Comment by collado-mike** [comment]
Link to https://github.com/OpenLineage/OpenLineage/issues/435

**Comment by howardyoo** [comment]
closing as #435 has been closed.
