### ISSUE TITLE
Spark jobs save under different names or in elongated format

### ISSUE THREAD

**Issue by mdiazmonzon** [OpenLineage/OpenLineage#715]
When using the spark library some jobs are saving with different names depending if they are shuffling or inserting thus not able to create lineage

Source data set connects to this task
**deequ_dev_dw_nonpii_events_hourly_agg_hour=00_ds=2022_04_02_2.shuffled_map_partitions_sql_execution_map_partitions_union_map_partitions_hadoop**

Output dataset connects to this task
**deequ_dev_dw_nonpii_events_hourly_agg_hour=00_ds=2022_04_02_2.execute_save_into_data_source_command**

----

Another problem is when spark jobs are submitted with `elongated names` or `unique names` by the user, that contains timestamp at the end of the app name, such that lineage being emitted will have a multiple instance of the same type of job, but due to their unique name, will be stored as a different set of jobs and thus complicate the graph as more jobs are run.

Perhaps there may be a feature that would receive a formatting instructions inside the lineage event, that when processing, may overwrite the name without prefix or postfixes, but create a symlink so that the actual job name can be identified, which will prevent the lineage graph from getting cluttered, while maintaining information.

This problem also happens when the job's namespace move from A to B, so even it is a same job, due to the different namespaces, the two are handled separately. Sometimes we also want to avoid that from happening.

**Comment by tnazarew** [comment]
As I see it we have two issues here:
how do we want to supply modified `appName` we get from spark and how to store it. 
For now we have `appName` directly copied into  a `name` attribute of a `Job`. 

supply:
To solve the issue we would have to be able to modify it somehow.

1. overwrite with configurable value - we could supply a string as some config property 
2. supply some way of extracting `name` from `appName` - here we could use some regex 
or any other way of modification definition (length of prefix or suffix or sth)

first way is simpler and faster to implement, second more versatile and complex.

storing:
Here it's the question: Do we want to add new field or keep storing it as `name`
in first case we loose the original value, but the second one requires changes in the model and in the way the messages are grouped.


as for namespaces we would simply have to modify a model, not sure in what way tho

**Comment by julienledem** [comment]
I think you're solution 1. here works. 
Provide a way for the user to define the job name. Do you have an idea on how to do it?
