### ISSUE TITLE
[FEATURE] Support for  'disabling' openlineage

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#726]
In OpenLineage, we can set `OPENLINEAGE_URL` as the endpoint for sending openlineage data. However, there is a time when user may not choose to emit openlineage metrics - due to various reasons (testing, maintenance, troubleshooting, etc.). Currently, there is no way to stop lineage from being emitted, as long as the proper OPENLINEAGE_URL is specified.

Therefore, I would like to propose an additional env variable that can control whether the OPENLINEAGE should be enabled/disabled, by having the new variable `OPENLINEAGE_ENABLED`.

By default, if no such variables are found, it should be set to `True` where openlineage will continue to emit lineage data. However, when the variable is set to `OPENLINEAGE_ENABLED=False`, then even thought there may be a valid URL given, the client should not emit any lineage data to the server.

**Comment by wslulciuc** [comment]
+1 as I've heard others in the wild requesting a similar option to toggle metadata collection for our integrations. My first thought would have been to add toggling support at the client level (`java`, `py` ), but that would mean the integration would extract metadata, but the client `emit()` call would be a no-op. So, with `OPENLINEAGE_ENABLED` we'll want to essentially disable the integration all together, meaning the integration would skip over any metadata extraction code.

**Comment by howardyoo** [comment]
> +1 as I've heard others in the wild requesting a similar option to toggle metadata collection for our integrations. My first thought would have been to add toggling support at the client level (`java`, `py` ), but that would mean the integration would extract metadata, but the client `emit()` call would be a no-op. So, with `OPENLINEAGE_ENABLED` we'll want to essentially disable the integration all together, meaning the integration would skip over any metadata extraction code.

+1 on this, when `OPENLINEAGE_ENAGLED` is set to `false`, it should NOT ONLY stop emitting the events, but also should NOT DO any extractions or operations at all.

**Comment by julienledem** [comment]
agreed with Willy as well. When disabled it should be a no-op that does nothing

**Comment by kaxil** [comment]
> agreed with Willy as well. When disabled it should be a no-op that does nothing

+1 I agree
