### ISSUE TITLE
airflow: Postgresql Extractor having invalid namespace and name of datasets

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#757]
When the postgreSQL operator is being used in airflow, the following data is being observed received into openlineage:
```
{
  "totalCount": 1,
  "datasets": [
    {
      "id": {
        "namespace": "postgres://None:None",
        "name": "\"conn_type\":\"postgres\",\"login\":\"testuser\",\"password\":\"passw0rd\",\"host\":\"redshift-cluster.1sdlkfhja.us-east-1.redshift.amazonaws.com\",\"port\":5439,\"schema\":\"test\"}.public.zapier_orders_api"
      },
      "type": "DB_TABLE",
      "name": "\"conn_type\":\"postgres\",\"login\":\"testuser\",\"password\":\"passw0rd\",\"host\":\"redshift-cluster.1sdlkfhja.us-east-1.redshift.amazonaws.com\",\"port\":5439,\"schema\":\"dev\"}.public.zapier_orders_api",
      "physicalName""\"conn_type\":\"postgres\",\"login\":\"testuser\",\"password\":\"passw0rd\",\"host\":\"redshift-cluster.1sdlkfhja.us-east-1.redshift.amazonaws.com\",\"port\":5439,\"schema\":\"dev\"}.public.zapier_orders_api",
      "createdAt": "2022-05-09T08:47:26.719862Z",
      "updatedAt": "2022-05-18T08:47:16.734515Z",
      "namespace": "postgres://None:None",
      "sourceName": "postgres://None:None",
      "fields": [
        {
          "name": "f_p",
          "type": "varchar",
          "tags": [],
          "description": null
        },
```
Notice the dataset ID that has incorrect namespace, as well as name section that does not contain name, but what seems to be the object representation of connection object containing sensitive information like host, user, password, etc, which is incorrect. It feels as if the postgres extractor of airflow is trying to treat connection object as string.

- a better approach would be to check the type of the name given, and if it is of type string, set it, but if it is not a string type, make sure to prevent it from being stringified to the name value.
- also, make sure the proper namespace could be derived in the namespace section, not like `postgres://None:None`.

**Comment by JDarDagran** [comment]
@howardyoo could you please pass more details when did you observe this bug? I am not able to reproduce this
