### ISSUE TITLE
[BUG][INTEGRATION][Airflow] Incorrect Operator tracked in Airflow 2.3

### ISSUE THREAD

**Issue by conorbev** [OpenLineage/OpenLineage#767]
I see a change in the metadata collected from Airflow jobs which I think was introduced with the combination of Airflow 2.3/OpenLineage 0.8.1. There's an `airflow_version` facet that contains an `operator` attribute that is added by the integration.

In Airflow 2.2 for a `PostgresOperator` that attribute would have had a value: `airflow.providers.postgres.operators.postgres.PostgresOperator` but now in Airflow 2.3 that operator is tracked as: `airflow.models.taskinstance.TaskInstance`
( fwiw there's also a `taskInfo` attribute in there containing a json string which itself has a `operator` that is still set to `PostgresOperator` )

**Comment by howardyoo** [comment]
![image](https://user-images.githubusercontent.com/32691630/171485308-538517df-4aa7-4fac-b513-42c481ddea7d.png)

Screenshot for this issue.

**Comment by howardyoo** [comment]
@JDarDagran , I see that you have assigned yourself to this issue - are there any updates on this issue?
