### ISSUE TITLE
airflow: Implement DAG run listener

### ISSUE THREAD

**Issue by howardyoo** [OpenLineage/OpenLineage#768]
The current airflow integration for OpenLineage is focused on the operators used by Task Instance.
Therefore, the lineage keeps track of which task runs have ran, as well as what kind of operator and its behaviors caused the data sets to be created , altered, etc.

However, the current implementation has a few limitation of having to 'only' rely on Task instances:
1. It is difficult to determine when the DAG run actually ended, as task instances themselves, do not keep track of whether all the task instances have been completed and reached the end of the DAG run.
2. Due to the fact that concepts like DAGrun did not exist, each task instances had to contain dag run related information in its facets, resulting in many redundant information to be persisted.
3. It was inefficient for Openlineage to keep track of the delays and events on 'DAGrun' level, as getting the start and end of the dagrun meant assembling task instances, sorting it on smallest start and end times, and calculating the overall delays.
4. Other information such as DAGrun status was not as easy to determine, as each task instances only keeps track of task instance status.

Therefore, OpenLineage implementation for Apache Airflow integration should have the additional DAGrun level runevents and facets to cover the DAGrun side of things.
1. Listener should be able to capture when the DAGrun starts and stops (via scheduler) - and produce runevents on DAGruns.
2. Additional code to create dagrun facet should be designed and implemented
3. Additional test codes to test these should be created.

**Comment by conorbev** [comment]
There may be a relation between this work and #552 

I'm not sure what would be best but what I'm thinking is perhaps instead of trying to encode Airflow task level dependencies in each individual job if this issue (768) results in a DAG run being its own separate lineage event then maybe at DAG Run start time we can grab the entire task-dependency graph from Airflow and store it once at the DAG level in OL.

**Comment by howardyoo** [comment]
Thank you, @mobuchowski !
