### ISSUE TITLE
flink: get lineage from DataStream Iceberg sink

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#782]
Validate that we support Flink 1.16

example for Iceberg:
https://github.com/apache/iceberg/blob/master/flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java

**Comment by harels** [comment]
@pawel-big-lebowski assuming this is still the issue we are using to track the work on Flink to support the Iceberg sink?
