### ISSUE TITLE
spark: Support for Spark 3.3.0 

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#862]
Spark 3.3.0 has been realized on 16th July 2022. 
We still need to wait for a docker image -> https://hub.docker.com/r/bitnami/spark/tags?page=1&name=3.3

After that we can turn on integration tests for the latest Spark version and see how is it working.

**Comment by pawel-big-lebowski** [comment]
Although bitnami docker image is already available, we still need to wait for iceberg & delta support: 
 - https://github.com/delta-io/delta/issues/1217
 - https://github.com/apache/iceberg/pull/5056

Draft PR on our side:
 - https://github.com/OpenLineage/OpenLineage/pull/896

**Comment by LucaSoato** [comment]
Is Delta already supported as a format in OpenLineage? :)

**Comment by pawel-big-lebowski** [comment]
@LucaSoato Yes, OpenLineage calls Delta a provider and is able to detect provider like delta or iceberg from query plans.
