### ISSUE TITLE
Update integration tests to use mock-server container

### ISSUE THREAD

**Issue by collado-mike** [OpenLineage/OpenLineage#87]
See https://github.com/OpenLineage/OpenLineage/issues/90

To integration test the various OL integrations, we should replace all of the existing references to the Marquez container with a mock-server, such as was done in the Spark integration. This avoids a dependency on the Marquez implementation in the OpenLineage integration tests, so a bug in the implementation won't cause failures in the integration tests.

**Comment by mobuchowski** [comment]
Removed dependency in https://github.com/OpenLineage/OpenLineage/pull/129
