### ISSUE TITLE
UI Bug: New Extractors Not Recognized

### ISSUE THREAD

**Issue by denimalpaca** [OpenLineage/OpenLineage#892]
New operators being handled by new extractors are showing an orange UI tab noting that the code contains an unsupported operator. The operator is clearly being supported, as it is part of the lineage graph. Additionally, the operator is correlated with an extractor, so it seems to be a front end / UI issue. See screenshot below.

![Screen Shot 2022-06-24 at 2 30 46 PM](https://user-images.githubusercontent.com/2653551/175644885-05f44323-9552-41af-be73-02142fdcd8b4.png)

**Comment by conorbev** [comment]
This doesn't actually look like a UI issue to me. I took a look at the job in the Marquez API and the latest run there has a `inputVersions` populated by with the `FORESTFIRES_2` dataset but it also has a `unknownSourceAttribute` facet set (which is what the UI is picking up from).

It is coming from `_producer: "https://github.com/OpenLineage/OpenLineage/tree/0.9.0/integration/airflow",`

@mobuchowski I would have expected that #762 fixed this but maybe custom extractors are a special case?

**Comment by mobuchowski** [comment]
I don't think they are. Would need to see actual event to understand what's happening. Also, extractors can add this facet themselves.
