### ISSUE TITLE
databricks: OL kills SparkContext on databricks platform

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#941]
### Failing scenario

Following Spark script:
```
df = spark.createDataFrame([
    {'a': 1, 'b': 2},
    {'a': 3, 'b': 4}
])
df.write.mode("overwrite").saveAsTable("default.temp")
```
kills Spark context with an error log:
```
22/07/21 11:30:09 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoClassDefFoundError: org/apache/spark/sql/catalyst/plans/logical/CreateV2Table
```

### Problems

There are two problems here: 
 * An error in `apply` method should not break the whole Spark job no matter what the cause is. 
 * Databricks platform, by a great chance, replaces & modifies Spark plan's classes which are no longer accessible in our code although they exist in Spark's source code on github.

**Comment by wjohnson** [comment]
@pawel-big-lebowski what Databricks Runtime was this occurring on?  Databricks Runtime 10.4?
