### ISSUE TITLE
[PROPOSAL] Add application name to the specification

### ISSUE THREAD

**Issue by dpenmets** [OpenLineage/OpenLineage#952]
A new parameter - Application Name needs to be added to both the job and dataset parameters.

**Comment by howardyoo** [comment]
could you elaborate what this `application name` refers to?

**Comment by julienledem** [comment]
I spoke with @dpenmets, the goal is to capture ownership of job and dataset.
I'm proposing to add an `ownership` facet to both `Dataset` and `Job` to capture this 
Example:
```
ownership: {
   owners: [ { name: "application:application_name"} ]
}
```
Schema:
```
{
  "$schema" : "https://json-schema.org/draft/2020-12/schema",
  "$id" : "https://openlineage.io/spec/facets/1-0-0/OwnershipDatasetFacet.json",
  "$defs" : {
    "OwnershipDatasetFacet" : {
      "allOf" : [ {
        "$ref" : "https://openlineage.io/spec/1-0-3/OpenLineage.json#/$defs/DatasetFacet"
      }, {
        "type" : "object",
        "properties" : {
          "owners" : {
            "description" : "The owners of the dataset.",
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "name" : {
                  "description" : "The URN describing the owner of the Dataset",
                  "type" : "URN",
                  "example" : "application:app_name"
                },
                "type" : {
                  "description" : "The type of ownership (optional)",
                  "type" : "string",
                  "example" : "MAINTAINER"
                }
              },
              "required" : [ "name" ]
            }
          }
        }
      } ],
      "type" : "object"
    }
  },
  "type" : "object",
  "properties" : {
    "schema" : {
      "$ref" : "#/$defs/OwnershipDatasetFacet"
    }
  }
}
```

**Comment by mobuchowski** [comment]
`OwnershipDatasetFacet` -> `DatasetOwnershipDatasetFacet` and `JobOwnershipDatasetFacet` - we had the same discussion with `DatasetVersionDatasetFacet` - it more clearly indicates what the ownership is about. Also, I think attaching the same facet to both `Run` and `Job` would require us to rework how the Java client generated code looks like.

`"type" : "URN"` - I would make that `String` - more permissive, I don't think there's anything about ownership that requires us to narrow it down to URN.

**Comment by wslulciuc** [comment]
Great to finally see a proposal for dataset and job ownership! For clarity, my understanding of ownership rules are:

1. A **job** can be an **owner of** a **dataset**
2. An **individual** can be an **owner of** a **dataset** or **job**
3. A **team** can be an **owner of** a **dataset** or **job**

Meaning, `OwnershipDatasetFacet` would only apply to datasets, and not job ownership? If we were to also add a facet for job ownership, I would agree with @mobuchowski that we would need to define a `OwnershipJobFacet`.


QQ: Do we need to understand the ownership format (string, email, URN, etc)? We do see URNs used in by AWS (IAM [ARNs](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)), and GCP does list members of a IAM role as a URNs (see [IAM Overview](https://cloud.google.com/iam/docs/overview)):

```json
{
  "role": "roles/storage.objectAdmin",
   "members": [
     "user:ali@example.com",
     "serviceAccount:my-other-app@appspot.gserviceaccount.com",
     "group:admins@example.com",
     "domain:google.com"
   ]
}
``` 

GCP does also have an interesting naming convention for Google Accounts (`user:`), service accounts (`serviceAccount:`), Google group (`group:`), etc. Does the ownership facet also intend to define the URN prefix? @julienledem, in your example, was that the intention of `application:`, to define the URN type?

**Comment by howardyoo** [comment]
Correct me if I'm wrong, but since `OwnershipDatasetFacet` and `OwnershipJobFacet` basically contains the same information, perhaps we should use a single schema like `OwnershipFacet` and use it both for Job and Dataset facets?

**Comment by julienledem** [comment]
Maciej is right that we need to define two facets. One for jobs and one for datasets. This is a side effect of strongly separating dataset and job facets.
I am happy with making name a string.
To Willy, I think we can allow people to use type and name in the way you describe. I will update the description and explanation per your description.

**Comment by julienledem** [comment]
I have opened a PR

**Comment by conorbev** [comment]
Can we populate this facet in the Airflow integration from the owner field defined in the Airflow DAG ?

**Comment by julienledem** [comment]
@conorbev Yes that would a great. Do you want to open a follow up issue for that?
