### ISSUE TITLE
spark: fix flaky testInsertIntoDataSourceDirVisitor

### ISSUE THREAD

**Issue by mobuchowski** [OpenLineage/OpenLineage#962]
This test intermittently fails: like https://app.circleci.com/pipelines/github/OpenLineage/OpenLineage/4205/workflows/ea5d2d2a-8610-4e76-9c2e-b884ca36d7e1/jobs/47607

**Comment by pawel-big-lebowski** [comment]
Duplicate of https://github.com/OpenLineage/OpenLineage/issues/999
found that too late, sry
