### ISSUE TITLE
Databricks 10.4 Uses com.databricks.sql.managedcatalog.UnityCatalogV2Proxy

### ISSUE THREAD

**Issue by wjohnson** [OpenLineage/OpenLineage#964]
Databricks Runtime 10.4 LTS uses `com.databricks.sql.managedcatalog.UnityCatalogV2Proxy` when querying a Hive table.

This causes an exception to occur and no input / output is returned for the relevant end of the query.

**Comment by pawel-big-lebowski** [comment]
@wjohnson I was solving some databricks issue which was similar to this and merged it yesterday. It affected `create table as select` syntax. Did you check it directly on main?

**Comment by wjohnson** [comment]
@pawel-big-lebowski  that's exactly what I'm experiencing.  I just confirmed even after the recent PR you made #950 the issue persists on Databricks Runtime 10.4.
