### ISSUE TITLE
Facet for Dataset Version ID

### ISSUE THREAD

**Issue by RNHTTR** [OpenLineage/OpenLineage#976]
Some data tools (such as [iceberg](https://iceberg.apache.org/spec/#table-metadata) and [delta](https://docs.delta.io/latest/quick-start.html#read-older-versions-of-data-using-time-travel) have built-in table versioning systems. As such, OpenLineage should support emitting a dataset version ID as a facet (for example, as discussed in [this comment](https://github.com/MarquezProject/marquez/issues/1977#issuecomment-1119112558) discussing Marquez dataset versions.)

**Comment by collado-mike** [comment]
I think what you're looking for is https://github.com/OpenLineage/OpenLineage/blob/main/spec/facets/DatasetVersionDatasetFacet.json

**Comment by howardyoo** [comment]
@RNHTTR , looks like we have a schema defined to emit version information in dataset. Please confirm if this is something that can be used for your purpose.
