### ISSUE TITLE
Run flink integration tests against 1.14 and 1.15 versions

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#979]
Similarly to Apache Spark, modify circle-ci to run integration tests for multiple Flink versions (1.13 and 1.14). 
Document list of supported Flink versions [here](https://github.com/OpenLineage/OpenLineage/tree/main/integration).

**Comment by mobuchowski** [comment]
1.14 and 1.15

**Comment by mzareba382** [comment]
We are now able to check against Flink 1.14 and 1.15.
