### ISSUE TITLE
flaky test - SparkReadWriteIntegTest fails too often on circle-ci

### ISSUE THREAD

**Issue by pawel-big-lebowski** [OpenLineage/OpenLineage#999]
```
<========-----> 63% EXECUTING [9m 10s]> :app:integrationTest > 41 tests completed> :app:integrationTest > Executing test io.openlineage.spark.agent.lifecycle.Sp> IDLEio.openlineage.spark.agent.lifecycle.SparkReadWriteIntegTest testInsertIntoDataSourceDirVisitor(Path, SparkSession) FAILED

  org.mockito.exceptions.verification.TooFewActualInvocations: 
  eventEmitter.emit(<Capturing argument>);
  Wanted *at least* 4 times:
  -> at io.openlineage.spark.agent.EventEmitter.emit(EventEmitter.java:63)
  But was 2 times:
  -> at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:77)
  -> at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:102)
      at io.openlineage.spark.agent.lifecycle.SparkReadWriteIntegTest.testInsertIntoDataSourceDirVisitor(SparkReadWriteIntegTest.java:337)
```

**Comment by mobuchowski** [comment]
I think we're seeing this more often now because we're running tests on more Spark versions - there's bigger chance that one of them fails.

**Comment by howardyoo** [comment]
I am curious to know what would be a good way to prevent the errors. Will it be due to the fact that some of the resources from spark that the test requires are simply not available in time? In that case, would having an induced delay help alleviate this issue..? Just wondering...

**Comment by pawel-big-lebowski** [comment]
Openlineage integration requires optimized logical plan to generate OL events. Spark internals work in a way that:
* When start event is triggered, `QueryExecution` (containing a logical plan) is stored in a static map and the event can access it by a `queryId`.
* Openlineage gets `QueryExecution` from a static map field by `queryId` when a job is started.
* When spark is stopping job execution, it removes `QueryExecution` from a static map.

The logic described above is implemented here: https://github.com/apache/spark/blob/v3.3.0/sql/core/src/main/scala/org/apache/spark/sql/execution/SQLExecution.scala#L98-L130

The problem is that in case of really quick spark jobs (like `create view command`), `QueryExecution` may be removed by Spark before we access it within `start` event. 

Fortunately, this is not causing other integration tests fail. Additionally, version of Spark, on the master branch, is already passing `QueryExecution` to `SparkListenerSQLExecutionStart`: 
https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/SQLExecution.scala#L109

This means, we do have a problem that rarely happens and there is no easy solution to that at the moment. However, we will be able to solve it in future Spark versions. 

The test related to this issue (`testInsertIntoDataSourceDirVisitor`) is failing because of missing create view command event which is unrelated to this test. The best solution for now is to remove the failing assertion.
